// Austrian Bundesliga & 2. Liga club financial data
// Source: Austrian Football Bundesliga (Bundesliga GmbH) financial transparency reporting
// Monetary values in EUR millions (source in k€, divided by 1000).
// Flagged and excluded: SK Austria Klagenfurt (no audited accounts filed),
//   Schwarz-Weiss Bregenz (no audited accounts filed),
//   FAC, SV Horn, SV Lafnitz, KSV 1919, SV Stripfing, SKU Amstetten,
//   ASK Voitsberg (insufficient data / revenue too small).
// Most recent year: 2023-24 season accounts.
import type { EUClub } from "./euClubs";

// ─── Austrian Bundesliga ────────────────────────────────────────────────────
export const atClubs: EUClub[] = [
  {
    slug: "fc-blau-weiss-linz",
    name: "FC Blau-Weiß Linz",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Linz",
    currency: "EUR",
    stadium: { name: "Hofmann Personal Stadion", capacity: 12800, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 9.73,
      wage_bill: 4.98,
      wage_to_revenue_pct: 51.2,
      net_profit: 0.08,
      total_liabilities: 3.3,
      equity: -0.43,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 3.66,
      wage_bill: 2.65,
      wage_to_revenue_pct: 72.4,
      pre_tax_profit: -0.61,
    },
    historical: [
      { season: "2020-21", revenue: 2.39, wage_bill: 1.39, net_profit: 0.07 },
      { season: "2021-22", revenue: 2.83, wage_bill: 1.6, net_profit: -0.09 },
      { season: "2022-23", revenue: 3.66, wage_bill: 2.65, net_profit: -0.61 },
      { season: "2023-24", revenue: 9.73, wage_bill: 4.98, net_profit: 0.08 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-red-bull-salzburg",
    name: "FC Red Bull Salzburg",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Salzburg",
    currency: "EUR",
    stadium: { name: "Red Bull Arena", capacity: 29520, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 182.59,
      wage_bill: 46.41,
      wage_to_revenue_pct: 25.4,
      net_profit: 24.69,
      total_liabilities: 73.0,
      equity: 161.69,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 186.82,
      wage_bill: 51.39,
      wage_to_revenue_pct: 27.5,
      pre_tax_profit: 32.23,
    },
    historical: [
      { season: "2020-21", revenue: 112.12, wage_bill: 53.3, net_profit: 4.97 },
      { season: "2021-22", revenue: 152.53, wage_bill: 56.54, net_profit: 15.39 },
      { season: "2022-23", revenue: 186.82, wage_bill: 51.39, net_profit: 32.23 },
      { season: "2023-24", revenue: 182.59, wage_bill: 46.41, net_profit: 24.69 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fk-austria-wien",
    name: "FK Austria Wien",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Vienna",
    currency: "EUR",
    stadium: { name: "Generali Arena", capacity: 13500, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 48.38,
      wage_bill: 14.59,
      wage_to_revenue_pct: 30.2,
      net_profit: 11.24,
      total_liabilities: 59.44,
      equity: -9.42,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 30.66,
      wage_bill: 14.56,
      wage_to_revenue_pct: 47.5,
      pre_tax_profit: -6.85,
    },
    historical: [
      { season: "2020-21", revenue: 29.93, wage_bill: 13.21, net_profit: -4.69 },
      { season: "2021-22", revenue: 23.58, wage_bill: 12.62, net_profit: -7.06 },
      { season: "2022-23", revenue: 30.66, wage_bill: 14.56, net_profit: -6.85 },
      { season: "2023-24", revenue: 48.38, wage_bill: 14.59, net_profit: 11.24 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "gak",
    name: "GAK",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Graz",
    currency: "EUR",
    stadium: { name: "Merkur Arena (shared)", capacity: 15400, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 6.19,
      wage_bill: 3.69,
      wage_to_revenue_pct: 59.6,
      net_profit: -0.44,
      total_liabilities: 2.69,
      equity: 0.01,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 4.98,
      wage_bill: 2.77,
      wage_to_revenue_pct: 55.6,
      pre_tax_profit: -0.07,
    },
    historical: [
      { season: "2020-21", revenue: 3.47, wage_bill: 1.72, net_profit: 0.46 },
      { season: "2021-22", revenue: 3.54, wage_bill: 2.21, net_profit: -0.28 },
      { season: "2022-23", revenue: 4.98, wage_bill: 2.77, net_profit: -0.07 },
      { season: "2023-24", revenue: 6.19, wage_bill: 3.69, net_profit: -0.44 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "lask",
    name: "LASK",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Linz",
    currency: "EUR",
    stadium: { name: "Raiffeisen Arena", capacity: 19080, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 48.51,
      wage_bill: 17.78,
      wage_to_revenue_pct: 36.7,
      net_profit: 3.38,
      total_liabilities: 94.64,
      equity: 33.77,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 26.47,
      wage_bill: 14.64,
      wage_to_revenue_pct: 55.3,
      pre_tax_profit: -3.74,
    },
    historical: [
      { season: "2020-21", revenue: 23.38, wage_bill: 12.91, net_profit: 0.08 },
      { season: "2021-22", revenue: 30.89, wage_bill: 15.1, net_profit: 0.48 },
      { season: "2022-23", revenue: 26.47, wage_bill: 14.64, net_profit: -3.74 },
      { season: "2023-24", revenue: 48.51, wage_bill: 17.78, net_profit: 3.38 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "scr-altach",
    name: "SCR Altach",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Altach",
    currency: "EUR",
    stadium: { name: "Cashpoint Arena", capacity: 8500, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 10.98,
      wage_bill: 6.37,
      wage_to_revenue_pct: 58.0,
      net_profit: 0.01,
      total_liabilities: 1.86,
      equity: 3.11,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 11.02,
      wage_bill: 6.05,
      wage_to_revenue_pct: 54.9,
      pre_tax_profit: 0.37,
    },
    historical: [
      { season: "2020-21", revenue: 8.02, wage_bill: 5.24, net_profit: 0.46 },
      { season: "2021-22", revenue: 10.28, wage_bill: 5.75, net_profit: 0.59 },
      { season: "2022-23", revenue: 11.02, wage_bill: 6.05, net_profit: 0.37 },
      { season: "2023-24", revenue: 10.98, wage_bill: 6.37, net_profit: 0.01 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sk-rapid",
    name: "SK Rapid",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Vienna",
    currency: "EUR",
    stadium: { name: "Allianz Stadion", capacity: 28345, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 44.38,
      wage_bill: 20.39,
      wage_to_revenue_pct: 45.9,
      net_profit: 0.19,
      total_liabilities: 42.49,
      equity: 21.6,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 45.34,
      wage_bill: 18.38,
      wage_to_revenue_pct: 40.5,
      pre_tax_profit: 0.05,
    },
    historical: [
      { season: "2020-21", revenue: 40.48, wage_bill: 21.23, net_profit: 0.7 },
      { season: "2021-22", revenue: 49.63, wage_bill: 20.26, net_profit: 5.76 },
      { season: "2022-23", revenue: 45.34, wage_bill: 18.38, net_profit: 0.05 },
      { season: "2023-24", revenue: 44.38, wage_bill: 20.39, net_profit: 0.19 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sk-sturm-graz",
    name: "SK Sturm Graz",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Graz",
    currency: "EUR",
    stadium: { name: "Merkur Arena", capacity: 15400, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 54.38,
      wage_bill: 25.32,
      wage_to_revenue_pct: 46.6,
      net_profit: 0.03,
      total_liabilities: 20.45,
      equity: 7.92,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 46.55,
      wage_bill: 20.1,
      wage_to_revenue_pct: 43.2,
      pre_tax_profit: 2.0,
    },
    historical: [
      { season: "2020-21", revenue: 14.82, wage_bill: 9.61, net_profit: -0.5 },
      { season: "2021-22", revenue: 28.56, wage_bill: 14.47, net_profit: 2.27 },
      { season: "2022-23", revenue: 46.55, wage_bill: 20.1, net_profit: 2.0 },
      { season: "2023-24", revenue: 54.38, wage_bill: 25.32, net_profit: 0.03 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "tsv-hartberg",
    name: "TSV Hartberg",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Hartberg",
    currency: "EUR",
    stadium: { name: "Profertil Arena", capacity: 4200, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 8.8,
      wage_bill: 6.37,
      wage_to_revenue_pct: 72.4,
      net_profit: -0.59,
      total_liabilities: 1.43,
      equity: 0.21,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 7.53,
      wage_bill: 6.24,
      wage_to_revenue_pct: 82.9,
      pre_tax_profit: -1.06,
    },
    historical: [
      { season: "2020-21", revenue: 5.88, wage_bill: 4.04, net_profit: 0.33 },
      { season: "2021-22", revenue: 6.37, wage_bill: 4.46, net_profit: -0.1 },
      { season: "2022-23", revenue: 7.53, wage_bill: 6.24, net_profit: -1.06 },
      { season: "2023-24", revenue: 8.8, wage_bill: 6.37, net_profit: -0.59 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "wsg-tirol",
    name: "WSG Tirol",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Wattens",
    currency: "EUR",
    stadium: { name: "Berghauptmann Graber Stadion", capacity: 7000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 6.15,
      wage_bill: 4.02,
      wage_to_revenue_pct: 65.4,
      net_profit: -0.65,
      total_liabilities: 2.87,
      equity: 0.77,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 6.88,
      wage_bill: 4.2,
      wage_to_revenue_pct: 61.0,
      pre_tax_profit: -0.56,
    },
    historical: [
      { season: "2020-21", revenue: 7.38, wage_bill: 3.78, net_profit: 1.04 },
      { season: "2021-22", revenue: 7.81, wage_bill: 4.27, net_profit: 0.26 },
      { season: "2022-23", revenue: 6.88, wage_bill: 4.2, net_profit: -0.56 },
      { season: "2023-24", revenue: 6.15, wage_bill: 4.02, net_profit: -0.65 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "wolfsberger-ac",
    name: "Wolfsberger AC",
    country: "Austria",
    league: "Austrian Bundesliga",
    city: "Wolfsberg",
    currency: "EUR",
    stadium: { name: "Lavanttal Arena", capacity: 7300, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 14.96,
      wage_bill: 7.06,
      wage_to_revenue_pct: 47.2,
      net_profit: 0.46,
      total_liabilities: 4.15,
      equity: 4.6,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 11.86,
      wage_bill: 6.33,
      wage_to_revenue_pct: 53.4,
      pre_tax_profit: 0.08,
    },
    historical: [
      { season: "2020-21", revenue: 17.5, wage_bill: 7.73, net_profit: 1.49 },
      { season: "2021-22", revenue: 10.24, wage_bill: 5.96, net_profit: 0.17 },
      { season: "2022-23", revenue: 11.86, wage_bill: 6.33, net_profit: 0.08 },
      { season: "2023-24", revenue: 14.96, wage_bill: 7.06, net_profit: 0.46 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Austrian 2. Liga ──────────────────────────────────────────────────
  {
    slug: "admira-wacker",
    name: "Admira Wacker",
    country: "Austria",
    league: "Austrian 2. Liga",
    city: "Mödling",
    currency: "EUR",
    stadium: { name: "BSFZ-Arena", capacity: 8000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 7.97,
      wage_bill: 4.62,
      wage_to_revenue_pct: 58.0,
      net_profit: 0.0,
      total_liabilities: 5.04,
      equity: -1.62,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 7.4,
      wage_bill: 4.24,
      wage_to_revenue_pct: 57.3,
      pre_tax_profit: 0.01,
    },
    historical: [
      { season: "2020-21", revenue: 10.29, wage_bill: 7.08, net_profit: -0.47 },
      { season: "2021-22", revenue: 9.55, wage_bill: 6.37, net_profit: 0.0 },
      { season: "2022-23", revenue: 7.4, wage_bill: 4.24, net_profit: 0.01 },
      { season: "2023-24", revenue: 7.97, wage_bill: 4.62, net_profit: 0.0 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-liefering",
    name: "FC Liefering",
    country: "Austria",
    league: "Austrian 2. Liga",
    city: "Salzburg",
    currency: "EUR",
    stadium: { name: "FC Liefering Stadion", capacity: 3500, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 20.93,
      wage_bill: 7.88,
      wage_to_revenue_pct: 37.6,
      net_profit: 0.0,
      total_liabilities: 6.53,
      equity: 0.05,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 20.46,
      wage_bill: 8.49,
      wage_to_revenue_pct: 41.5,
      pre_tax_profit: 0.0,
    },
    historical: [
      { season: "2020-21", revenue: 18.23, wage_bill: 7.01, net_profit: 0.0 },
      { season: "2021-22", revenue: 19.11, wage_bill: 8.1, net_profit: 0.0 },
      { season: "2022-23", revenue: 20.46, wage_bill: 8.49, net_profit: 0.0 },
      { season: "2023-24", revenue: 20.93, wage_bill: 7.88, net_profit: 0.0 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "first-vienna-fc",
    name: "First Vienna FC",
    country: "Austria",
    league: "Austrian 2. Liga",
    city: "Vienna",
    currency: "EUR",
    stadium: { name: "Hohe Warte", capacity: 6000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 5.5,
      wage_bill: 3.37,
      wage_to_revenue_pct: 61.3,
      net_profit: 0.01,
      total_liabilities: 2.12,
      equity: 0.55,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 4.63,
      wage_bill: 2.77,
      wage_to_revenue_pct: 59.8,
      pre_tax_profit: 0.03,
    },
    historical: [
      { season: "2021-22", revenue: 3.49, wage_bill: 2.03, net_profit: 0.16 },
      { season: "2022-23", revenue: 4.63, wage_bill: 2.77, net_profit: 0.03 },
      { season: "2023-24", revenue: 5.5, wage_bill: 3.37, net_profit: 0.01 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sc-austria-lustenau",
    name: "SC Austria Lustenau",
    country: "Austria",
    league: "Austrian 2. Liga",
    city: "Lustenau",
    currency: "EUR",
    stadium: { name: "Rheinparkstadion", capacity: 8800, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 6.79,
      wage_bill: 2.64,
      wage_to_revenue_pct: 38.9,
      net_profit: 0.4,
      total_liabilities: 1.16,
      equity: 0.17,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 6.73,
      wage_bill: 2.62,
      wage_to_revenue_pct: 38.9,
      pre_tax_profit: 0.92,
    },
    historical: [
      { season: "2020-21", revenue: 2.6, wage_bill: 1.52, net_profit: 0.0 },
      { season: "2021-22", revenue: 2.35, wage_bill: 1.76, net_profit: -0.8 },
      { season: "2022-23", revenue: 6.73, wage_bill: 2.62, net_profit: 0.92 },
      { season: "2023-24", revenue: 6.79, wage_bill: 2.64, net_profit: 0.4 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "skn-st-poelten",
    name: "SKN St. Pölten",
    country: "Austria",
    league: "Austrian 2. Liga",
    city: "St. Pölten",
    currency: "EUR",
    stadium: { name: "NV Arena", capacity: 8000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 7.01,
      wage_bill: 4.07,
      wage_to_revenue_pct: 58.1,
      net_profit: -0.24,
      total_liabilities: 3.77,
      equity: -1.57,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 6.99,
      wage_bill: 3.35,
      wage_to_revenue_pct: 47.9,
      pre_tax_profit: -0.15,
    },
    historical: [
      { season: "2020-21", revenue: 8.82, wage_bill: 5.02, net_profit: 0.43 },
      { season: "2021-22", revenue: 6.73, wage_bill: 3.81, net_profit: -0.32 },
      { season: "2022-23", revenue: 6.99, wage_bill: 3.35, net_profit: -0.15 },
      { season: "2023-24", revenue: 7.01, wage_bill: 4.07, net_profit: -0.24 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sv-ried",
    name: "SV Ried",
    country: "Austria",
    league: "Austrian 2. Liga",
    city: "Ried",
    currency: "EUR",
    stadium: { name: "josko Arena", capacity: 7680, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 8.24,
      wage_bill: 4.59,
      wage_to_revenue_pct: 55.7,
      net_profit: -0.02,
      total_liabilities: 3.87,
      equity: 2.06,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Austrian Football Bundesliga financial transparency reporting. Values in €m (source in k€).. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 10.81,
      wage_bill: 5.44,
      wage_to_revenue_pct: 50.3,
      pre_tax_profit: 0.99,
    },
    historical: [
      { season: "2020-21", revenue: 8.43, wage_bill: 4.96, net_profit: 0.49 },
      { season: "2021-22", revenue: 10.52, wage_bill: 5.42, net_profit: 0.86 },
      { season: "2022-23", revenue: 10.81, wage_bill: 5.44, net_profit: 0.99 },
      { season: "2023-24", revenue: 8.24, wage_bill: 4.59, net_profit: -0.02 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
];
