// Swiss Super League club financial data
// Source: Swiss Football League financial fair play / transparency reporting
// Monetary values in EUR millions converted from TCHF at 0.96 EUR/CHF.
// net_profit field stores post-tax result; net_transfer_result noted in data_notes.
// Most recent year: FY2024 (2023/24 season).
import type { EUClub } from "./euClubs";

export const chClubs: EUClub[] = [
  {
    slug: "bsc-young-boys",
    name: "BSC Young Boys",
    country: "Switzerland",
    league: "Super League",
    city: "Bern",
    currency: "EUR",
    stadium: { name: "Wankdorf Stadion", capacity: 32000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 76.48,
      wage_bill: 37.7,
      wage_to_revenue_pct: 49.3,
      net_profit: 6.4,
      total_liabilities: 84.44,
      equity: 55.91,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 79663 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 80.28,
      wage_bill: 42.2,
      wage_to_revenue_pct: 52.6,
      pre_tax_profit: 6.44,
    },
    historical: [
      { season: "2020-21", revenue: 72.52, wage_bill: 35.61, net_profit: 14.21 },
      { season: "2021-22", revenue: 44.8, wage_bill: 30.4, net_profit: 6.4 },
      { season: "2022-23", revenue: 80.28, wage_bill: 42.2, net_profit: 6.44 },
      { season: "2023-24", revenue: 76.48, wage_bill: 37.7, net_profit: 6.4 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-basel-1893",
    name: "FC Basel 1893",
    country: "Switzerland",
    league: "Super League",
    city: "Basel",
    currency: "EUR",
    stadium: { name: "Joggeli (St. Jakob-Park)", capacity: 38512, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 39.4,
      wage_bill: 31.05,
      wage_to_revenue_pct: 78.8,
      net_profit: 14.98,
      total_liabilities: 79.06,
      equity: 16.2,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 41039 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 45.64,
      wage_bill: 31.25,
      wage_to_revenue_pct: 68.5,
      pre_tax_profit: 0.26,
    },
    historical: [
      { season: "2020-21", revenue: 48.19, wage_bill: 36.22, net_profit: -15.17 },
      { season: "2021-22", revenue: 42.98, wage_bill: 31.06, net_profit: -1.11 },
      { season: "2022-23", revenue: 45.64, wage_bill: 31.25, net_profit: 0.26 },
      { season: "2023-24", revenue: 39.4, wage_bill: 31.05, net_profit: 14.98 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-lausanne-sport",
    name: "FC Lausanne-Sport",
    country: "Switzerland",
    league: "Super League",
    city: "Lausanne",
    currency: "EUR",
    stadium: { name: "Stade de la Pontaise", capacity: 13900, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 23.2,
      wage_bill: 17.57,
      wage_to_revenue_pct: 75.7,
      net_profit: 0.15,
      total_liabilities: 18.31,
      equity: 0.47,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 24163 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 20.84,
      wage_bill: 16.09,
      wage_to_revenue_pct: 77.2,
      pre_tax_profit: -1.83,
    },
    historical: [
      { season: "2020-21", revenue: 18.65, wage_bill: 9.19, net_profit: -0.13 },
      { season: "2022-23", revenue: 20.84, wage_bill: 16.09, net_profit: -1.83 },
      { season: "2023-24", revenue: 23.2, wage_bill: 17.57, net_profit: 0.15 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-lugano",
    name: "FC Lugano",
    country: "Switzerland",
    league: "Super League",
    city: "Lugano",
    currency: "EUR",
    stadium: { name: "Cornaredo", capacity: 6330, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 28.3,
      wage_bill: 17.01,
      wage_to_revenue_pct: 60.1,
      net_profit: -0.05,
      total_liabilities: 23.42,
      equity: -8.18,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 29480 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 28.35,
      wage_bill: 15.3,
      wage_to_revenue_pct: 54.0,
      pre_tax_profit: 1.63,
    },
    historical: [
      { season: "2020-21", revenue: 7.08, wage_bill: 9.56, net_profit: -6.04 },
      { season: "2021-22", revenue: 26.97, wage_bill: 12.55, net_profit: 3.86 },
      { season: "2022-23", revenue: 28.35, wage_bill: 15.3, net_profit: 1.63 },
      { season: "2023-24", revenue: 28.3, wage_bill: 17.01, net_profit: -0.05 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-luzern",
    name: "FC Luzern",
    country: "Switzerland",
    league: "Super League",
    city: "Lucerne",
    currency: "EUR",
    stadium: { name: "Swissporarena", capacity: 16800, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 20.57,
      wage_bill: 16.45,
      wage_to_revenue_pct: 80.0,
      net_profit: -2.38,
      total_liabilities: 20.74,
      equity: -6.59,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 21428 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 20.22,
      wage_bill: 15.85,
      wage_to_revenue_pct: 78.4,
      pre_tax_profit: -2.98,
    },
    historical: [
      { season: "2020-21", revenue: 15.94, wage_bill: 12.36, net_profit: -3.16 },
      { season: "2021-22", revenue: 20.17, wage_bill: 14.88, net_profit: -3.1 },
      { season: "2022-23", revenue: 20.22, wage_bill: 15.85, net_profit: -2.98 },
      { season: "2023-24", revenue: 20.57, wage_bill: 16.45, net_profit: -2.38 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-sion",
    name: "FC Sion",
    country: "Switzerland",
    league: "Super League",
    city: "Sion",
    currency: "EUR",
    stadium: { name: "Tourbillon", capacity: 14283, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 12.01,
      wage_bill: 10.74,
      wage_to_revenue_pct: 89.4,
      net_profit: -4.91,
      total_liabilities: 52.06,
      equity: -34.14,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 12508 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 13.5,
      wage_bill: 17.0,
      wage_to_revenue_pct: 125.9,
      pre_tax_profit: -7.64,
    },
    historical: [
      { season: "2020-21", revenue: 15.22, wage_bill: 12.3, net_profit: -2.99 },
      { season: "2021-22", revenue: 17.15, wage_bill: 14.71, net_profit: -8.16 },
      { season: "2022-23", revenue: 13.5, wage_bill: 17.0, net_profit: -7.64 },
      { season: "2023-24", revenue: 12.01, wage_bill: 10.74, net_profit: -4.91 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-st-gallen-1879",
    name: "FC St.Gallen 1879",
    country: "Switzerland",
    league: "Super League",
    city: "St. Gallen",
    currency: "EUR",
    stadium: { name: "kybunpark", capacity: 20400, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 32.59,
      wage_bill: 19.15,
      wage_to_revenue_pct: 58.8,
      net_profit: 0.01,
      total_liabilities: 10.33,
      equity: 18.38,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 33943 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 30.95,
      wage_bill: 16.32,
      wage_to_revenue_pct: 52.7,
      pre_tax_profit: 0.58,
    },
    historical: [
      { season: "2020-21", revenue: 20.4, wage_bill: 13.5, net_profit: 0.84 },
      { season: "2021-22", revenue: 29.83, wage_bill: 14.84, net_profit: 1.56 },
      { season: "2022-23", revenue: 30.95, wage_bill: 16.32, net_profit: 0.58 },
      { season: "2023-24", revenue: 32.59, wage_bill: 19.15, net_profit: 0.01 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-winterthur",
    name: "FC Winterthur",
    country: "Switzerland",
    league: "Super League",
    city: "Winterthur",
    currency: "EUR",
    stadium: { name: "Schützenwiese", capacity: 8600, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2022-23",
      revenue: 12.73,
      wage_bill: 7.72,
      wage_to_revenue_pct: 60.6,
      net_profit: 0.0,
      total_liabilities: 6.19,
      equity: 0.15,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: n/a TCHF.. Post-tax result used as net profit.",
    },
    prior_year: null,
    historical: [
      { season: "2022-23", revenue: 12.73, wage_bill: 7.72, net_profit: 0.0 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-zuerich",
    name: "FC Zürich",
    country: "Switzerland",
    league: "Super League",
    city: "Zürich",
    currency: "EUR",
    stadium: { name: "Letzigrund", capacity: 26104, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 26.22,
      wage_bill: 18.84,
      wage_to_revenue_pct: 71.9,
      net_profit: 0.09,
      total_liabilities: 14.48,
      equity: 0.46,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 27310 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 28.69,
      wage_bill: 18.47,
      wage_to_revenue_pct: 64.4,
      pre_tax_profit: 0.33,
    },
    historical: [
      { season: "2020-21", revenue: 20.49, wage_bill: 14.79, net_profit: 0.05 },
      { season: "2021-22", revenue: 26.29, wage_bill: 17.17, net_profit: -0.11 },
      { season: "2022-23", revenue: 28.69, wage_bill: 18.47, net_profit: 0.33 },
      { season: "2023-24", revenue: 26.22, wage_bill: 18.84, net_profit: 0.09 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "grasshopper-club-zuerich",
    name: "Grasshopper Club Zürich",
    country: "Switzerland",
    league: "Super League",
    city: "Zürich",
    currency: "EUR",
    stadium: { name: "Letzigrund", capacity: 26104, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 9.82,
      wage_bill: 13.6,
      wage_to_revenue_pct: 138.5,
      net_profit: -13.21,
      total_liabilities: 4.32,
      equity: 3.22,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 10227 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 10.39,
      wage_bill: 14.36,
      wage_to_revenue_pct: 138.2,
      pre_tax_profit: -13.52,
    },
    historical: [
      { season: "2021-22", revenue: 8.43, wage_bill: 15.0, net_profit: -13.54 },
      { season: "2022-23", revenue: 10.39, wage_bill: 14.36, net_profit: -13.52 },
      { season: "2023-24", revenue: 9.82, wage_bill: 13.6, net_profit: -13.21 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "servette-fc",
    name: "Servette FC",
    country: "Switzerland",
    league: "Super League",
    city: "Geneva",
    currency: "EUR",
    stadium: { name: "Stade de Genève", capacity: 30084, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 42.77,
      wage_bill: 24.3,
      wage_to_revenue_pct: 56.8,
      net_profit: 0.0,
      total_liabilities: 9.25,
      equity: 0.67,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: Swiss Football League financial fair play reporting. Converted from TCHF at 0.96 EUR/CHF. Original revenue FY2023-24: 44549 TCHF.. Post-tax result used as net profit.",
    },
    prior_year: {
      season: "2022-23",
      revenue: 22.41,
      wage_bill: 16.32,
      wage_to_revenue_pct: 72.8,
      pre_tax_profit: 0.19,
    },
    historical: [
      { season: "2020-21", revenue: 18.33, wage_bill: 12.76, net_profit: 3.98 },
      { season: "2021-22", revenue: 18.76, wage_bill: 15.01, net_profit: -3.27 },
      { season: "2022-23", revenue: 22.41, wage_bill: 16.32, net_profit: 0.19 },
      { season: "2023-24", revenue: 42.77, wage_bill: 24.3, net_profit: 0.0 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
];
