// German 2. Bundesliga club financial data
// Source: DFL / German FA financial transparency reporting
// Monetary values in EUR millions (source in k€, divided by 1000).
// net_profit field stores post-tax result (pre-tax not available from this dataset).
// Flagged and excluded: SG Dynamo Dresden (only 1 year of available data).
// Most recent year: FY2023-24 accounts.
import type { EUClub } from "./euClubs";

export const de2Clubs: EUClub[] = [
  {
    slug: "1-fc-kaiserslautern",
    name: "1. FC Kaiserslautern",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Kaiserslautern",
    currency: "EUR",
    stadium: { name: "Fritz Walter Stadion", capacity: 49780, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 57.22,
      wage_bill: 24.46,
      wage_to_revenue_pct: 42.7,
      net_profit: 4.5,
      total_liabilities: 46.1,
      equity: 5.28,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 39.27,
      wage_bill: 17.26,
      wage_to_revenue_pct: 44.0,
      pre_tax_profit: 0.16,
    },
    historical: [
      { season: "2020-21", revenue: 34.23, wage_bill: 9.47, net_profit: 11.33 },
      { season: "2021-22", revenue: 19.06, wage_bill: 11.14, net_profit: -4.12 },
      { season: "2022-23", revenue: 39.27, wage_bill: 17.26, net_profit: 0.16 },
      { season: "2023-24", revenue: 57.22, wage_bill: 24.46, net_profit: 4.5 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "1-fc-magdeburg",
    name: "1. FC Magdeburg",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Magdeburg",
    currency: "EUR",
    stadium: { name: "MDCC-Arena", capacity: 27250, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 35.16,
      wage_bill: 21.08,
      wage_to_revenue_pct: 60.0,
      net_profit: -4.27,
      total_liabilities: 19.37,
      equity: 2.82,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 25.14,
      wage_bill: 11.85,
      wage_to_revenue_pct: 47.1,
      pre_tax_profit: 2.0,
    },
    historical: [
      { season: "2020-21", revenue: 9.33, wage_bill: 5.75, net_profit: -0.09 },
      { season: "2021-22", revenue: 41.11, wage_bill: 21.18, net_profit: -2.49 },
      { season: "2022-23", revenue: 25.14, wage_bill: 11.85, net_profit: 2.0 },
      { season: "2023-24", revenue: 35.16, wage_bill: 21.08, net_profit: -4.27 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "1-fc-nuernberg",
    name: "1. FC Nürnberg",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Nuremberg",
    currency: "EUR",
    stadium: { name: "Max-Morlock-Stadion", capacity: 50000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 53.04,
      wage_bill: 27.3,
      wage_to_revenue_pct: 51.5,
      net_profit: -2.04,
      total_liabilities: 18.82,
      equity: 9.52,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 49.65,
      wage_bill: 16.25,
      wage_to_revenue_pct: 32.7,
      pre_tax_profit: 0.33,
    },
    historical: [
      { season: "2019-20", revenue: 53.8, wage_bill: 24.1, net_profit: 1.72 },
      { season: "2020-21", revenue: 34.04, wage_bill: 20.91, net_profit: -9.37 },
      { season: "2021-22", revenue: 14.73, wage_bill: 7.34, net_profit: -0.01 },
      { season: "2022-23", revenue: 49.65, wage_bill: 16.25, net_profit: 0.33 },
      { season: "2023-24", revenue: 53.04, wage_bill: 27.3, net_profit: -2.04 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "dsc-arminia-bielefeld",
    name: "DSC Arminia Bielefeld",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Bielefeld",
    currency: "EUR",
    stadium: { name: "SchücoArena", capacity: 27849, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 25.27,
      wage_bill: 11.81,
      wage_to_revenue_pct: 46.7,
      net_profit: -2.08,
      total_liabilities: 15.96,
      equity: -3.91,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2020-21",
      revenue: 49.27,
      wage_bill: 30.65,
      wage_to_revenue_pct: 62.2,
      pre_tax_profit: -1.66,
    },
    historical: [
      { season: "2019-20", revenue: 30.47, wage_bill: 18.27, net_profit: -2.93 },
      { season: "2020-21", revenue: 49.27, wage_bill: 30.65, net_profit: -1.66 },
      { season: "2023-24", revenue: 25.27, wage_bill: 11.81, net_profit: -2.08 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "eintracht-braunschweig",
    name: "Eintracht Braunschweig",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Braunschweig",
    currency: "EUR",
    stadium: { name: "Eintracht-Stadion", capacity: 23325, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 29.75,
      wage_bill: 15.99,
      wage_to_revenue_pct: 53.7,
      net_profit: -0.24,
      total_liabilities: 10.58,
      equity: 0.64,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 28.27,
      wage_bill: 14.51,
      wage_to_revenue_pct: 51.3,
      pre_tax_profit: 0.16,
    },
    historical: [
      { season: "2020-21", revenue: 22.44, wage_bill: 12.94, net_profit: -0.84 },
      { season: "2021-22", revenue: 16.53, wage_bill: 8.9, net_profit: -0.51 },
      { season: "2022-23", revenue: 28.27, wage_bill: 14.51, net_profit: 0.16 },
      { season: "2023-24", revenue: 29.75, wage_bill: 15.99, net_profit: -0.24 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fc-schalke-04",
    name: "FC Schalke 04",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Gelsenkirchen",
    currency: "EUR",
    stadium: { name: "Veltins-Arena", capacity: 62271, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 69.56,
      wage_bill: 30.06,
      wage_to_revenue_pct: 43.2,
      net_profit: -0.96,
      total_liabilities: 100.19,
      equity: -103.97,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 164.52,
      wage_bill: 57.8,
      wage_to_revenue_pct: 35.1,
      pre_tax_profit: 6.24,
    },
    historical: [
      { season: "2019-20", revenue: 169.5, wage_bill: 111.0, net_profit: -53.07 },
      { season: "2020-21", revenue: 199.21, wage_bill: 88.25, net_profit: -1.13 },
      { season: "2021-22", revenue: 154.76, wage_bill: 78.47, net_profit: -20.05 },
      { season: "2022-23", revenue: 164.52, wage_bill: 57.8, net_profit: 6.24 },
      { season: "2023-24", revenue: 69.56, wage_bill: 30.06, net_profit: -0.96 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "fortuna-duesseldorf",
    name: "Fortuna Düsseldorf",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Düsseldorf",
    currency: "EUR",
    stadium: { name: "Merkur Spiel-Arena", capacity: 54600, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 68.05,
      wage_bill: 29.14,
      wage_to_revenue_pct: 42.8,
      net_profit: 0.57,
      total_liabilities: 36.87,
      equity: 1.42,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 50.58,
      wage_bill: 26.18,
      wage_to_revenue_pct: 51.8,
      pre_tax_profit: -2.99,
    },
    historical: [
      { season: "2019-20", revenue: 80.38, wage_bill: 37.76, net_profit: 0.0 },
      { season: "2020-21", revenue: 46.64, wage_bill: 24.11, net_profit: -2.01 },
      { season: "2021-22", revenue: 46.42, wage_bill: 24.24, net_profit: -1.19 },
      { season: "2022-23", revenue: 50.58, wage_bill: 26.18, net_profit: -2.99 },
      { season: "2023-24", revenue: 68.05, wage_bill: 29.14, net_profit: 0.57 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "hannover-96",
    name: "Hannover 96",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Hanover",
    currency: "EUR",
    stadium: { name: "HDI Arena", capacity: 49000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 54.99,
      wage_bill: 30.22,
      wage_to_revenue_pct: 55.0,
      net_profit: -0.06,
      total_liabilities: 55.03,
      equity: 8.26,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 47.46,
      wage_bill: 29.18,
      wage_to_revenue_pct: 61.5,
      pre_tax_profit: -3.83,
    },
    historical: [
      { season: "2019-20", revenue: 55.26, wage_bill: 34.02, net_profit: -11.14 },
      { season: "2020-21", revenue: 47.7, wage_bill: 31.27, net_profit: -8.84 },
      { season: "2021-22", revenue: 53.0, wage_bill: 30.99, net_profit: -0.46 },
      { season: "2022-23", revenue: 47.46, wage_bill: 29.18, net_profit: -3.83 },
      { season: "2023-24", revenue: 54.99, wage_bill: 30.22, net_profit: -0.06 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "hertha-bsc",
    name: "Hertha BSC",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Berlin",
    currency: "EUR",
    stadium: { name: "Olympiastadion Berlin", capacity: 74667, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 93.85,
      wage_bill: 45.79,
      wage_to_revenue_pct: 48.8,
      net_profit: -33.33,
      total_liabilities: 58.68,
      equity: -23.06,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 119.5,
      wage_bill: 40.65,
      wage_to_revenue_pct: 34.0,
      pre_tax_profit: -99.14,
    },
    historical: [
      { season: "2019-20", revenue: 111.94, wage_bill: 80.19, net_profit: -53.44 },
      { season: "2020-21", revenue: 102.81, wage_bill: 92.95, net_profit: -77.93 },
      { season: "2021-22", revenue: 143.91, wage_bill: 97.74, net_profit: -79.76 },
      { season: "2022-23", revenue: 119.5, wage_bill: 40.65, net_profit: -99.14 },
      { season: "2023-24", revenue: 93.85, wage_bill: 45.79, net_profit: -33.33 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "karlsruher-sc",
    name: "Karlsruher SC",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Karlsruhe",
    currency: "EUR",
    stadium: { name: "BBBank Wildpark", capacity: 34302, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 45.77,
      wage_bill: 17.83,
      wage_to_revenue_pct: 39.0,
      net_profit: -0.18,
      total_liabilities: 43.92,
      equity: 28.32,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 30.86,
      wage_bill: 16.39,
      wage_to_revenue_pct: 53.1,
      pre_tax_profit: -0.73,
    },
    historical: [
      { season: "2019-20", revenue: 21.93, wage_bill: 12.77, net_profit: -13.48 },
      { season: "2020-21", revenue: 19.58, wage_bill: 11.88, net_profit: -5.8 },
      { season: "2021-22", revenue: 27.12, wage_bill: 12.6, net_profit: 1.03 },
      { season: "2022-23", revenue: 30.86, wage_bill: 16.39, net_profit: -0.73 },
      { season: "2023-24", revenue: 45.77, wage_bill: 17.83, net_profit: -0.18 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sc-paderborn-07",
    name: "SC Paderborn 07",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Paderborn",
    currency: "EUR",
    stadium: { name: "Benteler-Arena", capacity: 15000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 33.74,
      wage_bill: 16.66,
      wage_to_revenue_pct: 49.4,
      net_profit: -1.39,
      total_liabilities: 14.0,
      equity: 6.34,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 33.58,
      wage_bill: 13.55,
      wage_to_revenue_pct: 40.4,
      pre_tax_profit: 0.02,
    },
    historical: [
      { season: "2019-20", revenue: 32.24, wage_bill: 18.51, net_profit: 5.07 },
      { season: "2020-21", revenue: 13.55, wage_bill: 13.55, net_profit: -0.57 },
      { season: "2021-22", revenue: 29.34, wage_bill: 14.47, net_profit: 4.47 },
      { season: "2022-23", revenue: 33.58, wage_bill: 13.55, net_profit: 0.02 },
      { season: "2023-24", revenue: 33.74, wage_bill: 16.66, net_profit: -1.39 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sc-preussen-muenster",
    name: "SC Preußen Münster",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Münster",
    currency: "EUR",
    stadium: { name: "Preußenstadion", capacity: 14000, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 13.01,
      wage_bill: 14.51,
      wage_to_revenue_pct: 111.5,
      net_profit: 2.17,
      total_liabilities: 17.94,
      equity: 2.76,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 6.58,
      wage_bill: 3.69,
      wage_to_revenue_pct: 56.1,
      pre_tax_profit: -1.44,
    },
    historical: [
      { season: "2022-23", revenue: 6.58, wage_bill: 3.69, net_profit: -1.44 },
      { season: "2023-24", revenue: 13.01, wage_bill: 14.51, net_profit: 2.17 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sv-07-elversberg",
    name: "SV 07 Elversberg",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Elversberg",
    currency: "EUR",
    stadium: { name: "Ursapharm-Arena", capacity: 9500, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 28.23,
      wage_bill: 12.82,
      wage_to_revenue_pct: 45.4,
      net_profit: 1.12,
      total_liabilities: 34.14,
      equity: -4.23,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 16.27,
      wage_bill: 9.97,
      wage_to_revenue_pct: 61.3,
      pre_tax_profit: -3.49,
    },
    historical: [
      { season: "2021-22", revenue: 11.95, wage_bill: 6.32, net_profit: 0.01 },
      { season: "2022-23", revenue: 16.27, wage_bill: 9.97, net_profit: -3.49 },
      { season: "2023-24", revenue: 28.23, wage_bill: 12.82, net_profit: 1.12 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "sv-darmstadt-98",
    name: "SV Darmstadt 98",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Darmstadt",
    currency: "EUR",
    stadium: { name: "Merck-Stadion", capacity: 17810, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 60.87,
      wage_bill: 28.88,
      wage_to_revenue_pct: 47.4,
      net_profit: 5.42,
      total_liabilities: 56.06,
      equity: 22.53,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 34.45,
      wage_bill: 19.48,
      wage_to_revenue_pct: 56.5,
      pre_tax_profit: -1.22,
    },
    historical: [
      { season: "2019-20", revenue: 31.05, wage_bill: 16.69, net_profit: 0.9 },
      { season: "2020-21", revenue: 29.93, wage_bill: 14.3, net_profit: 2.06 },
      { season: "2021-22", revenue: 26.51, wage_bill: 15.1, net_profit: -1.98 },
      { season: "2022-23", revenue: 34.45, wage_bill: 19.48, net_profit: -1.22 },
      { season: "2023-24", revenue: 60.87, wage_bill: 28.88, net_profit: 5.42 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "spvgg-greuther-fuerth",
    name: "SpVgg Greuther Fürth",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Fürth",
    currency: "EUR",
    stadium: { name: "Sportpark Ronhof", capacity: 16186, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 34.43,
      wage_bill: 17.43,
      wage_to_revenue_pct: 50.6,
      net_profit: -0.29,
      total_liabilities: 13.58,
      equity: 7.37,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 35.24,
      wage_bill: 9.84,
      wage_to_revenue_pct: 27.9,
      pre_tax_profit: 0.13,
    },
    historical: [
      { season: "2019-20", revenue: 22.37, wage_bill: 13.27, net_profit: -3.95 },
      { season: "2020-21", revenue: 23.48, wage_bill: 12.58, net_profit: -0.46 },
      { season: "2021-22", revenue: 48.76, wage_bill: 22.67, net_profit: 5.33 },
      { season: "2022-23", revenue: 35.24, wage_bill: 9.84, net_profit: 0.13 },
      { season: "2023-24", revenue: 34.43, wage_bill: 17.43, net_profit: -0.29 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
  {
    slug: "vfl-bochum",
    name: "VfL Bochum",
    country: "Germany",
    league: "2. Bundesliga",
    city: "Bochum",
    currency: "EUR",
    stadium: { name: "Vonovia Ruhrstadion", capacity: 27599, ownership: null },
    ownership: null,
    financials: {
      most_recent_year: "2023-24",
      revenue: 74.86,
      wage_bill: 45.1,
      wage_to_revenue_pct: 60.2,
      net_profit: -5.13,
      total_liabilities: 36.72,
      equity: 4.18,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Source: German FA/DFL club financial reporting. Values in €m (source in k€). Post-tax result used as net profit (pre-tax not available from this dataset).",
    },
    prior_year: {
      season: "2022-23",
      revenue: 84.27,
      wage_bill: 38.5,
      wage_to_revenue_pct: 45.7,
      pre_tax_profit: 8.23,
    },
    historical: [
      { season: "2019-20", revenue: 32.84, wage_bill: 17.44, net_profit: -2.92 },
      { season: "2020-21", revenue: 28.33, wage_bill: 18.7, net_profit: -4.88 },
      { season: "2021-22", revenue: 63.61, wage_bill: 31.17, net_profit: 5.99 },
      { season: "2022-23", revenue: 84.27, wage_bill: 38.5, net_profit: 8.23 },
      { season: "2023-24", revenue: 74.86, wage_bill: 45.1, net_profit: -5.13 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },
];
