// AUTO-GENERATED by populate_deep_dive_ts.py — do not edit manually.
// Re-run that script after enrich_deep_dive.py completes.

export interface RevenueBreakdown {
  matchday: number | null;
  broadcasting: number | null;
  commercial: number | null;
}

export interface OwnerLoans {
  amount: number | null;
  interest_rate: string | null;
  repayment_date: string | null;
  secured: boolean | null;
}

export interface BankDebt {
  amount: number | null;
  facility_type: string | null;
  repayment_date: string | null;
  security: string | null;
}

export interface BondDebt {
  amount: number | null;
  maturity: string | null;
}

export interface DebtProfile {
  owner_loans: OwnerLoans | null;
  bank_debt: BankDebt | null;
  transfer_payables: number | null;
  bond_debt: BondDebt | null;
  other_debt: string | null;
  total_debt_notes: string | null;
}

export interface ClubDeepDive {
  revenue_breakdown: RevenueBreakdown | null;
  debt_profile: DebtProfile | null;
}

export const deepDive: Record<string, ClubDeepDive> = {
  "arsenal": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "aston_villa": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "bournemouth": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "brentford": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "brighton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "burnley": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "chelsea": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "crystal_palace": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "everton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "fulham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "leeds": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "liverpool": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "man_city": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "man_united": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "newcastle": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "nottm_forest": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "sunderland": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "tottenham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "west_ham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "wolves": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "birmingham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "blackburn": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "bristol_city": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "charlton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "coventry": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "derby": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "hull": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "ipswich": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "leicester": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "middlesbrough": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "millwall": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "norwich": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "oxford_utd": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "portsmouth": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "preston": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "qpr": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "sheff_utd": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "sheff_wed": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "southampton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "stoke": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "swansea": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "watford": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "west_brom": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "wrexham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "afc_wimbledon": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "barnsley": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "blackpool": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "bolton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "bradford": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "burton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "cardiff": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "doncaster": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "exeter": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "huddersfield": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "leyton_orient": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "lincoln": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "luton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "mansfield": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "northampton": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "peterborough": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "plymouth": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "port_vale": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "reading": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "rotherham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "stevenage": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "stockport": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "wigan": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "wycombe": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "accrington": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "barnet": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "barrow": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "bristol_rovers": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "bromley": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "cambridge": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "cheltenham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "chesterfield": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "colchester": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "crawley": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "crewe": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "fleetwood": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "gillingham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "grimsby": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "harrogate": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "mk_dons": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "newport": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "notts_county": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "oldham": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "salford": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "shrewsbury": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "swindon": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "tranmere": {
    "revenue_breakdown": null,
    "debt_profile": null
  },
  "walsall": {
    "revenue_breakdown": null,
    "debt_profile": null
  }
};
