// Danish Superliga clubs — extracted from company annual reports
// Monetary values in EUR millions (converted from DKK at published EUR/DKK rates)
// FY2025/24 conversion: tDKK × 0.1340 / 1000 | FY2023: × 0.1342 | FY2022: × 0.1344 | FY2021: × 0.1345
// Original DKK figures (tDKK) stored in financials.data_notes for reference
// Source: Annual reports filed with the Danish Business Authority (Erhvervsstyrelsen)
import type { EUClub } from "./euClubs";

export const dkClubs: EUClub[] = [
  // ─── FC København / PARKEN ────────────────────────────────────────────────
  // Note: PARKEN Sport & Entertainment A/S group — includes FC Copenhagen
  // football plus Lalandia resort operations. FY = calendar year (Jan–Dec).
  {
    slug: "fc-kobenhavn",
    name: "FC København",
    country: "Denmark",
    league: "Superliga",
    city: "Copenhagen",
    currency: "EUR",
    stadium: { name: "Parken", capacity: 38065, ownership: "PARKEN Sport & Entertainment A/S" },
    ownership: { summary: "PARKEN Sport & Entertainment A/S (listed OMX Copenhagen)", category: "Public company; FCK is a subsidiary of PARKEN group", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 252.5,
      wage_bill: 88.3,
      wage_to_revenue_pct: 35.0,
      net_profit: 27.5,
      total_liabilities: 294.2,
      equity: 194.9,
      operating_profit: 41.1,
      pre_tax_profit: 37.5,
      net_debt: 269.1,
      data_notes: "PARKEN group (includes Lalandia resort). Original DKK (tDKK): revenue 1,884,619 | wages 658,894 | operating profit 306,600 (primært resultat 297,200 + transfer 10,400 − amortiseringer 1,000) | pre-tax profit 279,904 | equity 1,454,809 | total liabilities 2,196,052 | cash 187,555. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2024",
      revenue: 197.9,
      wage_bill: 80.5,
      wage_to_revenue_pct: 40.7,
      net_profit: 31.2,
      total_liabilities: 286.3,
      equity: null,
      operating_profit: 37.9,
      profit_from_player_sales: 22.8,
      pre_tax_profit: 41.9,
      net_debt: 270.0,
    },
    historical: [
      { season: "FY2023", revenue: 227.5, wage_bill: 78.3, net_profit: 57.8, operating_profit: 64.1, pre_tax_profit: 57.8, net_debt: 154.8 },
      { season: "FY2022", revenue: 176.6, wage_bill: 69.8, net_profit: 35.4, operating_profit: 41.5, pre_tax_profit: 35.4, net_debt: 178.8 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "LOW",
  },

  // ─── FC Midtjylland ───────────────────────────────────────────────────────
  // FY = Aug–Jul (2024/25 reported). Revenue = Bruttofortjeneste.
  {
    slug: "fc-midtjylland",
    name: "FC Midtjylland",
    country: "Denmark",
    league: "Superliga",
    city: "Herning",
    currency: "EUR",
    stadium: { name: "MCH Arena", capacity: 11203, ownership: "Club-related" },
    ownership: { summary: "Matthew Benham (Brentford owner) via Sport Investment Group", category: "FC Midtjylland A/S — private company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024/25",
      revenue: 36.3,
      wage_bill: 28.1,
      wage_to_revenue_pct: 77.4,
      net_profit: -5.3,
      total_liabilities: 46.0,
      equity: 40.6,
      operating_profit: -5.9,
      pre_tax_profit: -6.5,
      net_debt: 42.8,
      data_notes: "Original DKK (tDKK): revenue 270,722 | wages 209,602 | operating profit -44,327 | pre-tax profit -48,054 | equity 302,690 | total liabilities 343,271 | cash 23,845. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 28.6,
      wage_bill: 23.7,
      wage_to_revenue_pct: 82.9,
      net_profit: -7.5,
      total_liabilities: 53.8,
      equity: null,
      operating_profit: -11.2,
      profit_from_player_sales: null,
      pre_tax_profit: -11.6,
      net_debt: 51.7,
    },
    historical: [
      { season: "FY2022/23", revenue: 46.5, wage_bill: 19.6, net_profit: 14.7, operating_profit: 14.8, pre_tax_profit: 14.7, net_debt: -2.4 },
      { season: "FY2021/22", revenue: 33.0, wage_bill: 16.0, net_profit: 4.7, operating_profit: 4.9, pre_tax_profit: 4.7, net_debt: -19.3 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── AGF (Aarhus Gymnastikforening) ──────────────────────────────────────
  // FY = Jul–Jun (2023/24 reported)
  {
    slug: "agf",
    name: "AGF",
    country: "Denmark",
    league: "Superliga",
    city: "Aarhus",
    currency: "EUR",
    stadium: { name: "Ceres Park", capacity: 20032, ownership: "Club-owned" },
    ownership: { summary: "AGF A/S — publicly owned cooperative structure", category: "AGF A/S (sports company of the club)", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2023/24",
      revenue: 24.9,
      wage_bill: 15.7,
      wage_to_revenue_pct: 63.0,
      net_profit: 7.9,
      total_liabilities: 9.1,
      equity: 30.2,
      operating_profit: -5.5,
      pre_tax_profit: 10.2,
      net_debt: 7.1,
      data_notes: "Pre-tax profit elevated by large player-sale gains. Original DKK (tDKK): revenue 185,630 | wages 116,973 | operating profit -41,161 | pre-tax profit 75,585 | equity 225,593 | total liabilities 68,136 | cash 15,306. EUR/DKK: 0.1340 (FY2024).",
    },
    prior_year: {
      season: "FY2022/23",
      revenue: 24.2,
      wage_bill: 13.5,
      wage_to_revenue_pct: 55.7,
      net_profit: 3.0,
      total_liabilities: 6.0,
      equity: null,
      operating_profit: 1.5,
      profit_from_player_sales: null,
      pre_tax_profit: 1.9,
      net_debt: 0.5,
    },
    historical: [
      // net_profit field stores pre-tax profit (closest available equivalent)
      // net_debt = total_liabilities − cash (likvide beholdninger); consistent with FY2024 methodology
      { season: "FY2021/22", revenue: 25.4, wage_bill: 13.0, net_profit: 1.0, operating_profit: 2.6, pre_tax_profit: 1.4, net_debt: 7.7 },
      // DKK (tDKK): revenue 188,807 | wages 96,745 | op profit 19,251 | pre-tax 10,693 | net profit 7,497 | total liabilities 69,782 | cash 12,617. EUR/DKK: 0.1344 (FY2022).
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── Silkeborg IF ─────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2025); annual report filed in English
  {
    slug: "silkeborg-if",
    name: "Silkeborg IF",
    country: "Denmark",
    league: "Superliga",
    city: "Silkeborg",
    currency: "EUR",
    stadium: { name: "JYSK Park", capacity: 10000, ownership: "Club-owned" },
    ownership: { summary: "Silkeborg IF A/S — private company", category: "Professional football subsidiary", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 10.9,
      wage_bill: 6.8,
      wage_to_revenue_pct: 63.1,
      net_profit: 3.5,
      total_liabilities: 4.2,
      equity: 15.6,
      operating_profit: 4.4,
      pre_tax_profit: 4.4,
      net_debt: 1.5,
      data_notes: "Original DKK (tDKK): revenue 81,013 | wages 51,095 | operating profit 33,126 | pre-tax profit 33,108 | equity 116,715 | total liabilities 31,464 | cash 20,064. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2024",
      revenue: 12.7,
      wage_bill: 6.4,
      wage_to_revenue_pct: 50.0,
      net_profit: 6.6,
      total_liabilities: 6.9,
      equity: 14.1,
      operating_profit: 8.2,
      profit_from_player_sales: null,
      pre_tax_profit: 8.4,
      net_debt: 4.1,
    },
    historical: [
      { season: "FY2023", revenue: 9.6, wage_bill: 5.9, net_profit: 3.7, operating_profit: 3.4, pre_tax_profit: 3.7, net_debt: -6.8 },
      { season: "FY2022", revenue: 15.2, wage_bill: 6.1, net_profit: 9.5, operating_profit: 9.5, pre_tax_profit: 9.5, net_debt: -4.5 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "LOW",
  },

  // ─── FC Nordsjælland ──────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024); Right to Dream academy model
  // Revenue = Bruttofortjeneste (includes significant player sales proceeds)
  {
    slug: "fc-nordsjaelland",
    name: "FC Nordsjælland",
    country: "Denmark",
    league: "Superliga",
    city: "Farum",
    currency: "EUR",
    stadium: { name: "Right to Dream Park", capacity: 10300, ownership: "Club-owned" },
    ownership: { summary: "Right to Dream Group (Tom Vernon) — integrated academy/club model", category: "FC Nordsjælland A/S — private company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 49.1,
      wage_bill: 4.3,
      wage_to_revenue_pct: 8.7,
      net_profit: null,
      total_liabilities: 28.6,
      equity: 31.9,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: 26.2,
      data_notes: "Revenue includes player sales proceeds (academy model). Wage ratio unusually low due to player-trading revenue base. Original DKK (tDKK): total revenue 366,004 | wages 31,778 | equity 238,150 | total liabilities 213,149 | cash 16,943. EUR/DKK: 0.1340 (FY2024).",
    },
    prior_year: {
      season: "FY2023",
      revenue: 39.2,
      wage_bill: 23.9,
      wage_to_revenue_pct: 61.0,
      net_profit: 8.2,
      total_liabilities: 27.7,
      equity: 17.0,
      operating_profit: 11.0,
      profit_from_player_sales: null,
      pre_tax_profit: 10.5,
      net_debt: 16.3,
    },
    historical: [
      { season: "FY2022", revenue: 8.5, wage_bill: 14.5, net_profit: -7.8, operating_profit: -8.1, pre_tax_profit: -7.8, net_debt: 3.0 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "PARTIAL",
    volatility_tier: "HIGH",
  },

  // ─── Randers FC ───────────────────────────────────────────────────────────
  // FY = Jul–Jun (2024/25); Randers FC Holding A/S (consolidated group)
  {
    slug: "randers-fc",
    name: "Randers FC",
    country: "Denmark",
    league: "Superliga",
    city: "Randers",
    currency: "EUR",
    stadium: { name: "Cepheus Park Randers", capacity: 12700, ownership: "Club-related" },
    ownership: { summary: "Randers FC Holding A/S — private company", category: "Holding company owning football + ancillary businesses", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024/25",
      revenue: 13.5,
      wage_bill: 10.4,
      wage_to_revenue_pct: 77.2,
      net_profit: 0.7,
      total_liabilities: 6.4,
      equity: 8.9,
      operating_profit: 1.0,
      pre_tax_profit: 1.0,
      net_debt: 2.8,
      data_notes: "Group (consolidated) figures. Original DKK (tDKK): revenue 100,720 | wages 77,735 | operating profit 7,930 | pre-tax profit 7,791 | equity 66,114 | total liabilities 47,517 | cash 26,277. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: null,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── Viborg FF ────────────────────────────────────────────────────────────
  // FY = Jul–Jun (2024/25); Viborg F.F. Prof. Fodbold A/S
  {
    slug: "viborg-ff",
    name: "Viborg FF",
    country: "Denmark",
    league: "Superliga",
    city: "Viborg",
    currency: "EUR",
    stadium: { name: "Energi Viborg Arena", capacity: 10000, ownership: "Municipal/club" },
    ownership: { summary: "Viborg F.F. Prof. Fodbold A/S — private company", category: "Professional football subsidiary of Viborg FF", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024/25",
      revenue: 10.6,
      wage_bill: 7.2,
      wage_to_revenue_pct: 68.1,
      net_profit: -1.3,
      total_liabilities: 3.5,
      equity: 13.2,
      operating_profit: -1.8,
      pre_tax_profit: -1.7,
      net_debt: -1.1,
      data_notes: "Net cash position (negative net debt). Original DKK (tDKK): revenue 79,330 | wages 54,042 | operating profit -13,199 | pre-tax profit -12,394 | equity 98,653 | total liabilities 26,058 | cash 34,651. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 10.3,
      wage_bill: 7.1,
      wage_to_revenue_pct: 68.6,
      net_profit: 3.1,
      total_liabilities: 4.0,
      equity: 14.7,
      operating_profit: 3.7,
      profit_from_player_sales: null,
      pre_tax_profit: 3.9,
      net_debt: -0.1,
    },
    historical: [
      { season: "FY2022/23", revenue: 11.6, wage_bill: 5.7, net_profit: 4.5, operating_profit: 4.5, pre_tax_profit: 4.5, net_debt: -5.0 },
      { season: "FY2021/22", revenue: 7.6, wage_bill: 4.3, net_profit: 0.9, operating_profit: 0.9, pre_tax_profit: 0.9, net_debt: -6.7 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── AaB (Aalborg Boldspilklub) ───────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2025); club was relegated from Superliga in 2025
  {
    slug: "aab",
    name: "AaB",
    country: "Denmark",
    league: "1. Division",
    city: "Aalborg",
    currency: "EUR",
    stadium: { name: "Aalborg Portland Park", capacity: 13800, ownership: "Club-owned" },
    ownership: { summary: "Aalborg Boldspilklub A/S — private company", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 9.9,
      wage_bill: 9.6,
      wage_to_revenue_pct: 97.1,
      net_profit: 0.8,
      total_liabilities: 8.0,
      equity: 8.4,
      operating_profit: 0.9,
      pre_tax_profit: 0.8,
      net_debt: 7.9,
      data_notes: "Club relegated from Superliga in 2025. Wage ratio elevated as revenue excludes separately reported transfer income. Original DKK (tDKK): revenue 73,785 | wages 71,649 | operating profit 7,046 | pre-tax profit 6,023 | equity 62,743 | total liabilities 59,398 | cash 983. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2024",
      revenue: 10.2,
      wage_bill: 8.6,
      wage_to_revenue_pct: 84.3,
      net_profit: -6.0,
      total_liabilities: 8.3,
      equity: 7.7,
      operating_profit: -5.9,
      profit_from_player_sales: -0.7,
      pre_tax_profit: -6.0,
      net_debt: 1.3,
    },
    historical: [
      { season: "FY2023", revenue: 11.0, wage_bill: 9.0, net_profit: -4.6, operating_profit: -4.5, pre_tax_profit: -4.6, net_debt: -1.1 },
      { season: "FY2022", revenue: 11.4, wage_bill: 9.2, net_profit: -2.1, operating_profit: -1.8, pre_tax_profit: -2.1, net_debt: 2.0 },
      { season: "FY2021", revenue: 8.6, wage_bill: 8.1, net_profit: -2.1, operating_profit: -2.1, pre_tax_profit: -2.1, net_debt: -5.1 },
      { season: "FY2020", revenue: 5.9, wage_bill: 7.8, net_profit: 1.6, operating_profit: 1.6, pre_tax_profit: 1.6, net_debt: -5.6 },
      { season: "FY2019", revenue: 8.1, wage_bill: 7.4, net_profit: -4.5, operating_profit: -4.7, pre_tax_profit: -4.5, net_debt: -0.9 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── Lyngby BK ────────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024)
  {
    slug: "lyngby-bk",
    name: "Lyngby BK",
    country: "Denmark",
    league: "Superliga",
    city: "Lyngby",
    currency: "EUR",
    stadium: { name: "Lyngby Stadion", capacity: 10000, ownership: "Club-related" },
    ownership: { summary: "Lyngby Boldklub A/S — private company; supported by parent organisation", category: "Professional football subsidiary", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 7.2,
      wage_bill: 6.5,
      wage_to_revenue_pct: 90.5,
      net_profit: 0.3,
      total_liabilities: 6.0,
      equity: 1.8,
      operating_profit: 0.3,
      pre_tax_profit: 0.3,
      net_debt: 4.7,
      data_notes: "Revenue = Bruttofortjeneste (gross profit used per club's presentation). Parent has committed financing through June 2026. Original DKK (tDKK): revenue 53,628 | wages 48,531 | operating profit 2,378 | pre-tax profit 1,840 | equity 13,142 | total liabilities 44,973 | cash 10,128. EUR/DKK: 0.1340 (FY2024).",
    },
    prior_year: {
      season: "FY2023",
      revenue: 6.3,
      wage_bill: 5.7,
      wage_to_revenue_pct: 90.5,
      net_profit: 0.1,
      total_liabilities: 7.7,
      equity: -5.0,
      operating_profit: 0.2,
      profit_from_player_sales: null,
      pre_tax_profit: 0.1,
      net_debt: 7.7,
    },
    historical: [
      { season: "FY2022", revenue: 3.1, wage_bill: 4.7, net_profit: -2.0, operating_profit: -1.9, pre_tax_profit: -2.0, net_debt: 6.5 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── SønderjyskE ─────────────────────────────────────────────────────────
  // FY = Oct–Sep (2023/24 reported)
  {
    slug: "sonderjyske",
    name: "SønderjyskE",
    country: "Denmark",
    league: "Superliga",
    city: "Haderslev",
    currency: "EUR",
    stadium: { name: "Sydbank Park", capacity: 10000, ownership: "Club-related" },
    ownership: { summary: "SønderjyskE Fodbold A/S — private company", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2023/24",
      revenue: 5.0,
      wage_bill: 5.5,
      wage_to_revenue_pct: 109.6,
      net_profit: -0.6,
      total_liabilities: 4.3,
      equity: 2.1,
      operating_profit: -0.7,
      pre_tax_profit: -0.8,
      net_debt: 4.2,
      data_notes: "Wage bill exceeds revenue (wages 109% of revenue) — club relies on intercompany financing. Original DKK (tDKK): revenue 37,431 | wages 41,017 | operating profit -5,654 | pre-tax profit -6,500 | equity 15,786 | total liabilities 32,738 | cash 1,707. EUR/DKK: 0.1340 (FY2024).",
    },
    prior_year: {
      season: "FY2022/23",
      revenue: 5.6,
      wage_bill: 7.2,
      wage_to_revenue_pct: 128.6,
      net_profit: -1.5,
      total_liabilities: 3.9,
      equity: 0.4,
      operating_profit: -1.9,
      profit_from_player_sales: null,
      pre_tax_profit: -2.0,
      net_debt: 3.6,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── AC Horsens ───────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2025); serious financial distress
  {
    slug: "ac-horsens",
    name: "AC Horsens",
    country: "Denmark",
    league: "1. Division",
    city: "Horsens",
    currency: "EUR",
    stadium: { name: "Casa Arena Horsens", capacity: 10400, ownership: "Municipal" },
    ownership: { summary: "Fodboldalliancen AC Horsens A/S — private company; financed by parent/group", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 3.3,
      wage_bill: 7.8,
      wage_to_revenue_pct: 239.0,
      net_profit: -10.5,
      total_liabilities: 26.3,
      equity: -14.7,
      operating_profit: -10.7,
      pre_tax_profit: -10.5,
      net_debt: 25.6,
      data_notes: "Negative equity; club technically insolvent, funded by large intercompany loans. Wage bill is 239% of revenues. Original DKK (tDKK): revenue 24,281 | wages 58,039 | operating profit -80,022 | pre-tax profit -78,459 | equity -109,524 | total liabilities 196,840 | total assets 87,316. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2024",
      revenue: 3.1,
      wage_bill: 7.6,
      wage_to_revenue_pct: 242.9,
      net_profit: -11.0,
      total_liabilities: 13.4,
      equity: -4.2,
      operating_profit: -10.4,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: 12.7,
    },
    historical: [
      { season: "FY2023", revenue: 5.7, wage_bill: 4.8, net_profit: 0.8, operating_profit: 0.8, pre_tax_profit: 0.8, net_debt: -4.8 },
      { season: "FY2022", revenue: 5.0, wage_bill: 4.2, net_profit: -1.1, operating_profit: -1.1, pre_tax_profit: -1.1, net_debt: null },
      { season: "FY2021", revenue: 5.2, wage_bill: null, net_profit: null, operating_profit: 0.5, pre_tax_profit: null, net_debt: null },
      { season: "FY2020", revenue: 5.3, wage_bill: null, net_profit: null, operating_profit: 0.9, pre_tax_profit: null, net_debt: null },
      { season: "FY2019", revenue: 5.9, wage_bill: null, net_profit: null, operating_profit: -0.5, pre_tax_profit: null, net_debt: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── Vejle BK (VB Alliancen) ─────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024); negative equity
  {
    slug: "vejle-bk",
    name: "Vejle BK",
    country: "Denmark",
    league: "1. Division",
    city: "Vejle",
    currency: "EUR",
    stadium: { name: "Vejle Stadion", capacity: 10000, ownership: "Club-related" },
    ownership: { summary: "VB Alliancen A/S — private company; financed by intercompany loans from group", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 6.4,
      wage_bill: 6.5,
      wage_to_revenue_pct: 102.1,
      net_profit: -0.5,
      total_liabilities: 5.3,
      equity: -2.7,
      operating_profit: -0.6,
      pre_tax_profit: -0.6,
      net_debt: 4.6,
      data_notes: "Negative equity. Revenue is estimated (Bruttofortjeneste). Original DKK (tDKK): wages 48,591 | pre-tax profit -3,975 | equity -19,936 | total liabilities 39,163 | cash 4,548 | total assets 19,227. EUR/DKK: 0.1340 (FY2024).",
    },
    prior_year: {
      season: "FY2023",
      revenue: null,
      wage_bill: 6.1,
      wage_to_revenue_pct: null,
      net_profit: -2.1,
      total_liabilities: 4.9,
      equity: -2.2,
      operating_profit: -2.2,
      profit_from_player_sales: null,
      pre_tax_profit: -2.1,
      net_debt: 4.3,
    },
    historical: [
      { season: "FY2022", revenue: 5.6, wage_bill: 6.1, net_profit: -0.9, operating_profit: -1.0, pre_tax_profit: -0.9, net_debt: -1.2 },
      { season: "FY2021", revenue: 7.8, wage_bill: 6.4, net_profit: 1.1, operating_profit: 1.0, pre_tax_profit: 1.1, net_debt: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "PARTIAL",
    volatility_tier: "HIGH",
  },

  // ─── Hvidovre IF ─────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024); small club, currently in lower divisions
  {
    slug: "hvidovre-if",
    name: "Hvidovre IF",
    country: "Denmark",
    league: "1. Division",
    city: "Hvidovre",
    currency: "EUR",
    stadium: { name: "Pro Ventilation Arena", capacity: 8000, ownership: "Club-related" },
    ownership: { summary: "Hvidovre IF — non-profit association structure", category: "Non-profit sports club", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 0.7,
      wage_bill: 0.3,
      wage_to_revenue_pct: 37.1,
      net_profit: 0.0,
      total_liabilities: 0.2,
      equity: 0.0,
      operating_profit: 0.0,
      pre_tax_profit: 0.0,
      net_debt: 0.1,
      data_notes: "Non-profit community club structure; revenue from membership fees and local sponsorships. Original DKK (tDKK): revenue 5,340 | wages 1,980 | operating result -83 | equity 180 | total assets 1,523. EUR/DKK: 0.1340 (FY2024).",
    },
    prior_year: {
      season: "FY2023",
      revenue: 0.6,
      wage_bill: 0.2,
      wage_to_revenue_pct: 28.6,
      net_profit: 0.0,
      total_liabilities: 0.2,
      equity: 0.0,
      operating_profit: 0.0,
      profit_from_player_sales: null,
      pre_tax_profit: 0.0,
      net_debt: 0.1,
    },
    historical: [
      { season: "FY2022", revenue: 0.7, wage_bill: null, net_profit: 0.0, operating_profit: 0.0, pre_tax_profit: 0.0, net_debt: -0.1 },
      { season: "FY2021", revenue: 0.6, wage_bill: null, net_profit: 0.0, operating_profit: 0.0, pre_tax_profit: 0.0, net_debt: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── Brøndby IF ──────────────────────────────────────────────────────────
  // FY = Jul–Jun (2024/25 reported). Listed on OMX Copenhagen. IFRS accounting.
  // Note: prior year 2023/24 was an 18-month transition period (Jan 2023–Jun 2024) — not directly comparable.
  {
    slug: "brondby-if",
    name: "Brøndby IF",
    country: "Denmark",
    league: "Superliga",
    city: "Brøndby",
    currency: "EUR",
    stadium: { name: "Brøndby Stadion", capacity: 29000, ownership: "Club-owned" },
    ownership: { summary: "Brøndby IF A/S (listed OMX Copenhagen); Jan Bech Andersen major shareholder", category: "Listed public company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024/25",
      revenue: 35.0,
      wage_bill: 26.2,
      wage_to_revenue_pct: 75.0,
      net_profit: -17.5,
      total_liabilities: 38.8,
      equity: 26.0,
      operating_profit: -16.0,
      pre_tax_profit: -17.5,
      net_debt: 20.1,
      data_notes: "IFRS reporting. Transfer result -38,855 tDKK included above operating line. Original DKK (tDKK): revenue 261,208 | wages 195,941 | pre-tax profit -130,578 | equity 194,496 | total liabilities 289,387 | cash 139,335. EUR/DKK: 0.1340 (FY2025).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 46.4,
      wage_bill: 33.4,
      wage_to_revenue_pct: 71.9,
      net_profit: -14.1,
      total_liabilities: 36.4,
      equity: 21.5,
      operating_profit: -12.6,
      profit_from_player_sales: 1.2,
      pre_tax_profit: -14.1,
      net_debt: 29.9,
    },
    historical: [
      { season: "FY2022", revenue: 29.7, wage_bill: 17.9, net_profit: -1.6, operating_profit: -5.9, pre_tax_profit: -1.6, net_debt: -4.3 },
      { season: "FY2021", revenue: 39.0, wage_bill: null, net_profit: 11.2, operating_profit: 8.7, pre_tax_profit: 11.2, net_debt: null },
      { season: "FY2020", revenue: 15.2, wage_bill: null, net_profit: -3.5, operating_profit: null, pre_tax_profit: -3.5, net_debt: null },
      { season: "FY2019", revenue: 23.6, wage_bill: null, net_profit: -10.6, operating_profit: null, pre_tax_profit: -10.6, net_debt: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },
];
