// Danish Superliga clubs — extracted from company annual reports
// Monetary values in USD millions (converted from DKK at published FX rates)
// FY2025 conversion: tDKK × 0.000143 | FY2024 conversion: tDKK × 0.000145
// Original DKK figures (tDKK) stored in financials.data_notes for reference
// Source: Annual reports filed with the Danish Business Authority (Erhvervsstyrelsen)
import type { EUClub } from "./euClubs";

export const dkClubs: EUClub[] = [
  // ─── FC København / PARKEN ────────────────────────────────────────────────
  // Note: PARKEN Sport & Entertainment A/S group — includes FC Copenhagen
  // football plus Lalandia resort operations. FY = calendar year (Jan–Dec).
  {
    slug: "fc-kobenhavn",
    name: "FC København",
    country: "Denmark",
    league: "Superliga",
    city: "Copenhagen",
    currency: "USD",
    stadium: { name: "Parken", capacity: 38065, ownership: "PARKEN Sport & Entertainment A/S" },
    ownership: { summary: "PARKEN Sport & Entertainment A/S (listed OMX Copenhagen)", category: "Public company; FCK is a subsidiary of PARKEN group", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 269.5,
      wage_bill: 94.2,
      wage_to_revenue_pct: 35.0,
      net_profit: 29.4,
      total_liabilities: 314.0,
      equity: 208.0,
      operating_profit: null,
      pre_tax_profit: 40.0,
      net_debt: 287.2,
      data_notes: "PARKEN group (includes Lalandia resort). Original DKK (tDKK): revenue 1,884,619 | wages 658,894 | pre-tax profit 279,904 | equity 1,454,809 | total liabilities 2,196,052 | cash 187,555. FX: 0.143 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "LOW",
  },

  // ─── FC Midtjylland ───────────────────────────────────────────────────────
  // FY = Aug–Jul (2024/25 reported)
  {
    slug: "fc-midtjylland",
    name: "FC Midtjylland",
    country: "Denmark",
    league: "Superliga",
    city: "Herning",
    currency: "USD",
    stadium: { name: "MCH Arena", capacity: 11203, ownership: "Club-related" },
    ownership: { summary: "Matthew Benham (Brentford owner) via Sport Investment Group", category: "FC Midtjylland A/S — private company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024/25",
      revenue: 38.7,
      wage_bill: 30.0,
      wage_to_revenue_pct: 77.4,
      net_profit: -5.7,
      total_liabilities: 49.1,
      equity: 43.3,
      operating_profit: -6.3,
      pre_tax_profit: -6.9,
      net_debt: 45.7,
      data_notes: "Original DKK (tDKK): revenue 270,722 | wages 209,602 | operating profit -44,327 | pre-tax profit -48,054 | equity 302,690 | total liabilities 343,271 | cash 23,845. FX: 0.143 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── AGF (Aarhus Gymnastikforening) ──────────────────────────────────────
  // FY = Jul–Jun (2023/24 reported)
  {
    slug: "agf",
    name: "AGF",
    country: "Denmark",
    league: "Superliga",
    city: "Aarhus",
    currency: "USD",
    stadium: { name: "Ceres Park", capacity: 20032, ownership: "Club-owned" },
    ownership: { summary: "AGF A/S — publicly owned cooperative structure", category: "AGF A/S (sports company of the club)", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2023/24",
      revenue: 26.9,
      wage_bill: 17.0,
      wage_to_revenue_pct: 63.0,
      net_profit: 8.6,
      total_liabilities: 9.9,
      equity: 32.7,
      operating_profit: -6.0,
      pre_tax_profit: 11.0,
      net_debt: 7.7,
      data_notes: "Pre-tax profit elevated by large player-sale gains. Original DKK (tDKK): revenue 185,630 | wages 116,973 | operating profit -41,161 | pre-tax profit 75,585 | equity 225,593 | total liabilities 68,136 | cash 15,306. FX: 0.145 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── Silkeborg IF ─────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2025); annual report filed in English
  {
    slug: "silkeborg-if",
    name: "Silkeborg IF",
    country: "Denmark",
    league: "Superliga",
    city: "Silkeborg",
    currency: "USD",
    stadium: { name: "JYSK Park", capacity: 10000, ownership: "Club-owned" },
    ownership: { summary: "Silkeborg IF A/S — private company", category: "Professional football subsidiary", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 11.6,
      wage_bill: 7.3,
      wage_to_revenue_pct: 63.1,
      net_profit: 3.7,
      total_liabilities: 4.5,
      equity: 16.7,
      operating_profit: 4.7,
      pre_tax_profit: 4.7,
      net_debt: 1.6,
      data_notes: "Original DKK (tDKK): revenue 81,013 | wages 51,095 | operating profit 33,126 | pre-tax profit 33,108 | equity 116,715 | total liabilities 31,464 | cash 20,064. FX: 0.143 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "LOW",
  },

  // ─── FC Nordsjælland ──────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024); Right to Dream academy model
  // Revenue includes significant player sales proceeds
  {
    slug: "fc-nordsjaelland",
    name: "FC Nordsjælland",
    country: "Denmark",
    league: "Superliga",
    city: "Farum",
    currency: "USD",
    stadium: { name: "Right to Dream Park", capacity: 10300, ownership: "Club-owned" },
    ownership: { summary: "Right to Dream Group (Tom Vernon) — integrated academy/club model", category: "FC Nordsjælland A/S — private company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 53.1,
      wage_bill: 4.6,
      wage_to_revenue_pct: 8.7,
      net_profit: null,
      total_liabilities: 30.9,
      equity: 34.5,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: 28.4,
      data_notes: "Revenue includes player sales proceeds (academy model). Wage ratio unusually low due to player-trading revenue base. Original DKK (tDKK): total revenue 366,004 | wages 31,778 | equity 238,150 | total liabilities 213,149 | cash 16,943. FX: 0.145 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "PARTIAL",
    volatility_tier: "HIGH",
  },

  // ─── Randers FC ───────────────────────────────────────────────────────────
  // FY = Jul–Jun (2024/25); Randers FC Holding A/S (consolidated group)
  {
    slug: "randers-fc",
    name: "Randers FC",
    country: "Denmark",
    league: "Superliga",
    city: "Randers",
    currency: "USD",
    stadium: { name: "Cepheus Park Randers", capacity: 12700, ownership: "Club-related" },
    ownership: { summary: "Randers FC Holding A/S — private company", category: "Holding company owning football + ancillary businesses", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024/25",
      revenue: 14.4,
      wage_bill: 11.1,
      wage_to_revenue_pct: 77.2,
      net_profit: 0.8,
      total_liabilities: 6.8,
      equity: 9.5,
      operating_profit: 1.1,
      pre_tax_profit: 1.1,
      net_debt: 3.0,
      data_notes: "Group (consolidated) figures. Original DKK (tDKK): revenue 100,720 | wages 77,735 | operating profit 7,930 | pre-tax profit 7,791 | equity 66,114 | total liabilities 47,517 | cash 26,277. FX: 0.143 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── Viborg FF ────────────────────────────────────────────────────────────
  // FY = Jul–Jun (2024/25); Viborg F.F. Prof. Fodbold A/S
  {
    slug: "viborg-ff",
    name: "Viborg FF",
    country: "Denmark",
    league: "Superliga",
    city: "Viborg",
    currency: "USD",
    stadium: { name: "Energi Viborg Arena", capacity: 10000, ownership: "Municipal/club" },
    ownership: { summary: "Viborg F.F. Prof. Fodbold A/S — private company", category: "Professional football subsidiary of Viborg FF", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024/25",
      revenue: 11.3,
      wage_bill: 7.7,
      wage_to_revenue_pct: 68.1,
      net_profit: -1.4,
      total_liabilities: 3.7,
      equity: 14.1,
      operating_profit: -1.9,
      pre_tax_profit: -1.8,
      net_debt: -1.2,
      data_notes: "Net cash position (negative net debt). Original DKK (tDKK): revenue 79,330 | wages 54,042 | operating profit -13,199 | pre-tax profit -12,394 | equity 98,653 | total liabilities 26,058 | cash 34,651. FX: 0.143 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── AaB (Aalborg Boldspilklub) ───────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2025); club was relegated from Superliga in 2025
  {
    slug: "aab",
    name: "AaB",
    country: "Denmark",
    league: "1. Division",
    city: "Aalborg",
    currency: "USD",
    stadium: { name: "Aalborg Portland Park", capacity: 13800, ownership: "Club-owned" },
    ownership: { summary: "Aalborg Boldspilklub A/S — private company", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 10.6,
      wage_bill: 10.2,
      wage_to_revenue_pct: 97.1,
      net_profit: 0.9,
      total_liabilities: 8.5,
      equity: 9.0,
      operating_profit: 1.0,
      pre_tax_profit: 0.9,
      net_debt: 8.4,
      data_notes: "Club relegated from Superliga in 2025. Wage ratio elevated as revenue excludes separately reported transfer income. Original DKK (tDKK): revenue 73,785 | wages 71,649 | operating profit 7,046 | pre-tax profit 6,023 | equity 62,743 | total liabilities 59,398 | cash 983. FX: 0.143 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── Lyngby BK ────────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024)
  {
    slug: "lyngby-bk",
    name: "Lyngby BK",
    country: "Denmark",
    league: "Superliga",
    city: "Lyngby",
    currency: "USD",
    stadium: { name: "Lyngby Stadion", capacity: 10000, ownership: "Club-related" },
    ownership: { summary: "Lyngby Boldklub A/S — private company; supported by parent organisation", category: "Professional football subsidiary", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 7.8,
      wage_bill: 7.0,
      wage_to_revenue_pct: 90.5,
      net_profit: 0.3,
      total_liabilities: 6.5,
      equity: 1.9,
      operating_profit: 0.3,
      pre_tax_profit: 0.3,
      net_debt: 5.1,
      data_notes: "Revenue = Bruttofortjeneste (gross profit used per club's presentation). Parent has committed financing through June 2026. Original DKK (tDKK): revenue 53,628 | wages 48,531 | operating profit 2,378 | pre-tax profit 1,840 | equity 13,142 | total liabilities 44,973 | cash 10,128. FX: 0.145 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── SønderjyskE ─────────────────────────────────────────────────────────
  // FY = Oct–Sep (2023/24 reported)
  {
    slug: "sonderjyske",
    name: "SønderjyskE",
    country: "Denmark",
    league: "Superliga",
    city: "Haderslev",
    currency: "USD",
    stadium: { name: "Sydbank Park", capacity: 10000, ownership: "Club-related" },
    ownership: { summary: "SønderjyskE Fodbold A/S — private company", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2023/24",
      revenue: 5.4,
      wage_bill: 5.9,
      wage_to_revenue_pct: 109.6,
      net_profit: -0.7,
      total_liabilities: 4.7,
      equity: 2.3,
      operating_profit: -0.8,
      pre_tax_profit: -0.9,
      net_debt: 4.5,
      data_notes: "Wage bill exceeds revenue (wages 109% of revenue) — club relies on intercompany financing. Original DKK (tDKK): revenue 37,431 | wages 41,017 | operating profit -5,654 | pre-tax profit -6,500 | equity 15,786 | total liabilities 32,738 | cash 1,707. FX: 0.145 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── AC Horsens ───────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2025); serious financial distress
  {
    slug: "ac-horsens",
    name: "AC Horsens",
    country: "Denmark",
    league: "1. Division",
    city: "Horsens",
    currency: "USD",
    stadium: { name: "Casa Arena Horsens", capacity: 10400, ownership: "Municipal" },
    ownership: { summary: "Fodboldalliancen AC Horsens A/S — private company; financed by parent/group", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 3.5,
      wage_bill: 8.3,
      wage_to_revenue_pct: 239.0,
      net_profit: -11.2,
      total_liabilities: 28.1,
      equity: -15.7,
      operating_profit: -11.4,
      pre_tax_profit: -11.2,
      net_debt: 27.3,
      data_notes: "Negative equity; club technically insolvent, funded by large intercompany loans. Wage bill is 239% of revenues. Original DKK (tDKK): revenue 24,281 | wages 58,039 | operating profit -80,022 | pre-tax profit -78,459 | equity -109,524 | total liabilities 196,840 | total assets 87,316. FX: 0.143 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── Vejle BK (VB Alliancen) ─────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024); negative equity
  {
    slug: "vejle-bk",
    name: "Vejle BK",
    country: "Denmark",
    league: "1. Division",
    city: "Vejle",
    currency: "USD",
    stadium: { name: "Vejle Stadion", capacity: 10000, ownership: "Club-related" },
    ownership: { summary: "VB Alliancen A/S — private company; financed by intercompany loans from group", category: "Professional football company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 6.9,
      wage_bill: 7.0,
      wage_to_revenue_pct: 102.1,
      net_profit: -0.5,
      total_liabilities: 5.7,
      equity: -2.9,
      operating_profit: -0.6,
      pre_tax_profit: -0.6,
      net_debt: 5.0,
      data_notes: "Negative equity. Revenue is estimated (Bruttofortjeneste). Original DKK (tDKK): wages 48,591 | pre-tax profit -3,975 | equity -19,936 | total liabilities 39,163 | cash 4,548 | total assets 19,227. FX: 0.145 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "PARTIAL",
    volatility_tier: "HIGH",
  },

  // ─── Hvidovre IF ─────────────────────────────────────────────────────────
  // FY = calendar year (Jan–Dec 2024); small club, currently in lower divisions
  {
    slug: "hvidovre-if",
    name: "Hvidovre IF",
    country: "Denmark",
    league: "1. Division",
    city: "Hvidovre",
    currency: "USD",
    stadium: { name: "Pro Ventilation Arena", capacity: 8000, ownership: "Club-related" },
    ownership: { summary: "Hvidovre IF — non-profit association structure", category: "Non-profit sports club", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 0.8,
      wage_bill: 0.3,
      wage_to_revenue_pct: 37.1,
      net_profit: 0.0,
      total_liabilities: 0.2,
      equity: 0.0,
      operating_profit: 0.0,
      pre_tax_profit: 0.0,
      net_debt: 0.1,
      data_notes: "Non-profit community club structure; revenue from membership fees and local sponsorships. Original DKK (tDKK): revenue 5,340 | wages 1,980 | operating result -83 | equity 180 | total assets 1,523. FX: 0.145 USD/DKK.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── Brøndby IF ──────────────────────────────────────────────────────────
  // NOTE: Annual report PDF could not be machine-extracted (scanned/encoded).
  // Data will be added when machine-readable report becomes available.
  {
    slug: "brondby-if",
    name: "Brøndby IF",
    country: "Denmark",
    league: "Superliga",
    city: "Brøndby",
    currency: "USD",
    stadium: { name: "Brøndby Stadion", capacity: 29000, ownership: "Club-owned" },
    ownership: { summary: "Brøndby IF A/S (listed OMX Copenhagen); Jan Bech Andersen major shareholder", category: "Listed public company", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      pre_tax_profit: null,
      net_debt: null,
      data_notes: "Annual report PDF could not be machine-extracted (appears to be scanned). Financial data unavailable at this time.",
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "NO_DATA",
    volatility_tier: null,
  },
];
