// Spanish La Liga / La Liga 2 clubs — values in EUR millions
// Source: Cuentas anuales (annual accounts) filed at Registro Mercantil / CNMV / club publications
// FY runs 1 July → 30 June (football season year). FY2024/25 = year ended 30 June 2025.
// Revenue = Importe neto de la cifra de negocios (net business turnover); includes player sale gains
// Wages  = Gastos de personal (total: sueldos + cargas sociales)
// Operating profit (EBIT) = Resultado de explotación (includes gains on player registrations)
// Pre-tax = Resultado antes de impuestos
// Net profit = Resultado del ejercicio
// Net debt = bank/credit institution debt + formal loans (incl. participatory loans) + owner/group loans
//            − cash & equivalents. EXCLUDES Deudas con entidades deportivas (transfer payables to clubs).
// net_debt < 0 = net cash position
// Entity types: SAD = Sociedad Anónima Deportiva (for-profit); Asociación = non-profit membership club
// (Real Madrid, Barcelona, Athletic Club are asociaciones; all others are SAD unless noted)

import { EUClub } from "./euClubs";

export const esClubs: EUClub[] = [

  // ══════════════════════════════════════════════════════
  // LA LIGA
  // ══════════════════════════════════════════════════════

  // ─── Real Madrid ───────────────────────────────────────────────────────────────
  {
    slug: "real-madrid",
    name: "Real Madrid",
    country: "Spain",
    league: "La Liga",
    city: "Madrid",
    currency: "EUR",
    stadium: { name: "Estadio Santiago Bernabéu", capacity: 81044, ownership: "Club-owned; major renovation 2019–2023 (€1.17bn project financing)" },
    ownership: { summary: "Member-owned (asociación); ~90,000 socios (members)", category: "Real Madrid Club de Fútbol (Asociación)", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 1185.0,
      wage_bill: 510.0,
      wage_to_revenue_pct: 43.0,
      net_profit: 24.0,
      total_liabilities: null,
      equity: 598.0,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: 32.0,
      net_debt: 12.0,
      data_notes: "Consolidated accounts. Net debt €12m excludes ~€1,170m stadium renovation project financing (ring-fenced). Wage bill estimated from wage-ratio disclosure.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 1043.6,
      wage_bill: 505.0,
      wage_to_revenue_pct: 48.4,
      net_profit: 15.6,
      operating_profit: 21.9,
      profit_from_player_sales: 12.7,
      pre_tax_profit: 19.9,
      net_debt: -131.2,
    },
    historical: [
      { season: "FY2024/25", revenue: 1185.0, wage_bill: 510.0, net_profit: 24.0 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── FC Barcelona ──────────────────────────────────────────────────────────────
  {
    slug: "fc-barcelona",
    name: "FC Barcelona",
    country: "Spain",
    league: "La Liga",
    city: "Barcelona",
    currency: "EUR",
    stadium: { name: "Estadi Olímpic Lluís Companys (temp.) / Camp Nou (renovation)", capacity: 55926, ownership: "Club-owned; Camp Nou renovation ongoing" },
    ownership: { summary: "Member-owned (asociación); ~140,000 socios (members). President: Joan Laporta.", category: "Futbol Club Barcelona (Asociació Esportiva)", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 964.2,
      wage_bill: 510.0,
      wage_to_revenue_pct: 52.9,
      net_profit: -16.9,
      total_liabilities: null,
      equity: -152.7,
      operating_profit: 71.3,
      profit_from_player_sales: null,
      pre_tax_profit: -8.4,
      net_debt: 469.0,
      data_notes: "Consolidated accounts (filed in €'000s). Going concern emphasis paragraph. Negative equity -€152.7m. Club has secured LaLiga 'palancas' (leverages) to address liquidity. Revenue includes player sale gains.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 748.3,
      wage_bill: 473.8,
      wage_to_revenue_pct: 63.3,
      net_profit: -180.3,
      operating_profit: -104.6,
      profit_from_player_sales: 70.5,
      pre_tax_profit: -204.5,
      net_debt: 561.2,
    },
    historical: [
      { season: "FY2024/25", revenue: 964.2, wage_bill: 510.0, net_profit: -16.9 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Atlético de Madrid ────────────────────────────────────────────────────────
  {
    slug: "atletico-madrid",
    name: "Atlético de Madrid",
    country: "Spain",
    league: "La Liga",
    city: "Madrid",
    currency: "EUR",
    stadium: { name: "Estadio Cívitas Metropolitano", capacity: 68456, ownership: "Club-owned" },
    ownership: { summary: "Idan Ofer (majority shareholder ~74%)", category: "Club Atlético de Madrid SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 416.1,
      wage_bill: 279.9,
      wage_to_revenue_pct: 67.3,
      net_profit: -6.0,
      total_liabilities: null,
      equity: 174.7,
      operating_profit: 17.9,
      profit_from_player_sales: null,
      pre_tax_profit: -5.9,
      net_debt: 537.0,
      data_notes: "Net debt includes ~€570m 'otros pasivos financieros' LT (stadium/infrastructure financing) plus bank credit, less cash. Standalone (no group consolidation).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 395.1,
      wage_bill: 267.7,
      wage_to_revenue_pct: 67.7,
      net_profit: 0.7,
      operating_profit: 22.4,
      profit_from_player_sales: 27.3,
      pre_tax_profit: 1.0,
      net_debt: 556.8,
    },
    historical: [
      { season: "FY2024/25", revenue: 416.1, wage_bill: 279.9, net_profit: -6.0 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Athletic Club ─────────────────────────────────────────────────────────────
  {
    slug: "athletic-club",
    name: "Athletic Club",
    country: "Spain",
    league: "La Liga",
    city: "Bilbao",
    currency: "EUR",
    stadium: { name: "San Mamés", capacity: 53289, ownership: "Club-owned" },
    ownership: { summary: "Member-owned (asociación); baserritarras (Basque Country-only player policy)", category: "Athletic Club (Asociación)", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 166.4,
      wage_bill: 122.1,
      wage_to_revenue_pct: 73.4,
      net_profit: 7.0,
      total_liabilities: null,
      equity: 112.8,
      operating_profit: 8.2,
      profit_from_player_sales: null,
      pre_tax_profit: 7.7,
      net_debt: -45.8,
      data_notes: "Net cash position (no material bank debt; strong cash reserves). Non-profit asociación — no corporate tax obligation. Clean audit opinion.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 124.5,
      wage_bill: 112.8,
      wage_to_revenue_pct: 90.6,
      net_profit: 0.0,
      operating_profit: 0.4,
      profit_from_player_sales: 6.6,
      pre_tax_profit: 0.0,
      net_debt: -22.1,
    },
    historical: [
      { season: "FY2024/25", revenue: 166.4, wage_bill: 122.1, net_profit: 7.0 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Real Sociedad ─────────────────────────────────────────────────────────────
  {
    slug: "real-sociedad",
    name: "Real Sociedad",
    country: "Spain",
    league: "La Liga",
    city: "San Sebastián",
    currency: "EUR",
    stadium: { name: "Reale Arena", capacity: 39500, ownership: "Club-owned" },
    ownership: { summary: "Privately held SAD; Jokin Aperribay (President). Part of Red & White Holdings group (same as Arsenal).", category: "Real Sociedad de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 126.5,
      wage_bill: 97.6,
      wage_to_revenue_pct: 77.1,
      net_profit: 17.0,
      total_liabilities: null,
      equity: 92.7,
      operating_profit: 16.7,
      profit_from_player_sales: null,
      pre_tax_profit: 15.5,
      net_debt: 146.6,
      data_notes: "Clean audit opinion (Deloitte). Key audit matter: cash management investments. Net debt includes CVC LaLiga participatory loan and stadium financing.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 160.5,
      wage_bill: 103.7,
      wage_to_revenue_pct: 64.6,
      net_profit: 1.2,
      operating_profit: 2.9,
      profit_from_player_sales: 6.9,
      pre_tax_profit: 1.2,
      net_debt: 117.1,
    },
    historical: [
      { season: "FY2024/25", revenue: 126.5, wage_bill: 97.6, net_profit: 17.0 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Real Betis ────────────────────────────────────────────────────────────────
  {
    slug: "real-betis",
    name: "Real Betis",
    country: "Spain",
    league: "La Liga",
    city: "Seville",
    currency: "EUR",
    stadium: { name: "Estadio Benito Villamarín", capacity: 60721, ownership: "Club-owned" },
    ownership: { summary: "Majority-owned by Ángel Haro and José Miguel López Catalán; publicly traded on BME (MCE: RBB)", category: "Real Betis Balompié SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 150.6,
      wage_bill: 102.7,
      wage_to_revenue_pct: 68.2,
      net_profit: 4.6,
      total_liabilities: null,
      equity: -39.9,
      operating_profit: 15.0,
      profit_from_player_sales: null,
      pre_tax_profit: 5.6,
      net_debt: 215.3,
      data_notes: "Qualified audit opinion (DTA €5.9m not recognised). Going concern emphasis paragraph: negative equity -€39.9m; management consider mitigated by contract extensions and revenue pipeline. Net debt includes CVC participatory loan.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 138.6,
      wage_bill: 106.9,
      wage_to_revenue_pct: 77.1,
      operating_profit: 12.1,
      profit_from_player_sales: 45.5,
      pre_tax_profit: 0.3,
      net_debt: 93.7,
    },
    historical: [
      { season: "FY2024/25", revenue: 150.6, wage_bill: 102.7, net_profit: 4.6 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Sevilla FC ────────────────────────────────────────────────────────────────
  {
    slug: "sevilla-fc",
    name: "Sevilla FC",
    country: "Spain",
    league: "La Liga",
    city: "Seville",
    currency: "EUR",
    stadium: { name: "Estadio Ramón Sánchez-Pizjuán", capacity: 43883, ownership: "Club-owned" },
    ownership: { summary: "Del Nido family (significant stake). Publicly listed on BME.", category: "Sevilla Fútbol Club SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 115.2,
      wage_bill: 114.0,
      wage_to_revenue_pct: 98.9,
      net_profit: -54.1,
      total_liabilities: null,
      equity: -122.8,
      operating_profit: -49.3,
      profit_from_player_sales: null,
      pre_tax_profit: -54.1,
      net_debt: 199.2,
      data_notes: "Emphasis of matter paragraph (auditor): negative equity -€122.8m but participatory loans treated as equity under Spanish law, avoiding mandatory dissolution. Deep operational losses with wage bill near parity with revenue. Net debt includes participatory loans.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 175.0,
      wage_bill: 159.1,
      wage_to_revenue_pct: 90.9,
      net_profit: -81.7,
      operating_profit: -75.6,
      profit_from_player_sales: 5.3,
      pre_tax_profit: -81.7,
      net_debt: 84.6,
    },
    historical: [
      { season: "FY2024/25", revenue: 115.2, wage_bill: 114.0, net_profit: -54.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Girona FC ─────────────────────────────────────────────────────────────────
  {
    slug: "girona-fc",
    name: "Girona FC",
    country: "Spain",
    league: "La Liga",
    city: "Girona",
    currency: "EUR",
    stadium: { name: "Estadi Montilivi", capacity: 13450, ownership: "Club-owned; expansion plans under review" },
    ownership: { summary: "City Football Group (majority owner); Girona FC Supporters Trust (minority)", category: "Girona Fútbol Club SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 110.9,
      wage_bill: 76.6,
      wage_to_revenue_pct: 69.1,
      net_profit: 16.5,
      total_liabilities: null,
      equity: 39.1,
      operating_profit: 23.0,
      profit_from_player_sales: null,
      pre_tax_profit: 22.0,
      net_debt: 20.1,
      data_notes: "City Football Group subsidiary. Clean audit opinion. Strong profitability driven by UEFA Champions League participation (FY2024/25) and player trading gains.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 69.9,
      wage_bill: 49.0,
      wage_to_revenue_pct: 70.1,
      net_profit: 3.0,
      operating_profit: 5.0,
      profit_from_player_sales: 2.9,
      pre_tax_profit: 4.0,
      net_debt: 4.4,
    },
    historical: [
      { season: "FY2024/25", revenue: 110.9, wage_bill: 76.6, net_profit: 16.5 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── RCD Mallorca ──────────────────────────────────────────────────────────────
  {
    slug: "rcd-mallorca",
    name: "RCD Mallorca",
    country: "Spain",
    league: "La Liga",
    city: "Palma",
    currency: "EUR",
    stadium: { name: "Estadi de Son Moix", capacity: 23142, ownership: "Rented from Palma City Council" },
    ownership: { summary: "Robert Sarver (majority owner, via Mallorca Acquisition S.L.) sold to a consortium in 2023; Andy Kohlberg (chairman) holds significant stake.", category: "Real Club Deportivo Mallorca SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 72.6,
      wage_bill: 53.5,
      wage_to_revenue_pct: 73.7,
      net_profit: -10.0,
      total_liabilities: null,
      equity: 30.7,
      operating_profit: -8.7,
      profit_from_player_sales: null,
      pre_tax_profit: -9.9,
      net_debt: 35.5,
      data_notes: "Clean audit opinion. Operating loss driven by high wages relative to revenue; modest player trading income. Net debt includes CVC participatory loan component.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 71.2,
      wage_bill: 47.7,
      wage_to_revenue_pct: 67.0,
      operating_profit: -7.8,
      profit_from_player_sales: 2.2,
      pre_tax_profit: -8.7,
      net_debt: -1.8,
    },
    historical: [
      { season: "FY2024/25", revenue: 72.6, wage_bill: 53.5, net_profit: -10.0 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Valencia CF ───────────────────────────────────────────────────────────────
  {
    slug: "valencia-cf",
    name: "Valencia CF",
    country: "Spain",
    league: "La Liga",
    city: "Valencia",
    currency: "EUR",
    stadium: { name: "Estadio de Mestalla", capacity: 55000, ownership: "Club-owned; Nou Mestalla stadium under construction (securitisation fund)" },
    ownership: { summary: "Peter Lim (Singapore; ~82% via Meriton Holdings)", category: "Valencia Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 97.6,
      wage_bill: 83.2,
      wage_to_revenue_pct: 85.3,
      net_profit: 0.5,
      total_liabilities: null,
      equity: 18.9,
      operating_profit: 23.1,
      profit_from_player_sales: null,
      pre_tax_profit: 1.6,
      net_debt: 276.6,
      data_notes: "Emphasis of matter (EY): going concern uncertainty due to high debt burden. Accounts filed in €'000s. Net debt includes stadium securitisation fund (Nou Mestalla project financing). Major debt refinancing completed Oct 2024.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 100.2,
      wage_bill: 69.4,
      wage_to_revenue_pct: 69.3,
      net_profit: 0.2,
      operating_profit: 15.5,
      profit_from_player_sales: 16.8,
      pre_tax_profit: 2.0,
      net_debt: 120.4,
    },
    historical: [
      { season: "FY2024/25", revenue: 97.6, wage_bill: 83.2, net_profit: 0.5 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Getafe CF ─────────────────────────────────────────────────────────────────
  {
    slug: "getafe-cf",
    name: "Getafe CF",
    country: "Spain",
    league: "La Liga",
    city: "Getafe",
    currency: "EUR",
    stadium: { name: "Coliseum Alfonso Pérez", capacity: 17700, ownership: "Rented from Ayuntamiento de Getafe; large subvenciones received for stadium/training ground right-of-use" },
    ownership: { summary: "Ángel Torres (President, significant shareholder)", category: "Getafe Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 58.0,
      wage_bill: 43.0,
      wage_to_revenue_pct: 74.1,
      net_profit: -1.7,
      total_liabilities: null,
      equity: 11.6,
      operating_profit: 4.2,
      profit_from_player_sales: null,
      pre_tax_profit: -0.9,
      net_debt: 63.3,
      data_notes: "Revenue includes €34.3m subvenciones (municipal grants) for stadium/training ground right-of-use obligations. Underlying commercial revenue materially lower. Clean audit opinion.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 60.5,
      wage_bill: 51.0,
      wage_to_revenue_pct: 84.3,
      operating_profit: -7.4,
      profit_from_player_sales: 16.6,
      pre_tax_profit: -10.4,
      net_debt: 21.3,
    },
    historical: [
      { season: "FY2024/25", revenue: 58.0, wage_bill: 43.0, net_profit: -1.7 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Deportivo Alavés ──────────────────────────────────────────────────────────
  {
    slug: "deportivo-alaves",
    name: "Deportivo Alavés",
    country: "Spain",
    league: "La Liga",
    city: "Vitoria-Gasteiz",
    currency: "EUR",
    stadium: { name: "Estadio de Mendizorrotza", capacity: 19840, ownership: "Club-owned" },
    ownership: { summary: "Kiroletako Bazkideak S.L. (majority); ultimate parent Lazkaokoa S.L. (both Vitoria-based)", category: "Deportivo Alavés SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 61.1,
      wage_bill: 42.2,
      wage_to_revenue_pct: 69.1,
      net_profit: 0.2,
      total_liabilities: null,
      equity: 8.2,
      operating_profit: 3.0,
      profit_from_player_sales: null,
      pre_tax_profit: -0.9,
      net_debt: 25.0,
      data_notes: "Complex group structure: Alaves SAD (parent) has ~€94m invested in subsidiaries, funded by external bank debt ~€24m LT and inter-group financing. Net debt shown is external financial debt only. Negative working capital -€35.5m; going concern risk noted by auditor (Sayma) but considered mitigated by La Liga TV rights.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 58.7,
      wage_bill: 34.5,
      wage_to_revenue_pct: 58.8,
      net_profit: 2.6,
      operating_profit: 5.6,
      profit_from_player_sales: 4.9,
      pre_tax_profit: 2.6,
      net_debt: 8.8,
    },
    historical: [
      { season: "FY2024/25", revenue: 61.1, wage_bill: 42.2, net_profit: 0.2 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Rayo Vallecano ────────────────────────────────────────────────────────────
  {
    slug: "rayo-vallecano",
    name: "Rayo Vallecano",
    country: "Spain",
    league: "La Liga",
    city: "Madrid",
    currency: "EUR",
    stadium: { name: "Estadio de Vallecas", capacity: 14708, ownership: "Rented from Madrid City Council under right-of-use arrangement (subject to audit qualification)" },
    ownership: { summary: "Raúl Martín Presa (majority shareholder/President)", category: "Rayo Vallecano de Madrid SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 56.0,
      wage_bill: 35.3,
      wage_to_revenue_pct: 63.1,
      net_profit: 1.5,
      total_liabilities: null,
      equity: 39.3,
      operating_profit: 1.5,
      profit_from_player_sales: null,
      pre_tax_profit: 1.5,
      net_debt: -38.5,
      data_notes: "Qualified audit opinion: stadium right-of-use (€15.2m) not recognised in accounts. Emphasis of matter: tax provisions €29.8m from historical tax disputes under convenio de acreedores (creditor arrangement). Net cash position: cash exceeds all formal financial debt.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 55.3,
      wage_bill: 34.8,
      wage_to_revenue_pct: 62.9,
      net_profit: 4.0,
      operating_profit: 5.0,
      profit_from_player_sales: 4.8,
      pre_tax_profit: 5.0,
      net_debt: -39.7,
    },
    historical: [
      { season: "FY2024/25", revenue: 56.0, wage_bill: 35.3, net_profit: 1.5 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── RCD Espanyol ──────────────────────────────────────────────────────────────
  {
    slug: "rcd-espanyol",
    name: "RCD Espanyol",
    country: "Spain",
    league: "La Liga",
    city: "Cornellà de Llobregat",
    currency: "EUR",
    stadium: { name: "RCDE Stadium (Estadi Cornellà-El Prat)", capacity: 40000, ownership: "Club-owned" },
    ownership: { summary: "Rastar Group (Chen Yansheng; Shantou, China) — dominant shareholder and ultimate controlling party", category: "Real Club Deportivo Espanyol de Barcelona SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 68.6,
      wage_bill: 51.5,
      wage_to_revenue_pct: 75.1,
      net_profit: 2.3,
      total_liabilities: null,
      equity: 107.2,
      operating_profit: 8.5,
      profit_from_player_sales: null,
      pre_tax_profit: 2.6,
      net_debt: 34.4,
      data_notes: "Rastar Group (Chinese owner) has provided shareholder loans classified as 'Deudas con características especiales' (~€34m), constituting the majority of net debt. EBIT of €8.5m includes €22.6m gains on player registrations. Equity boosted by €32m capital increase in FY2023/24.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 23.7,
      wage_bill: 44.5,
      wage_to_revenue_pct: 187.8,
      operating_profit: -19.8,
      profit_from_player_sales: 17.9,
      pre_tax_profit: -18.4,
      net_debt: -2.8,
    },
    historical: [
      { season: "FY2023/24", revenue: 23.7, wage_bill: null, net_profit: -13.8 },
      { season: "FY2024/25", revenue: 68.6, wage_bill: 51.5, net_profit: 2.3 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── RC Celta de Vigo ──────────────────────────────────────────────────────────
  {
    slug: "rc-celta",
    name: "RC Celta de Vigo",
    country: "Spain",
    league: "La Liga",
    city: "Vigo",
    currency: "EUR",
    stadium: { name: "Estadio Abanca-Balaídos", capacity: 29000, ownership: "Club-owned" },
    ownership: { summary: "Mouriño family (Carlos Mouriño Atanes, President)", category: "Real Club Celta de Vigo SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2022/23 (Jun)",
      revenue: 69.9,
      wage_bill: 55.9,
      wage_to_revenue_pct: 79.9,
      net_profit: -13.3,
      total_liabilities: null,
      equity: 73.7,
      operating_profit: -17.0,
      profit_from_player_sales: null,
      pre_tax_profit: -17.6,
      net_debt: 20.9,
      data_notes: "Accounts from FY2022/23 (2 years old — most recent filed at publication). FY2023/24 and FY2024/25 accounts not yet publicly available.",
    },
    prior_year: null,
    historical: [
      { season: "FY2022/23", revenue: 69.9, wage_bill: 55.9, net_profit: -13.3 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Real Oviedo ───────────────────────────────────────────────────────────────
  {
    slug: "real-oviedo",
    name: "Real Oviedo",
    country: "Spain",
    league: "La Liga",
    city: "Oviedo",
    currency: "EUR",
    stadium: { name: "Estadio Carlos Tartiere", capacity: 30500, ownership: "Club-owned" },
    ownership: { summary: "Chinese-led consortium (Steve Zhou; Boying International). Promoted to La Liga for 2024/25 season.", category: "Real Oviedo SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 23.1,
      wage_bill: 19.6,
      wage_to_revenue_pct: 84.8,
      net_profit: -5.6,
      total_liabilities: null,
      equity: 5.9,
      operating_profit: -5.3,
      profit_from_player_sales: null,
      pre_tax_profit: -5.4,
      net_debt: 0.0,
      data_notes: "First La Liga season in FY2024/25 (promoted from La Liga 2). Fondos propios (retained net assets) negative at -€3.3m; total patrimonio neto (including grants) €5.9m. Minimal external financial debt.",
    },
    prior_year: null,
    historical: [
      { season: "FY2024/25", revenue: 23.1, wage_bill: 19.6, net_profit: -5.6 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── UD Almería ────────────────────────────────────────────────────────────────
  {
    slug: "ud-almeria",
    name: "UD Almería",
    country: "Spain",
    league: "La Liga",
    city: "Almería",
    currency: "EUR",
    stadium: { name: "Estadio de los Juegos Mediterráneos", capacity: 22000, ownership: "Municipal; rented by club" },
    ownership: { summary: "Turki Al-Sheikh (Saudi Arabia; entertainment/media group linked to Saudi government)", category: "Unión Deportiva Almería SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 66.5,
      wage_bill: 46.3,
      wage_to_revenue_pct: 69.6,
      net_profit: 3.9,
      total_liabilities: null,
      equity: 41.4,
      operating_profit: 7.1,
      profit_from_player_sales: null,
      pre_tax_profit: 5.2,
      net_debt: 26.0,
      data_notes: "Accounts from FY2023/24 (1 year old). Club was in La Liga during FY2023/24 and relegated at end of that season. FY2024/25 accounts not yet available.",
    },
    prior_year: null,
    historical: [
      { season: "FY2023/24", revenue: 66.5, wage_bill: 46.3, net_profit: 3.9 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Levante UD (null — no statutory accounts available) ──────────────────────
  {
    slug: "levante-ud",
    name: "Levante UD",
    country: "Spain",
    league: "La Liga",
    city: "Valencia",
    currency: "EUR",
    stadium: { name: "Estadio Ciudad de Valencia (Orriols)", capacity: 25354, ownership: "Club-owned" },
    ownership: { summary: null, category: "Levante Unión Deportiva SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      data_notes: "Annual accounts not available for analysis at time of publication (accessed via annual report links requiring login).",
    },
    prior_year: null,
    historical: [],
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ─── CA Osasuna (null — foundation accounts) ───────────────────────────────────
  {
    slug: "ca-osasuna",
    name: "CA Osasuna",
    country: "Spain",
    league: "La Liga",
    city: "Pamplona",
    currency: "EUR",
    stadium: { name: "El Sadar", capacity: 23576, ownership: "Club-owned" },
    ownership: { summary: "Member-owned foundation (Fundación Club Atlético Osasuna); non-profit association", category: "Club Atlético Osasuna (Fundación)", fifty_plus_one: null },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      data_notes: "Foundation (fundación) accounts filed — not comparable with SAD commercial accounts. Full commercial accounts not available for analysis.",
    },
    prior_year: null,
    historical: [],
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ─── Villarreal CF (null — foundation accounts) ────────────────────────────────
  {
    slug: "villarreal-cf",
    name: "Villarreal CF",
    country: "Spain",
    league: "La Liga",
    city: "Villarreal",
    currency: "EUR",
    stadium: { name: "Estadio de la Cerámica", capacity: 23500, ownership: "Club-owned" },
    ownership: { summary: "Roig family (Fernando Roig Negueroles)", category: "Villarreal Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      data_notes: "Foundation (Fundació Villarreal CF) accounts filed at Companies House — not the trading entity's financial statements. SAD commercial accounts not publicly available.",
    },
    prior_year: null,
    historical: [],
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ══════════════════════════════════════════════════════
  // LA LIGA 2 (LaLiga Hypermotion)
  // ══════════════════════════════════════════════════════

  // ─── Albacete BP ───────────────────────────────────────────────────────────────
  {
    slug: "albacete-bp",
    name: "Albacete BP",
    country: "Spain",
    league: "La Liga 2",
    city: "Albacete",
    currency: "EUR",
    stadium: { name: "Estadio Carlos Belmonte", capacity: 17491, ownership: "Municipal" },
    ownership: { summary: "Carlos González Calvo (President, majority shareholder)", category: "Albacete Balompié SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 9.8,
      wage_bill: 7.8,
      wage_to_revenue_pct: 79.6,
      net_profit: -0.7,
      total_liabilities: null,
      equity: 12.2,
      operating_profit: -0.6,
      profit_from_player_sales: null,
      pre_tax_profit: -0.7,
      net_debt: 12.4,
      data_notes: null,
    },
    prior_year: null,
    historical: [
      { season: "FY2024/25", revenue: 9.8, wage_bill: 7.8, net_profit: -0.7 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Burgos CF ─────────────────────────────────────────────────────────────────
  {
    slug: "burgos-cf",
    name: "Burgos CF",
    country: "Spain",
    league: "La Liga 2",
    city: "Burgos",
    currency: "EUR",
    stadium: { name: "Estadio El Plantío", capacity: 12643, ownership: "Municipal" },
    ownership: { summary: "Jon Larrea and Gonzalo Calderón (co-owners)", category: "Burgos Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 11.2,
      wage_bill: 8.1,
      wage_to_revenue_pct: 72.3,
      net_profit: -1.6,
      total_liabilities: null,
      equity: 1.8,
      operating_profit: -1.2,
      profit_from_player_sales: null,
      pre_tax_profit: -1.6,
      net_debt: 7.0,
      data_notes: "Accounts from FY2023/24 (1 year old). Abridged accounts filed — limited line-item detail.",
    },
    prior_year: null,
    historical: [
      { season: "FY2023/24", revenue: 11.2, wage_bill: 8.1, net_profit: -1.6 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Cádiz CF ──────────────────────────────────────────────────────────────────
  {
    slug: "cadiz-cf",
    name: "Cádiz CF",
    country: "Spain",
    league: "La Liga 2",
    city: "Cádiz",
    currency: "EUR",
    stadium: { name: "Estadio Nuevo Mirandilla", capacity: 20724, ownership: "Municipal" },
    ownership: { summary: "Manuel Vizcaíno Amor (President). Parent company Cádiz CF SAL listed on Nasdaq (CADZ).", category: "Cádiz Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 19.9,
      wage_bill: 18.9,
      wage_to_revenue_pct: 95.0,
      net_profit: 1.6,
      total_liabilities: null,
      equity: 5.6,
      operating_profit: 2.2,
      profit_from_player_sales: null,
      pre_tax_profit: 1.9,
      net_debt: 34.8,
      data_notes: "Parent company Cádiz CF SAL listed on Nasdaq (CADZ). Revenue includes La Liga broadcasting distributions (relegated at end of FY2023/24). Net debt elevated relative to club size.",
    },
    prior_year: null,
    historical: [
      { season: "FY2024/25", revenue: 19.9, wage_bill: 18.9, net_profit: 1.6 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── CD Castellón ──────────────────────────────────────────────────────────────
  {
    slug: "cd-castellon",
    name: "CD Castellón",
    country: "Spain",
    league: "La Liga 2",
    city: "Castellón de la Plana",
    currency: "EUR",
    stadium: { name: "Estadio Castalia", capacity: 17000, ownership: "Municipal" },
    ownership: { summary: "Bob Voulgaris (professional gambler; via Corner4 Sports group, registered Cayman Islands)", category: "Club Deportivo Castellón SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 11.3,
      wage_bill: 8.5,
      wage_to_revenue_pct: 75.2,
      net_profit: -3.9,
      total_liabilities: null,
      equity: 5.5,
      operating_profit: -3.6,
      profit_from_player_sales: null,
      pre_tax_profit: -3.7,
      net_debt: 22.8,
      data_notes: "Owned by Bob Voulgaris via Corner4 Sports (Cayman Islands). Net debt elevated relative to club scale.",
    },
    prior_year: null,
    historical: [
      { season: "FY2024/25", revenue: 11.3, wage_bill: 8.5, net_profit: -3.9 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── SD Eibar ──────────────────────────────────────────────────────────────────
  {
    slug: "sd-eibar",
    name: "SD Eibar",
    country: "Spain",
    league: "La Liga 2",
    city: "Eibar",
    currency: "EUR",
    stadium: { name: "Estadio Municipal de Ipurúa", capacity: 7083, ownership: "Club-owned; stadium-related financing significant" },
    ownership: { summary: "Cooperativa de socios (member co-operative); one of the smallest clubs in Spanish professional football by stadium capacity", category: "Sociedad Deportiva Eibar SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 10.7,
      wage_bill: 11.3,
      wage_to_revenue_pct: 105.6,
      net_profit: -1.9,
      total_liabilities: null,
      equity: 47.9,
      operating_profit: -4.2,
      profit_from_player_sales: null,
      pre_tax_profit: -1.9,
      net_debt: 56.6,
      data_notes: "Accounts filed in miles de euros (€'000s). Net debt of €56.6m is large relative to revenue (~530% of turnover) — primarily stadium/infrastructure financing accumulated from La Liga era. High equity base reflects historic capital injections and retained gains.",
    },
    prior_year: null,
    historical: [
      { season: "FY2024/25", revenue: 10.7, wage_bill: 11.3, net_profit: -1.9 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Elche CF ──────────────────────────────────────────────────────────────────
  {
    slug: "elche-cf",
    name: "Elche CF",
    country: "Spain",
    league: "La Liga 2",
    city: "Elche",
    currency: "EUR",
    stadium: { name: "Estadio Manuel Martínez Valero", capacity: 33732, ownership: "Municipal" },
    ownership: { summary: "Christian Bragarnik (Argentine football agent; via Huracan International LLC)", category: "Elche Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 14.0,
      wage_bill: 15.7,
      wage_to_revenue_pct: 112.1,
      net_profit: 9.0,
      total_liabilities: null,
      equity: 40.7,
      operating_profit: 8.9,
      profit_from_player_sales: null,
      pre_tax_profit: 9.0,
      net_debt: -9.0,
      data_notes: "Accounts from FY2023/24 (1 year old). Club relegated from La Liga at end of FY2022/23. Net profit despite wage bill exceeding revenue driven by significant player sale gains. Net cash position.",
    },
    prior_year: null,
    historical: [
      { season: "FY2023/24", revenue: 14.0, wage_bill: 15.7, net_profit: 9.0 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Granada CF (null — foundation accounts) ───────────────────────────────────
  {
    slug: "granada-cf",
    name: "Granada CF",
    country: "Spain",
    league: "La Liga 2",
    city: "Granada",
    currency: "EUR",
    stadium: { name: "Estadio Nuevo Los Cármenes", capacity: 19336, ownership: "Municipal" },
    ownership: { summary: "Grupo Pachuca (Mexican ownership group; Jesús Martínez, President)", category: "Granada Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      data_notes: "Foundation (fundación) accounts filed — SAD commercial accounts not available for analysis.",
    },
    prior_year: null,
    historical: [],
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ─── SD Huesca ─────────────────────────────────────────────────────────────────
  {
    slug: "sd-huesca",
    name: "SD Huesca",
    country: "Spain",
    league: "La Liga 2",
    city: "Huesca",
    currency: "EUR",
    stadium: { name: "El Alcoraz", capacity: 10200, ownership: "Club-owned" },
    ownership: { summary: "Grupo Olimpo (Spanish private equity); Felipe Moreno (President)", category: "Sociedad Deportiva Huesca SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 9.5,
      wage_bill: 9.7,
      wage_to_revenue_pct: 102.1,
      net_profit: -5.1,
      total_liabilities: null,
      equity: -1.8,
      operating_profit: -5.0,
      profit_from_player_sales: null,
      pre_tax_profit: -5.1,
      net_debt: 22.1,
      data_notes: "Accounts from FY2023/24 (1 year old). Qualified audit opinion. Negative equity -€1.8m. Net debt elevated relative to revenue.",
    },
    prior_year: null,
    historical: [
      { season: "FY2023/24", revenue: 9.5, wage_bill: 9.7, net_profit: -5.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── CD Leganés ────────────────────────────────────────────────────────────────
  {
    slug: "cd-leganes",
    name: "CD Leganés",
    country: "Spain",
    league: "La Liga 2",
    city: "Leganés",
    currency: "EUR",
    stadium: { name: "Estadio Municipal de Butarque", capacity: 11454, ownership: "Municipal" },
    ownership: { summary: "Felipe Moreno (President, main shareholder)", category: "Club Deportivo Leganés SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 11.3,
      wage_bill: 14.2,
      wage_to_revenue_pct: 125.7,
      net_profit: -5.8,
      total_liabilities: null,
      equity: -6.9,
      operating_profit: -5.7,
      profit_from_player_sales: null,
      pre_tax_profit: -5.8,
      net_debt: 14.4,
      data_notes: "Accounts from FY2023/24 (1 year old). Wages significantly exceed revenue. Negative equity -€6.9m. Club promoted to La Liga for FY2024/25.",
    },
    prior_year: null,
    historical: [
      { season: "FY2023/24", revenue: 11.3, wage_bill: 14.2, net_profit: -5.8 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── UD Las Palmas (null — no statutory accounts) ──────────────────────────────
  {
    slug: "ud-las-palmas",
    name: "UD Las Palmas",
    country: "Spain",
    league: "La Liga 2",
    city: "Las Palmas de Gran Canaria",
    currency: "EUR",
    stadium: { name: "Estadio Gran Canaria", capacity: 32400, ownership: "Regional government" },
    ownership: { summary: "Grupo Bahía (Kirsten Feldmann)", category: "Unión Deportiva Las Palmas SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      data_notes: "Filed document is a LaLiga FFP agreed-upon procedures report, not statutory annual accounts. No standalone annual accounts available for analysis.",
    },
    prior_year: null,
    historical: [],
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ─── Málaga CF ─────────────────────────────────────────────────────────────────
  {
    slug: "malaga-cf",
    name: "Málaga CF",
    country: "Spain",
    league: "La Liga 2",
    city: "Málaga",
    currency: "EUR",
    stadium: { name: "La Rosaleda", capacity: 30044, ownership: "Municipal" },
    ownership: { summary: "Administración concursal (judicial administration). Club emerged from creditor proceedings; ownership formally in administration.", category: "Málaga Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 10.8,
      wage_bill: 8.7,
      wage_to_revenue_pct: 80.6,
      net_profit: 4.2,
      total_liabilities: null,
      equity: 0.1,
      operating_profit: 0.5,
      profit_from_player_sales: null,
      pre_tax_profit: 3.9,
      net_debt: 28.7,
      data_notes: "Accounts from FY2023/24 (1 year old). Club under judicial administration (concurso de acreedores/administración concursal). Pre-tax profit of €3.9m includes extraordinary items from creditor debt write-offs.",
    },
    prior_year: null,
    historical: [
      { season: "FY2023/24", revenue: 10.8, wage_bill: 8.7, net_profit: 4.2 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── CD Mirandés ───────────────────────────────────────────────────────────────
  {
    slug: "cd-mirandes",
    name: "CD Mirandés",
    country: "Spain",
    league: "La Liga 2",
    city: "Miranda de Ebro",
    currency: "EUR",
    stadium: { name: "Estadio Municipal Anduva", capacity: 8000, ownership: "Municipal" },
    ownership: { summary: "Alfredo Intxausti (President); private Spanish ownership", category: "Club Deportivo Mirandés SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2022/23 (Jun)",
      revenue: 7.5,
      wage_bill: 5.4,
      wage_to_revenue_pct: 72.0,
      net_profit: 0.1,
      total_liabilities: null,
      equity: 8.3,
      operating_profit: 0.2,
      profit_from_player_sales: null,
      pre_tax_profit: 0.2,
      net_debt: -3.3,
      data_notes: "Accounts from FY2022/23 (2 years old). Net cash position. One of the smallest clubs in La Liga 2 by revenue.",
    },
    prior_year: null,
    historical: [
      { season: "FY2022/23", revenue: 7.5, wage_bill: 5.4, net_profit: 0.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Racing Club de Santander ──────────────────────────────────────────────────
  {
    slug: "racing-santander",
    name: "Racing Club de Santander",
    country: "Spain",
    league: "La Liga 2",
    city: "Santander",
    currency: "EUR",
    stadium: { name: "El Sardinero", capacity: 22200, ownership: "Club-owned" },
    ownership: { summary: "Haralabos Voulgaris (brother of Bob Voulgaris/Corner4); also has strategic stakes from other investors", category: "Real Racing Club de Santander SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 19.3,
      wage_bill: 12.8,
      wage_to_revenue_pct: 66.3,
      net_profit: 0.7,
      total_liabilities: null,
      equity: 6.7,
      operating_profit: 2.1,
      profit_from_player_sales: null,
      pre_tax_profit: 1.0,
      net_debt: 30.7,
      data_notes: "Abbreviated (abridged) accounts filed. Fondos propios (shareholders' funds) negative at -€14.1m; total patrimonio neto including grants €6.7m. Net debt elevated relative to revenue.",
    },
    prior_year: null,
    historical: [
      { season: "FY2024/25", revenue: 19.3, wage_bill: 12.8, net_profit: 0.7 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Real Zaragoza ─────────────────────────────────────────────────────────────
  {
    slug: "real-zaragoza",
    name: "Real Zaragoza",
    country: "Spain",
    league: "La Liga 2",
    city: "Zaragoza",
    currency: "EUR",
    stadium: { name: "La Romareda", capacity: 34596, ownership: "Municipal" },
    ownership: { summary: "Grupo Zaragoza Deporte (Zaragoza City Council holds minority; private shareholders majority)", category: "Real Zaragoza SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 17.9,
      wage_bill: 15.7,
      wage_to_revenue_pct: 87.7,
      net_profit: -0.1,
      total_liabilities: null,
      equity: 53.1,
      operating_profit: 1.1,
      profit_from_player_sales: null,
      pre_tax_profit: 0.0,
      net_debt: 31.0,
      data_notes: "Club in concurso de acreedores (creditor arrangement proceedings). DTA €21.7m recognised. Equity inflated by historical capital injections and deferred tax assets. Net debt ~€31m approximate.",
    },
    prior_year: null,
    historical: [
      { season: "FY2024/25", revenue: 17.9, wage_bill: 15.7, net_profit: -0.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Real Valladolid ───────────────────────────────────────────────────────────
  {
    slug: "real-valladolid",
    name: "Real Valladolid",
    country: "Spain",
    league: "La Liga 2",
    city: "Valladolid",
    currency: "EUR",
    stadium: { name: "Estadio José Zorrilla", capacity: 26512, ownership: "Municipal" },
    ownership: { summary: "Ronaldo Nazário (Brazilian ex-footballer; majority shareholder ~51%). Club relegated from La Liga at end of FY2023/24.", category: "Real Valladolid Club de Fútbol SAD", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 17.6,
      wage_bill: 29.9,
      wage_to_revenue_pct: 169.9,
      net_profit: 0.2,
      total_liabilities: null,
      equity: -17.9,
      operating_profit: 1.2,
      profit_from_player_sales: null,
      pre_tax_profit: 0.1,
      net_debt: 30.5,
      data_notes: "Accounts from FY2023/24 (1 year old). Wage bill 170% of revenue — extremely high. Going concern emphasis paragraph; negative equity -€17.9m (total patrimonio neto including grants). CVC LaLiga participatory loan €24.7m included in net debt. Ronaldo Nazário became majority shareholder in 2018.",
    },
    prior_year: null,
    historical: [
      { season: "FY2023/24", revenue: 17.6, wage_bill: 29.9, net_profit: 0.2 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

];
