// AUTO-GENERATED — source: DE_Football_DB_v0.8.xlsx, NL_Football_DB_v0.4.xlsx, AT_Football_DB_v0.8.xlsx
// Monetary values in EUR millions. Historical: Germany FY18/19–FY23/24 | Netherlands/Belgium 2019/20–2023/24 | Austria 2020/21–2024/25
// total_liabilities stored for DE/AT — NOT net_debt. net_debt is always null for EU clubs.

import { frClubs } from "./frClubs";
import { dkClubs } from "./dkClubs";
import { noClubs } from "./noClubs";
import { swClubs } from "./swClubs";
import { itClubs } from "./itClubs";
import { esClubs } from "./esClubs";
import { deClubs } from "./deClubs";
import { de2Clubs } from "./de2Clubs";
import { atClubs } from "./atClubs";
import { chClubs } from "./chClubs";

export type EUCountry = "Germany" | "Austria" | "Switzerland" | "Netherlands" | "Belgium" | "France" | "Denmark" | "Norway" | "Sweden" | "Italy" | "Spain";

export interface EUHistoricalYear {
  season: string;
  revenue: number | null;
  wage_bill: number | null;
  net_profit: number | null;
  equity?: number | null;
  total_liabilities?: number | null;
}

/** Prior-year financial snapshot — same optional fields as financials */
export interface EUPriorYear {
  season: string;
  revenue: number | null;
  wage_bill: number | null;
  wage_to_revenue_pct: number | null;
  net_profit?: number | null;
  total_liabilities?: number | null;
  equity?: number | null;
  operating_profit?: number | null;
  profit_from_player_sales?: number | null;
  pre_tax_profit?: number | null;
  net_debt?: number | null;
}

export interface EUClub {
  slug: string;
  name: string;
  country: EUCountry;
  league: string;
  city: string | null;
  currency: "EUR" | "USD" | "SEK";
  stadium: { name: string | null; capacity: number | null; ownership: string | null } | null;
  ownership: { summary: string | null; category: string | null; fifty_plus_one: string | null } | null;
  financials: {
    most_recent_year: string | null;
    revenue: number | null;
    wage_bill: number | null;
    wage_to_revenue_pct: number | null;
    net_profit: number | null;
    total_liabilities: number | null;
    equity: number | null;
    /** French, Italian, Spanish, Norwegian, Danish clubs */
    operating_profit?: number | null;
    profit_from_player_sales?: number | null;
    pre_tax_profit?: number | null;
    net_debt?: number | null;
    data_notes: string | null;
  };
  prior_year?: EUPriorYear | null;
  historical: EUHistoricalYear[];
  tm_squad_value_eur_m: number | null;
  data_status: string;
  volatility_tier: string | null;
}


// ─── Netherlands ─────────────────────────────────────────────────────────────────
const nlClubs: EUClub[] = [
{
  slug: "ajax",
  name: "Ajax",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Amsterdam",
  currency: "EUR",
  stadium: { name: "Johan Cruijff ArenA", capacity: 54990, ownership: "Amsterdam ArenA BV (city majority ~48%, club minority)" },
  ownership: { summary: "AFC Ajax NV listed Euronext Amsterdam (AJAX.AS); dispersed shareholders largely institutional", category: "Listed-public", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 152.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: -9.8,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 162.8, wage_bill: null, net_profit: -22.6 },
    { season: "2020/21", revenue: 153.9, wage_bill: null, net_profit: -10.5 },
    { season: "2021/22", revenue: 111.1, wage_bill: null, net_profit: -7.2 },
    { season: "2022/23", revenue: 196.4, wage_bill: null, net_profit: 39.0 },
    { season: "2023/24", revenue: 152.0, wage_bill: null, net_profit: -9.8 },
  ],
  tm_squad_value_eur_m: 175.0,
  data_status: "VERIFIED (Kroes exit)",
  volatility_tier: "HIGH",
},
{
  slug: "psv",
  name: "PSV",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Eindhoven",
  currency: "EUR",
  stadium: { name: "Philips Stadion", capacity: 36500, ownership: "Club-owned (PSV NV)" },
  ownership: { summary: "Stichting PSV Voetbal (members) controls PSV NV; historic Philips ties; PSV Holding commercial arm", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 168.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 29.3,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 94.2, wage_bill: null, net_profit: -18.9 },
    { season: "2020/21", revenue: 87.0, wage_bill: null, net_profit: -8.6 },
    { season: "2021/22", revenue: 101.0, wage_bill: null, net_profit: 13.6 },
    { season: "2022/23", revenue: 123.8, wage_bill: null, net_profit: 28.1 },
    { season: "2023/24", revenue: 168.0, wage_bill: null, net_profit: 29.3 },
  ],
  tm_squad_value_eur_m: 240.0,
  data_status: "VERIFIED",
  volatility_tier: "LOW",
},
{
  slug: "feyenoord",
  name: "Feyenoord",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Rotterdam",
  currency: "EUR",
  stadium: { name: "De Kuip (Stadion Feijenoord)", capacity: 47500, ownership: "Stadion Feijenoord NV (separate entity)" },
  ownership: { summary: "Stichting Continu\u00efteit Feyenoord + Vrienden van Feyenoord; member-influenced", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 150.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 14.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 73.7, wage_bill: null, net_profit: -10.0 },
    { season: "2020/21", revenue: 66.4, wage_bill: null, net_profit: -10.3 },
    { season: "2021/22", revenue: 92.0, wage_bill: null, net_profit: 11.6 },
    { season: "2022/23", revenue: 127.0, wage_bill: null, net_profit: 19.5 },
    { season: "2023/24", revenue: 150.0, wage_bill: null, net_profit: 14.0 },
  ],
  tm_squad_value_eur_m: 165.0,
  data_status: "VERIFIED (Van Persie era)",
  volatility_tier: "MEDIUM",
},
{
  slug: "az",
  name: "AZ",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Alkmaar",
  currency: "EUR",
  stadium: { name: "AFAS Stadion", capacity: 19500, ownership: "Club-owned" },
  ownership: { summary: "Robert Eenhoorn era; post-Eisma family restructure", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 70.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 5.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 46.0, wage_bill: null, net_profit: -2.1 },
    { season: "2020/21", revenue: 44.0, wage_bill: null, net_profit: -5.0 },
    { season: "2021/22", revenue: 52.0, wage_bill: null, net_profit: 3.0 },
    { season: "2022/23", revenue: 68.0, wage_bill: null, net_profit: 8.0 },
    { season: "2023/24", revenue: 70.0, wage_bill: null, net_profit: 5.0 },
  ],
  tm_squad_value_eur_m: 75.0,
  data_status: "VERIFIED",
  volatility_tier: "MEDIUM",
},
{
  slug: "fc_twente",
  name: "FC Twente",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Enschede",
  currency: "EUR",
  stadium: { name: "De Grolsch Veste", capacity: 30200, ownership: "Municipal (Enschede)" },
  ownership: { summary: "Stichting FC Twente '65 post-2016 rescue; member-supervised", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 48.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 3.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 32.0, wage_bill: null, net_profit: -3.5 },
    { season: "2020/21", revenue: 33.0, wage_bill: null, net_profit: 1.2 },
    { season: "2021/22", revenue: 36.0, wage_bill: null, net_profit: 2.5 },
    { season: "2022/23", revenue: 42.0, wage_bill: null, net_profit: 4.1 },
    { season: "2023/24", revenue: 48.0, wage_bill: null, net_profit: 3.0 },
  ],
  tm_squad_value_eur_m: 42.0,
  data_status: "VERIFIED",
  volatility_tier: "LOW",
},
{
  slug: "fc_utrecht",
  name: "FC Utrecht",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Utrecht",
  currency: "EUR",
  stadium: { name: "Stadion Galgenwaard", capacity: 23750, ownership: "Municipal" },
  ownership: { summary: "Frans van Seumeren (majority owner)", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 38.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 28.0, wage_bill: null, net_profit: -2.0 },
    { season: "2020/21", revenue: 27.0, wage_bill: null, net_profit: -3.5 },
    { season: "2021/22", revenue: 32.0, wage_bill: null, net_profit: 0.5 },
    { season: "2022/23", revenue: 36.0, wage_bill: null, net_profit: 1.0 },
    { season: "2023/24", revenue: 38.0, wage_bill: null, net_profit: null },
  ],
  tm_squad_value_eur_m: 35.0,
  data_status: "VERIFIED",
  volatility_tier: "MEDIUM",
},
{
  slug: "sparta_rotterdam",
  name: "Sparta Rotterdam",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Rotterdam",
  currency: "EUR",
  stadium: { name: "Het Kasteel", capacity: 11026, ownership: "Club-owned" },
  ownership: { summary: "Member/Stichting structure; oldest Dutch pro club (1888)", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 18.0,
  data_status: "PARTIAL",
  volatility_tier: "LOW",
},
{
  slug: "nec",
  name: "NEC",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Nijmegen",
  currency: "EUR",
  stadium: { name: "Goffertstadion", capacity: 12500, ownership: "Municipal" },
  ownership: { summary: "Marcel Boekhoorn (Dutch billionaire; Telfort founder)", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 27.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 14.0, wage_bill: null, net_profit: -1.5 },
    { season: "2020/21", revenue: 16.0, wage_bill: null, net_profit: -1.0 },
    { season: "2021/22", revenue: 22.0, wage_bill: null, net_profit: 0.8 },
    { season: "2022/23", revenue: 24.0, wage_bill: null, net_profit: 1.0 },
    { season: "2023/24", revenue: 27.0, wage_bill: null, net_profit: null },
  ],
  tm_squad_value_eur_m: 28.0,
  data_status: "VERIFIED",
  volatility_tier: "MEDIUM",
},
{
  slug: "go_ahead_eagles",
  name: "Go Ahead Eagles",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Deventer",
  currency: "EUR",
  stadium: { name: "De Adelaarshorst", capacity: 10000, ownership: "Municipal" },
  ownership: { summary: "Member-controlled Stichting", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 15.0,
  data_status: "PARTIAL",
  volatility_tier: "LOW",
},
{
  slug: "sc_heerenveen",
  name: "SC Heerenveen",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Heerenveen",
  currency: "EUR",
  stadium: { name: "Abe Lenstra Stadion", capacity: 26100, ownership: "Club-owned" },
  ownership: { summary: "Stichting Sportclub Heerenveen (Oranje-Wit structure)", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 27.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 22.0, wage_bill: null, net_profit: -1.0 },
    { season: "2020/21", revenue: 21.0, wage_bill: null, net_profit: -2.0 },
    { season: "2021/22", revenue: 24.0, wage_bill: null, net_profit: 1.5 },
    { season: "2022/23", revenue: 26.0, wage_bill: null, net_profit: 1.0 },
    { season: "2023/24", revenue: 27.0, wage_bill: null, net_profit: null },
  ],
  tm_squad_value_eur_m: 22.0,
  data_status: "PARTIAL",
  volatility_tier: "LOW",
},
{
  slug: "pec_zwolle",
  name: "PEC Zwolle",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Zwolle",
  currency: "EUR",
  stadium: { name: "MAC3PARK Stadion", capacity: 12500, ownership: "Municipal" },
  ownership: { summary: "Adriaan Visser consortium / local Dutch ownership", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 14.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "heracles_almelo",
  name: "Heracles Almelo",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Almelo",
  currency: "EUR",
  stadium: { name: "Erve Asito", capacity: 12080, ownership: "Municipal" },
  ownership: { summary: "Stichting + local members", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 11.0,
  data_status: "PARTIAL",
  volatility_tier: "LOW",
},
{
  slug: "fortuna_sittard",
  name: "Fortuna Sittard",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Sittard",
  currency: "EUR",
  stadium: { name: "Fortuna Sittard Stadion", capacity: 12500, ownership: "Municipal" },
  ownership: { summary: "Isitan G\u00fcn (Turkish businessman) via consortium", category: "Foreign-strategic", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 13.0,
  data_status: "VERIFIED",
  volatility_tier: "MEDIUM",
},
{
  slug: "rkc_waalwijk",
  name: "RKC Waalwijk",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Waalwijk",
  currency: "EUR",
  stadium: { name: "Mandemakers Stadion", capacity: 7500, ownership: "Municipal" },
  ownership: { summary: "Frank van Mosselveld / local consortium", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 10.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "willem_ii",
  name: "Willem II",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Tilburg",
  currency: "EUR",
  stadium: { name: "Koning Willem II Stadion", capacity: 14700, ownership: "Municipal" },
  ownership: { summary: "Member Vereniging + Stichting", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 12.0,
  data_status: "VERIFIED",
  volatility_tier: "LOW",
},
{
  slug: "nac_breda",
  name: "NAC Breda",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Breda",
  currency: "EUR",
  stadium: { name: "Rat Verlegh Stadion", capacity: 19000, ownership: "Municipal" },
  ownership: { summary: "Bob Pauw consortium / NAC Investments", category: "Dutch-corporate", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 10.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "almere_city",
  name: "Almere City",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Almere",
  currency: "EUR",
  stadium: { name: "Yanmar Stadion", capacity: 4501, ownership: "Club-owned" },
  ownership: { summary: "John Bes / local investors consortium", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 8.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "fc_groningen",
  name: "FC Groningen",
  country: "Netherlands",
  league: "Eredivisie",
  city: "Groningen",
  currency: "EUR",
  stadium: { name: "Euroborg", capacity: 22579, ownership: "Municipal" },
  ownership: { summary: "Stichting FC Groningen members", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 18.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: -6.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 23.0, wage_bill: null, net_profit: -2.5 },
    { season: "2020/21", revenue: 22.0, wage_bill: null, net_profit: -3.0 },
    { season: "2021/22", revenue: 25.0, wage_bill: null, net_profit: -1.5 },
    { season: "2022/23", revenue: 23.0, wage_bill: null, net_profit: -4.0 },
    { season: "2023/24", revenue: 18.0, wage_bill: null, net_profit: -6.0 },
  ],
  tm_squad_value_eur_m: 15.0,
  data_status: "VERIFIED",
  volatility_tier: "LOW",
},
{
  slug: "vitesse",
  name: "Vitesse",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Arnhem",
  currency: "EUR",
  stadium: { name: "GelreDome", capacity: 21248, ownership: "Private (GelreDome BV)" },
  ownership: { summary: "License REINSTATED Sept 2025 by Arnhem Court of Appeals after June 2024 revocation was overturned; post-Oyf/Coley Parry ownership still under local rescue consortium supervision", category: "Multi-owner", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [
    { season: "2019/20", revenue: 29.0, wage_bill: null, net_profit: -6.0 },
    { season: "2020/21", revenue: 27.0, wage_bill: null, net_profit: -8.0 },
    { season: "2021/22", revenue: 33.0, wage_bill: null, net_profit: -4.0 },
    { season: "2022/23", revenue: 28.0, wage_bill: null, net_profit: -12.0 },
    { season: "2023/24", revenue: null, wage_bill: null, net_profit: null },
  ],
  tm_squad_value_eur_m: 5.0,
  data_status: "VERIFIED (reinstatement)",
  volatility_tier: "HIGH",
},
{
  slug: "roda_jc",
  name: "Roda JC",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Kerkrade",
  currency: "EUR",
  stadium: { name: "Parkstad Limburg Stadion", capacity: 19979, ownership: "Municipal" },
  ownership: { summary: "Mauricio Garcia de la Vega (Mexican) era ended; local consortium", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 8.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "mvv_maastricht",
  name: "MVV Maastricht",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Maastricht",
  currency: "EUR",
  stadium: { name: "De Geusselt", capacity: 10000, ownership: "Municipal" },
  ownership: { summary: "Local Stichting/investors", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 4.0,
  data_status: "PARTIAL",
  volatility_tier: "LOW",
},
{
  slug: "de_graafschap",
  name: "De Graafschap",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Doetinchem",
  currency: "EUR",
  stadium: { name: "De Vijverberg", capacity: 12600, ownership: "Municipal" },
  ownership: { summary: "Stichting + members", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 6.0,
  data_status: "PARTIAL",
  volatility_tier: "LOW",
},
{
  slug: "fc_dordrecht",
  name: "FC Dordrecht",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Dordrecht",
  currency: "EUR",
  stadium: { name: "Riwal Hoogwerkers Stadion", capacity: 4235, ownership: "Municipal" },
  ownership: { summary: "Chien Lee / Pacific Media Group linked consortium (US/multi-club)", category: "Foreign-financial", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 4.0,
  data_status: "VERIFIED",
  volatility_tier: "MEDIUM",
},
{
  slug: "sc_cambuur",
  name: "SC Cambuur",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Leeuwarden",
  currency: "EUR",
  stadium: { name: "Kooiplein Stadion (new 2024)", capacity: 15000, ownership: "Municipal" },
  ownership: { summary: "Stichting + local businesses", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 7.0,
  data_status: "PARTIAL",
  volatility_tier: "LOW",
},
{
  slug: "fc_den_bosch",
  name: "FC Den Bosch",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Den Bosch",
  currency: "EUR",
  stadium: { name: "De Vliert", capacity: 8500, ownership: "Municipal" },
  ownership: { summary: "Kakhi Jordania (Georgian investor)", category: "Foreign-strategic", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 3.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "helmond_sport",
  name: "Helmond Sport",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Helmond",
  currency: "EUR",
  stadium: { name: "Lavans Stadion", capacity: 4100, ownership: "Municipal" },
  ownership: { summary: "Philippe van Esch (Dutch local)", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 3.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "top_oss",
  name: "TOP Oss",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Oss",
  currency: "EUR",
  stadium: { name: "Frans Heesen Stadion", capacity: 4700, ownership: "Municipal" },
  ownership: { summary: "Local consortium", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 3.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "fc_eindhoven",
  name: "FC Eindhoven",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Eindhoven",
  currency: "EUR",
  stadium: { name: "Jan Louwers Stadion", capacity: 4200, ownership: "Municipal" },
  ownership: { summary: "Local Dutch investors", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 4.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "vvv_venlo",
  name: "VVV-Venlo",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Venlo",
  currency: "EUR",
  stadium: { name: "De Koel", capacity: 8000, ownership: "Municipal" },
  ownership: { summary: "Hai Berden / local", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 5.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "fc_emmen",
  name: "FC Emmen",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Emmen",
  currency: "EUR",
  stadium: { name: "De Oude Meerdijk", capacity: 8600, ownership: "Municipal" },
  ownership: { summary: "Ronald Lubbers (Dutch)", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 4.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "ado_den_haag",
  name: "ADO Den Haag",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "The Hague",
  currency: "EUR",
  stadium: { name: "Bingoal Stadion", capacity: 15000, ownership: "Municipal" },
  ownership: { summary: "Bolt Football Holdings (Gauthier Ganaye-linked US) since 20 Feb 2023; prior: Globalon Football Holdings (US) 2021-2023; Wang Hui/UAE era ended bankruptcy 2021; Harm de Boer president 2025", category: "Foreign-financial", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 7.0,
  data_status: "VERIFIED (Bolt Football)",
  volatility_tier: "HIGH",
},
{
  slug: "jong_ajax",
  name: "Jong Ajax",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Amsterdam",
  currency: "EUR",
  stadium: { name: "De Toekomst", capacity: 2250, ownership: "Club-owned" },
  ownership: { summary: "Subsidiary of AFC Ajax NV (listed)", category: "Listed-public", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 20.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "jong_az",
  name: "Jong AZ",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Alkmaar",
  currency: "EUR",
  stadium: { name: "AFAS Trainingscomplex", capacity: 1500, ownership: "Club-owned" },
  ownership: { summary: "Subsidiary of AZ NV", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 12.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "jong_utrecht",
  name: "Jong Utrecht",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Utrecht",
  currency: "EUR",
  stadium: { name: "Sportcomplex Zoudenbalch", capacity: 1500, ownership: "Club-owned" },
  ownership: { summary: "Subsidiary of FC Utrecht BV", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 8.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "jong_psv",
  name: "Jong PSV",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Eindhoven",
  currency: "EUR",
  stadium: { name: "De Herdgang", capacity: 2500, ownership: "Club-owned" },
  ownership: { summary: "Subsidiary of PSV NV", category: "Stichting (fan-controlled)", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 15.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "telstar",
  name: "Telstar",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Velsen (IJmuiden)",
  currency: "EUR",
  stadium: { name: "711 Stadion (Rabobank IJmond Stadion)", capacity: 3060, ownership: "Municipal" },
  ownership: { summary: "Pacific Media Group / Chien Lee US consortium (indirect links)", category: "Foreign-financial", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 3.0,
  data_status: "VERIFIED",
  volatility_tier: "MEDIUM",
},
{
  slug: "fc_volendam",
  name: "FC Volendam",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Volendam",
  currency: "EUR",
  stadium: { name: "Kras Stadion", capacity: 6244, ownership: "Municipal" },
  ownership: { summary: "Jonk family (Wim Jonk) + local", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 6.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
{
  slug: "excelsior",
  name: "Excelsior",
  country: "Netherlands",
  league: "Keuken Kampioen Divisie",
  city: "Rotterdam",
  currency: "EUR",
  stadium: { name: "Van Donge & De Roo Stadion", capacity: 4500, ownership: "Municipal" },
  ownership: { summary: "Local Dutch investors post-Feyenoord partnership era", category: "Dutch-family", fifty_plus_one: null },
  financials: {
    most_recent_year: null,
    revenue: null,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Wage bill and balance sheet data not available from KNVB source",
  },
  historical: [],
  tm_squad_value_eur_m: 6.0,
  data_status: "PARTIAL",
  volatility_tier: "MEDIUM",
},
];

// ─── Belgium ─────────────────────────────────────────────────────────────────
const beClubs: EUClub[] = [
{
  slug: "club_brugge",
  name: "Club Brugge",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: "Listed on Euronext Brussels (~30% free float); Verhaeghe/Grisar consortium control", category: "Listed \u2014 public company", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 155.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 22.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 82.3, wage_bill: null, net_profit: 5.0 },
    { season: "2020/21", revenue: 88.0, wage_bill: null, net_profit: -9.8 },
    { season: "2021/22", revenue: 134.1, wage_bill: null, net_profit: 31.2 },
    { season: "2022/23", revenue: 112.0, wage_bill: null, net_profit: 10.0 },
    { season: "2023/24", revenue: 155.0, wage_bill: null, net_profit: 22.0 },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "anderlecht",
  name: "Anderlecht",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: "Marc Coucke \u2014 majority", category: "Private individual", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 70.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: -9.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 76.0, wage_bill: null, net_profit: -32.0 },
    { season: "2020/21", revenue: 58.0, wage_bill: null, net_profit: -35.7 },
    { season: "2021/22", revenue: 62.0, wage_bill: null, net_profit: -22.0 },
    { season: "2022/23", revenue: 53.0, wage_bill: null, net_profit: -27.0 },
    { season: "2023/24", revenue: 70.0, wage_bill: null, net_profit: -9.0 },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "royal_antwerp",
  name: "Royal Antwerp",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: "Paul Gheysens (Ghelamco) \u2014 majority", category: "Private family ownership", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 78.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 8.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 27.0, wage_bill: null, net_profit: -8.0 },
    { season: "2020/21", revenue: 32.0, wage_bill: null, net_profit: -6.0 },
    { season: "2021/22", revenue: 38.0, wage_bill: null, net_profit: -5.0 },
    { season: "2022/23", revenue: 52.0, wage_bill: null, net_profit: 2.0 },
    { season: "2023/24", revenue: 78.0, wage_bill: null, net_profit: 8.0 },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "krc_genk",
  name: "KRC Genk",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: null, category: null, fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 58.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 5.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 62.0, wage_bill: null, net_profit: 3.0 },
    { season: "2020/21", revenue: 48.0, wage_bill: null, net_profit: -8.0 },
    { season: "2021/22", revenue: 45.0, wage_bill: null, net_profit: -10.0 },
    { season: "2022/23", revenue: 54.0, wage_bill: null, net_profit: 8.0 },
    { season: "2023/24", revenue: 58.0, wage_bill: null, net_profit: 5.0 },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "standard_liege",
  name: "Standard Li\u00e8ge",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: "A-CAP (US insurer) \u2014 controlling stake since 2024 (exited 777 Partners)", category: "Private equity / institutional", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 40.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: -12.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 38.0, wage_bill: null, net_profit: -18.0 },
    { season: "2020/21", revenue: 34.0, wage_bill: null, net_profit: -22.0 },
    { season: "2021/22", revenue: 36.0, wage_bill: null, net_profit: -16.0 },
    { season: "2022/23", revenue: 38.0, wage_bill: null, net_profit: -14.0 },
    { season: "2023/24", revenue: 40.0, wage_bill: null, net_profit: -12.0 },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "kaa_gent",
  name: "KAA Gent",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: null, category: null, fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 50.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 2.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 42.0, wage_bill: null, net_profit: -4.0 },
    { season: "2020/21", revenue: 38.0, wage_bill: null, net_profit: -6.0 },
    { season: "2021/22", revenue: 44.0, wage_bill: null, net_profit: 1.0 },
    { season: "2022/23", revenue: 48.0, wage_bill: null, net_profit: 3.0 },
    { season: "2023/24", revenue: 50.0, wage_bill: null, net_profit: 2.0 },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "union_saint_gilloise",
  name: "Union Saint-Gilloise",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: "Tony Bloom (Brighton & Hove Albion chairman) \u2014 majority via RWDM", category: "Multi-Club Ownership (Brighton / Tony Bloom)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 45.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: 6.0,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 8.0, wage_bill: null, net_profit: -1.0 },
    { season: "2020/21", revenue: 10.0, wage_bill: null, net_profit: -0.5 },
    { season: "2021/22", revenue: 22.0, wage_bill: null, net_profit: 3.0 },
    { season: "2022/23", revenue: 38.0, wage_bill: null, net_profit: 5.0 },
    { season: "2023/24", revenue: 45.0, wage_bill: null, net_profit: 6.0 },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "oh_leuven",
  name: "OH Leuven",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: "King Power International (Thailand) \u2014 100% via Leicester parent", category: "Multi-Club Ownership (King Power / Thailand)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 22.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 12.0, wage_bill: null, net_profit: -4.0 },
    { season: "2020/21", revenue: 15.0, wage_bill: null, net_profit: -5.0 },
    { season: "2021/22", revenue: 18.0, wage_bill: null, net_profit: -4.0 },
    { season: "2022/23", revenue: 20.0, wage_bill: null, net_profit: -3.0 },
    { season: "2023/24", revenue: 22.0, wage_bill: null, net_profit: null },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "cercle_brugge",
  name: "Cercle Brugge",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: "AS Monaco (Dmitry Rybolovlev family) \u2014 majority", category: "Multi-Club Ownership (AS Monaco / Rybolovlev)", fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 16.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 9.0, wage_bill: null, net_profit: -2.0 },
    { season: "2020/21", revenue: 10.0, wage_bill: null, net_profit: -1.5 },
    { season: "2021/22", revenue: 12.0, wage_bill: null, net_profit: -1.0 },
    { season: "2022/23", revenue: 14.0, wage_bill: null, net_profit: 0.5 },
    { season: "2023/24", revenue: 16.0, wage_bill: null, net_profit: null },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
{
  slug: "charleroi",
  name: "Charleroi",
  country: "Belgium",
  league: "First Division A",
  city: null,
  currency: "EUR",
  stadium: null,
  ownership: { summary: null, category: null, fifty_plus_one: null },
  financials: {
    most_recent_year: "2023/24",
    revenue: 28.0,
    wage_bill: null,
    wage_to_revenue_pct: null,
    net_profit: null,
    total_liabilities: null,
    equity: null,
    data_notes: "Financial history available; stadium/ownership metadata pending enrichment",
  },
  historical: [
    { season: "2019/20", revenue: 22.0, wage_bill: null, net_profit: -3.0 },
    { season: "2020/21", revenue: 20.0, wage_bill: null, net_profit: -4.0 },
    { season: "2021/22", revenue: 24.0, wage_bill: null, net_profit: -2.0 },
    { season: "2022/23", revenue: 26.0, wage_bill: null, net_profit: -1.0 },
    { season: "2023/24", revenue: 28.0, wage_bill: null, net_profit: null },
  ],
  tm_squad_value_eur_m: null,
  data_status: "PARTIAL",
  volatility_tier: null,
},
];


export const euClubs: EUClub[] = [
  ...frClubs,
  ...dkClubs,
  ...noClubs,
  ...swClubs,
  ...itClubs,
  ...esClubs,
  ...deClubs,
  ...de2Clubs,
  ...atClubs,
  ...chClubs,
];

export function getEuClub(slug: string): EUClub | undefined {
  return euClubs.find((c) => c.slug === slug);
}

export const EU_COUNTRY_CONFIG: {
  country: EUCountry;
  flag: string;
  leagues: { key: string; label: string }[];
}[] = [
  {
    country: "France",
    flag: "🇫🇷",
    leagues: [
      { key: "Ligue 1", label: "Ligue 1" },
      { key: "Ligue 2", label: "Ligue 2" },
    ],
  },
  {
    country: "Denmark",
    flag: "🇩🇰",
    leagues: [
      { key: "Superliga", label: "Danish Superliga" },
      { key: "1. Division", label: "1. Division" },
    ],
  },
  {
    country: "Norway",
    flag: "🇳🇴",
    leagues: [
      { key: "norwegian-eliteserien", label: "Eliteserien" },
    ],
  },
  {
    country: "Sweden",
    flag: "🇸🇪",
    leagues: [
      { key: "Allsvenskan", label: "Allsvenskan" },
      { key: "Superettan", label: "Superettan" },
      { key: "Damallsvenskan", label: "Damallsvenskan" },
    ],
  },
  {
    country: "Italy",
    flag: "🇮🇹",
    leagues: [
      { key: "Serie A", label: "Serie A" },
      { key: "Serie B", label: "Serie B" },
    ],
  },
  {
    country: "Spain",
    flag: "🇪🇸",
    leagues: [
      { key: "La Liga", label: "La Liga" },
      { key: "La Liga 2", label: "La Liga 2" },
    ],
  },
  {
    country: "Germany",
    flag: "🇩🇪",
    leagues: [
      { key: "1. Bundesliga", label: "Bundesliga" },
      { key: "2. Bundesliga", label: "2. Bundesliga" },
    ],
  },
  {
    country: "Austria",
    flag: "🇦🇹",
    leagues: [
      { key: "Austrian Bundesliga", label: "Austrian Bundesliga" },
      { key: "Austrian 2. Liga", label: "Austrian 2. Liga" },
    ],
  },
  {
    country: "Switzerland",
    flag: "🇨🇭",
    leagues: [
      { key: "Super League", label: "Swiss Super League" },
    ],
  },
];