// Auto-generated: metro population matched to German & Austrian clubs
// Source: Metro Populations (EU) tab, DE_Football_DB_v0.8.xlsx

export interface EUMarketContext {
  metro_area: string;   // e.g. "Rhine-Ruhr shared metro"
  metro_pop_m: number;  // millions
  metro_note: string;   // definition note
}

export const euMarketContext: Record<string, EUMarketContext> = {
  "1_fc_heidenheim": { metro_area: "Heidenheim", metro_pop_m: 0.13, metro_note: "Heidenheim district" },
  "1_fc_kaiserslautern": { metro_area: "Kaiserslautern", metro_pop_m: 0.26, metro_note: "Kaiserslautern" },
  "1_fc_koeln": { metro_area: "Cologne-Bonn", metro_pop_m: 3.6, metro_note: "Cologne-Bonn" },
  "1_fc_magdeburg": { metro_area: "Magdeburg", metro_pop_m: 0.4, metro_note: "Magdeburg" },
  "1_fc_nuernberg": { metro_area: "Nuremberg", metro_pop_m: 3.6, metro_note: "Nuremberg metro" },
  "1_fc_saarbruecken": { metro_area: "Saarbrücken", metro_pop_m: 0.8, metro_note: "Saar region" },
  "1_fc_union_berlin": { metro_area: "Berlin", metro_pop_m: 6.1, metro_note: "Berlin-Brandenburg" },
  "1_fsv_mainz_05": { metro_area: "Rhine-Main", metro_pop_m: 2.8, metro_note: "Rhine-Main shared metro" },
  "admira_wacker": { metro_area: "Vienna", metro_pop_m: 2.9, metro_note: "Vienna metro (Maria Enzersdorf)" },
  "alemannia_aachen": { metro_area: "Aachen", metro_pop_m: 0.55, metro_note: "Aachen" },
  "ask_voitsberg": { metro_area: "Voitsberg", metro_pop_m: 0.04, metro_note: "Voitsberg" },
  "bayer_04_leverkusen": { metro_area: "Rhine-Ruhr", metro_pop_m: 5.1, metro_note: "Rhine-Ruhr shared metro" },
  "borussia_dortmund": { metro_area: "Rhine-Ruhr", metro_pop_m: 5.1, metro_note: "Rhine-Ruhr shared metro" },
  "borussia_dortmund_ii": { metro_area: "Rhine-Ruhr", metro_pop_m: 5.1, metro_note: "Rhine-Ruhr shared metro" },
  "borussia_moenchengladbach": { metro_area: "Mönchengladbach", metro_pop_m: 0.45, metro_note: "Gladbach urban area" },
  "dsc_arminia_bielefeld": { metro_area: "Bielefeld", metro_pop_m: 0.34, metro_note: "Bielefeld" },
  "eintracht_braunschweig": { metro_area: "Braunschweig", metro_pop_m: 1.0, metro_note: "Braunschweig region" },
  "eintracht_frankfurt": { metro_area: "Rhine-Main", metro_pop_m: 2.8, metro_note: "Rhine-Main shared metro" },
  "fc_augsburg": { metro_area: "Augsburg", metro_pop_m: 0.9, metro_note: "Augsburg region" },
  "fc_bayern_muenchen": { metro_area: "Munich", metro_pop_m: 2.9, metro_note: "Munich metro region" },
  "fc_blau_weiss_linz": { metro_area: "Linz", metro_pop_m: 0.79, metro_note: "Linz-Wels" },
  "fc_energie_cottbus": { metro_area: "Cottbus", metro_pop_m: 0.2, metro_note: "Cottbus" },
  "fc_erzgebirge_aue": { metro_area: "Erzgebirge", metro_pop_m: 0.08, metro_note: "Erzgebirge (Aue)" },
  "fc_hansa_rostock": { metro_area: "Rostock", metro_pop_m: 0.42, metro_note: "Rostock" },
  "fc_ingolstadt_04": { metro_area: "Ingolstadt", metro_pop_m: 0.25, metro_note: "Ingolstadt" },
  "fc_liefering": { metro_area: "Salzburg", metro_pop_m: 0.39, metro_note: "Salzburg metro" },
  "fc_red_bull_salzburg": { metro_area: "Salzburg", metro_pop_m: 0.39, metro_note: "Salzburg metro" },
  "fc_schalke_04": { metro_area: "Rhine-Ruhr", metro_pop_m: 5.1, metro_note: "Rhine-Ruhr shared metro (Gelsenkirchen)" },
  "fc_st_pauli": { metro_area: "Hamburg", metro_pop_m: 5.4, metro_note: "Hamburg metro" },
  "fc_viktoria_koeln": { metro_area: "Cologne-Bonn", metro_pop_m: 3.6, metro_note: "Cologne-Bonn" },
  "first_vienna_fc": { metro_area: "Vienna", metro_pop_m: 2.9, metro_note: "Vienna metropolitan" },
  "fk_austria_wien": { metro_area: "Vienna", metro_pop_m: 2.9, metro_note: "Vienna metropolitan" },
  "floridsdorfer_ac": { metro_area: "Vienna", metro_pop_m: 2.9, metro_note: "Vienna metropolitan (Floridsdorf)" },
  "fortuna_duesseldorf": { metro_area: "Rhine-Ruhr", metro_pop_m: 5.1, metro_note: "Rhine-Ruhr shared metro" },
  "grazer_ak": { metro_area: "Graz", metro_pop_m: 0.44, metro_note: "Graz" },
  "hamburger_sv": { metro_area: "Hamburg", metro_pop_m: 5.4, metro_note: "Hamburg metro" },
  "hannover_96": { metro_area: "Hannover", metro_pop_m: 1.15, metro_note: "Hannover region" },
  "hannover_96_ii": { metro_area: "Hannover", metro_pop_m: 1.15, metro_note: "Hannover region" },
  "hertha_bsc": { metro_area: "Berlin", metro_pop_m: 6.1, metro_note: "Berlin-Brandenburg" },
  "holstein_kiel": { metro_area: "Kiel", metro_pop_m: 0.65, metro_note: "Kiel region" },
  "karlsruher_sc": { metro_area: "Karlsruhe", metro_pop_m: 1.0, metro_note: "Karlsruhe metro" },
  "lask": { metro_area: "Linz", metro_pop_m: 0.79, metro_note: "Linz-Wels" },
  "rb_leipzig": { metro_area: "Leipzig", metro_pop_m: 1.1, metro_note: "Leipzig metro" },
  "rot_weiss_essen": { metro_area: "Rhine-Ruhr", metro_pop_m: 5.1, metro_note: "Rhine-Ruhr shared metro" },
  "sc_austria_lustenau": { metro_area: "Rheintal", metro_pop_m: 0.4, metro_note: "Rheintal shared (Lustenau)" },
  "sc_freiburg": { metro_area: "Freiburg", metro_pop_m: 0.66, metro_note: "Freiburg metro" },
  "sc_paderborn_07": { metro_area: "Paderborn", metro_pop_m: 0.31, metro_note: "Paderborn" },
  "sc_preussen_muenster": { metro_area: "Münster", metro_pop_m: 0.32, metro_note: "Münster" },
  "sc_verl": { metro_area: "Verl", metro_pop_m: 0.03, metro_note: "Verl" },
  "schwarz_weiss_bregenz": { metro_area: "Rheintal", metro_pop_m: 0.4, metro_note: "Rheintal shared (Bregenz)" },
  "scr_altach": { metro_area: "Rheintal", metro_pop_m: 0.4, metro_note: "Rheintal shared (Altach)" },
  "sg_dynamo_dresden": { metro_area: "Dresden", metro_pop_m: 0.8, metro_note: "Dresden" },
  "sk_austria_klagenfurt": { metro_area: "Klagenfurt", metro_pop_m: 0.19, metro_note: "Klagenfurt" },
  "sk_rapid_wien": { metro_area: "Vienna", metro_pop_m: 2.9, metro_note: "Vienna metropolitan" },
  "sk_rapid_wien_ii": { metro_area: "Vienna", metro_pop_m: 2.9, metro_note: "Vienna metropolitan" },
  "sk_sturm_graz": { metro_area: "Graz", metro_pop_m: 0.44, metro_note: "Graz" },
  "sk_sturm_graz_ii": { metro_area: "Graz", metro_pop_m: 0.44, metro_note: "Graz" },
  "skn_st_poelten": { metro_area: "St. Pölten", metro_pop_m: 0.1, metro_note: "St. Pölten" },
  "sku_amstetten": { metro_area: "Amstetten", metro_pop_m: 0.05, metro_note: "Amstetten" },
  "spvgg_greuther_fuerth": { metro_area: "Nuremberg", metro_pop_m: 3.6, metro_note: "Nuremberg metro shared" },
  "spvgg_unterhaching": { metro_area: "Munich", metro_pop_m: 2.9, metro_note: "Munich metro suburb" },
  "ssv_jahn_regensburg": { metro_area: "Regensburg", metro_pop_m: 0.34, metro_note: "Regensburg" },
  "ssv_ulm_1846": { metro_area: "Ulm", metro_pop_m: 0.52, metro_note: "Ulm metro" },
  "sv_darmstadt_98": { metro_area: "Rhine-Main", metro_pop_m: 2.8, metro_note: "Rhine-Main shared metro" },
  "sv_elversberg": { metro_area: "Saar adjacent", metro_pop_m: 0.14, metro_note: "Saar adjacent (Spiesen-Elversberg)" },
  "sv_horn": { metro_area: "Horn", metro_pop_m: 0.04, metro_note: "Horn" },
  "sv_kapfenberg": { metro_area: "Kapfenberg", metro_pop_m: 0.06, metro_note: "Kapfenberg" },
  "sv_lafnitz": { metro_area: "Lafnitz", metro_pop_m: 0.01, metro_note: "Lafnitz" },
  "sv_ried": { metro_area: "Ried", metro_pop_m: 0.06, metro_note: "Ried im Innkreis" },
  "sv_sandhausen": { metro_area: "Rhine-Neckar", metro_pop_m: 2.4, metro_note: "Rhine-Neckar" },
  "sv_stripfing": { metro_area: "Marchfeld", metro_pop_m: 0.02, metro_note: "Marchfeld (Stripfing)" },
  "sv_waldhof_mannheim": { metro_area: "Rhine-Neckar", metro_pop_m: 2.4, metro_note: "Rhine-Neckar" },
  "sv_wehen_wiesbaden": { metro_area: "Rhine-Main", metro_pop_m: 2.8, metro_note: "Rhine-Main shared metro" },
  "sv_werder_bremen": { metro_area: "Bremen", metro_pop_m: 1.25, metro_note: "Bremen-Oldenburg" },
  "tsg_1899_hoffenheim": { metro_area: "Sinsheim", metro_pop_m: 0.12, metro_note: "Rhein-Neckar adjacent" },
  "tsv_1860_muenchen": { metro_area: "Munich", metro_pop_m: 2.9, metro_note: "Munich metro region" },
  "tsv_hartberg": { metro_area: "Hartberg", metro_pop_m: 0.02, metro_note: "Hartberg" },
  "vfb_stuttgart": { metro_area: "Stuttgart", metro_pop_m: 2.8, metro_note: "Stuttgart metro" },
  "vfb_stuttgart_ii": { metro_area: "Stuttgart", metro_pop_m: 2.8, metro_note: "Stuttgart metro" },
  "vfl_bochum": { metro_area: "Rhine-Ruhr", metro_pop_m: 5.1, metro_note: "Rhine-Ruhr shared metro" },
  "vfl_osnabrueck": { metro_area: "Osnabrück", metro_pop_m: 0.27, metro_note: "Osnabrück" },
  "vfl_wolfsburg": { metro_area: "Wolfsburg", metro_pop_m: 0.22, metro_note: "Wolfsburg-Gifhorn" },
  "wolfsberger_ac": { metro_area: "Wolfsberg", metro_pop_m: 0.05, metro_note: "Wolfsberg" },
  "wsg_tirol": { metro_area: "Innsbruck", metro_pop_m: 0.31, metro_note: "Innsbruck" },
};
