// AUTO-GENERATED by generate_fixed_assets_ts.py — do not edit manually.

export type OwnershipStatus = "owned" | "leased";

export interface StadiumData {
  stadium_name: string;
  capacity: number | null;
  ownership: OwnershipStatus | null;
  /** Who owns the freehold if leased, or null for club-owned */
  ownership_detail: string | null;
  /** Narrative note for leasehold situations */
  leasehold_notes: string | null;
}

export interface TrainingGroundData {
  ownership: OwnershipStatus | null;
  notes: string | null;
}

export interface ClubAssets {
  stadium: StadiumData;
  training_ground: TrainingGroundData | null;
}

export const fixedAssets: Record<string, ClubAssets> = {

  // Premier League
  arsenal: {
    stadium: { stadium_name: "Emirates Stadium", capacity: 60704, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "aston-villa": {
    stadium: { stadium_name: "Villa Park", capacity: 42918, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "Purchased in 2018" },
  },
  bournemouth: {
    stadium: { stadium_name: "Vitality Stadium", capacity: 11307, ownership: "leased", ownership_detail: "Structadene Ltd (property company)", leasehold_notes: "Club sold the freehold in 2005 to property company Structadene for £3.5m. The club pays approximately £300k/year in rent and has sought to repurchase the freehold." },
    training_ground: { ownership: "owned", notes: "New £32m facility built 2025" },
  },
  brentford: {
    stadium: { stadium_name: "Gtech Community Stadium", capacity: 17250, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  brighton: {
    stadium: { stadium_name: "Amex Stadium", capacity: 31876, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  burnley: {
    stadium: { stadium_name: "Turf Moor", capacity: 21944, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  chelsea: {
    stadium: { stadium_name: "Stamford Bridge", capacity: 40173, ownership: "leased", ownership_detail: "Chelsea Pitch Owners (non-profit supporter organisation)", leasehold_notes: "Freehold owned by Chelsea Pitch Owners (fan trust). Club must continue to play at Stamford Bridge or forfeit the right to use the Chelsea FC name." },
    training_ground: { ownership: "owned", notes: "Owned by BlueCo - transferrred in 2022 to help PSR" },
  },
  "crystal-palace": {
    stadium: { stadium_name: "Selhurst Park", capacity: 26255, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "Purchased 2013 for £2.3m" },
  },
  everton: {
    stadium: { stadium_name: "Hill Dickinson Stadium", capacity: 52769, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Owned by Liverpool City Council - 40 year lease from 2013" },
  },
  fulham: {
    stadium: { stadium_name: "Craven Cottage", capacity: 25700, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "Expected expansion of training ground" },
  },
  leeds: {
    stadium: { stadium_name: "Elland Road", capacity: 37890, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Freehold sold in 2004, leased back" },
  },
  liverpool: {
    stadium: { stadium_name: "Anfield", capacity: 61276, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "man-city": {
    stadium: { stadium_name: "Etihad Stadium", capacity: 55097, ownership: "leased", ownership_detail: "Manchester City Council", leasehold_notes: "250-year lease from Manchester City Council at approximately £4m/year. Freehold remains with the council." },
    training_ground: { ownership: "owned", notes: null },
  },
  "man-united": {
    stadium: { stadium_name: "Old Trafford", capacity: 74140, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  newcastle: {
    stadium: { stadium_name: "St James' Park", capacity: 52409, ownership: "leased", ownership_detail: "PZ Holdings Ltd (PIF / Reuben Brothers)", leasehold_notes: "Stadium sold to sister company PZ Holdings in 2024/25 for £172m to generate a PSR accounting profit. The club now leases back the ground from its own owners." },
    training_ground: { ownership: "owned", notes: "New £200m facility planned at Wollsington" },
  },
  "nottm-forest": {
    stadium: { stadium_name: "City Ground", capacity: 30404, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  sunderland: {
    stadium: { stadium_name: "Stadium of Light", capacity: 49000, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  tottenham: {
    stadium: { stadium_name: "Tottenham Hotspur Stadium", capacity: 62303, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "west-ham": {
    stadium: { stadium_name: "London Stadium", capacity: 62500, ownership: "leased", ownership_detail: "London Stadium LLP (Greater London Authority)", leasehold_notes: "Club holds a 99-year lease from the Greater London Authority. Does not benefit from naming rights revenue or non-football events at the stadium." },
    training_ground: { ownership: "owned", notes: null },
  },
  wolves: {
    stadium: { stadium_name: "Molineux Stadium", capacity: 31700, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },

  // Championship
  birmingham: {
    stadium: { stadium_name: "St Andrew's", capacity: 29409, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  blackburn: {
    stadium: { stadium_name: "Ewood Park", capacity: 31367, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "Sold to Venky portfolio company in 2021 to comply with EFL reg rules" },
  },
  "bristol-city": {
    stadium: { stadium_name: "Ashton Gate", capacity: 27000, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  charlton: {
    stadium: { stadium_name: "The Valley", capacity: 27111, ownership: "leased", ownership_detail: "Roland Duchâtelet (former owner)", leasehold_notes: "Freehold owned by former owner Roland Duchâtelet following his sale of the club in 2019. The club leases the ground from its former owner." },
    training_ground: { ownership: "leased", notes: "Freehold owned by former owner Roland Duchatelet" },
  },
  coventry: {
    stadium: { stadium_name: "CBS Arena", capacity: 32609, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  derby: {
    stadium: { stadium_name: "Pride Park", capacity: 30000, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  hull: {
    stadium: { stadium_name: "KC Stadium", capacity: 25586, ownership: "leased", ownership_detail: "Hull City Council", leasehold_notes: "Leased from Hull City Council. Club has sought to purchase the freehold but negotiations have stalled." },
    training_ground: { ownership: "owned", notes: null },
  },
  ipswich: {
    stadium: { stadium_name: "Portman Road", capacity: 29813, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  leicester: {
    stadium: { stadium_name: "King Power Stadium", capacity: 32259, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  middlesbrough: {
    stadium: { stadium_name: "Riverside Stadium", capacity: 33746, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  millwall: {
    stadium: { stadium_name: "The Den", capacity: 20146, ownership: "leased", ownership_detail: "Owned by Lewisham Council; 999 year lease", leasehold_notes: "999-year lease from Lewisham Council. Effectively permanent but freehold remains with the council." },
    training_ground: { ownership: "owned", notes: "Purchased in Feb 2025" },
  },
  norwich: {
    stadium: { stadium_name: "Carrow Road", capacity: 27150, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "oxford-utd": {
    stadium: { stadium_name: "The Kassam Stadium", capacity: 12500, ownership: "leased", ownership_detail: "Owned by Firoka Group - new stadium anticipated in 2026", leasehold_notes: "Kassam Stadium leased from the Firoka Group. A new 16,000-seat stadium at Stratfield Brake is anticipated for 2026–27." },
    training_ground: { ownership: "leased", notes: "23 year lease signed in 2019" },
  },
  portsmouth: {
    stadium: { stadium_name: "Fratton Park", capacity: 20867, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  preston: {
    stadium: { stadium_name: "Deepdale", capacity: 23404, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  qpr: {
    stadium: { stadium_name: "Loftus Road", capacity: 18439, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "sheff-utd": {
    stadium: { stadium_name: "Bramall Lane", capacity: 32050, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "New training ground planned at Dore site, purchased in March 2024" },
  },
  "sheff-wed": {
    stadium: { stadium_name: "Hillsborough", capacity: 34835, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  southampton: {
    stadium: { stadium_name: "St Mary's Stadium", capacity: 32384, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  stoke: {
    stadium: { stadium_name: "Bet365", capacity: 30089, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "Transferred to club in 2025 re-org" },
  },
  swansea: {
    stadium: { stadium_name: "Swansea.com Stadium", capacity: 21088, ownership: "leased", ownership_detail: "37 year lease in 2018 from council", leasehold_notes: "37-year lease with Swansea Council signed in 2018. The council retains the freehold." },
    training_ground: { ownership: "leased", notes: "Owned by Swansea Univeristy" },
  },
  watford: {
    stadium: { stadium_name: "Vicarage Road", capacity: 22220, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "west-brom": {
    stadium: { stadium_name: "Hawthorns", capacity: 26850, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  wrexham: {
    stadium: { stadium_name: "Stok Cae Ras", capacity: 12600, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Freehold owned by Welsh FA" },
  },

  // League One
  "afc-wimbledon": {
    stadium: { stadium_name: "Plough Lane", capacity: 9215, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Owned by KCL University" },
  },
  barnsley: {
    stadium: { stadium_name: "Oakwell Stadium", capacity: 23287, ownership: "leased", ownership_detail: "30 year lease in 2023", leasehold_notes: "30-year lease signed with the council in 2023. Previous freehold arrangement lapsed when the club entered administration." },
    training_ground: { ownership: "leased", notes: "30 year lease from council agreed in 2024" },
  },
  blackpool: {
    stadium: { stadium_name: "Bloomfield Road", capacity: 17338, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "New 87 acre site acquired for new training ground - full planning approval granted" },
  },
  bolton: {
    stadium: { stadium_name: "Toughsheet Community Stadium", capacity: 28723, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: "Moved to new site in 2018" },
  },
  bradford: {
    stadium: { stadium_name: "Valley Parade", capacity: 24840, ownership: "leased", ownership_detail: "Lease until 2028 from former owner", leasehold_notes: "Lease from former owner Omar Khan's associated company, running until 2028." },
    training_ground: { ownership: "leased", notes: "Rent facilities from Woodhouse Grove School" },
  },
  burton: {
    stadium: { stadium_name: "Pirelli Stadium Princess Way", capacity: 6912, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Uses St George's Park training facilities" },
  },
  cardiff: {
    stadium: { stadium_name: "Cardiff City Stadium", capacity: 33316, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "New training ground currently under construction" },
  },
  exeter: {
    stadium: { stadium_name: "St James Park", capacity: 8720, ownership: "leased", ownership_detail: "25 year lease from council in 2020", leasehold_notes: "25-year lease from Exeter City Council (signed 2020)." },
    training_ground: { ownership: "owned", notes: "Purchased in 2018; recent £3.5m redevelopment" },
  },
  huddersfield: {
    stadium: { stadium_name: "Accu Stadium", capacity: 24121, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Leased from local council" },
  },
  "leyton-orient": {
    stadium: { stadium_name: "Brisbane Road", capacity: 9271, ownership: "leased", ownership_detail: "Owned by former owners (Matchroom);  20 year lease in 2023", leasehold_notes: "20-year lease signed in 2023 with Barry Hearn's Matchroom, who retained the freehold following their period of ownership." },
    training_ground: { ownership: "leased", notes: "Leased from Chigwell School" },
  },
  lincoln: {
    stadium: { stadium_name: "Sincil Bank", capacity: 10121, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  luton: {
    stadium: { stadium_name: "Kenilworth Road", capacity: 11500, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Contains option to purchase freehold" },
  },
  mansfield: {
    stadium: { stadium_name: "Field Mill", capacity: 10022, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  northampton: {
    stadium: { stadium_name: "Sixfields Stadium", capacity: 8200, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Leased from Moulton College" },
  },
  peterborough: {
    stadium: { stadium_name: "London Road", capacity: 15314, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "25 year lease signed in Feb 2021" },
  },
  plymouth: {
    stadium: { stadium_name: "Home Park", capacity: 17000, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "port-vale": {
    stadium: { stadium_name: "Vale Park", capacity: 16800, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  reading: {
    stadium: { stadium_name: "Select Car Leasing Stadium", capacity: 24161, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  rotherham: {
    stadium: { stadium_name: "New York Stadium", capacity: 12000, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Leased from Tata Steel" },
  },
  stevenage: {
    stadium: { stadium_name: "Lamex Stadium", capacity: 7318, ownership: "leased", ownership_detail: "leased from the council, long term lease", leasehold_notes: "Long-term lease from Stevenage Borough Council." },
    training_ground: { ownership: "owned", notes: null },
  },
  wigan: {
    stadium: { stadium_name: "Brick Community Stadium", capacity: 25138, ownership: "leased", ownership_detail: "Owned by Mike Danson (current owner)", leasehold_notes: "Stadium owned by Mike Danson, the current club owner, who purchased it as part of his acquisition. Club leases it back from him." },
    training_ground: { ownership: "owned", notes: null },
  },

  // League Two
  accrington: {
    stadium: { stadium_name: "Wham Stadium", capacity: 5450, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Long term lease with council signed 2021" },
  },
  barnet: {
    stadium: { stadium_name: "The Hive", capacity: 6500, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  barrow: {
    stadium: { stadium_name: "Holker Street", capacity: 6500, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Lease from FC United" },
  },
  cambridge: {
    stadium: { stadium_name: "Cledara Abbey Stadium", capacity: 7937, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Long term lease from Clare College" },
  },
  chesterfield: {
    stadium: { stadium_name: "SMH Group Stadium", capacity: 10292, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: null },
  },
  colchester: {
    stadium: { stadium_name: "JobServe Community Stadium", capacity: 10105, ownership: "leased", ownership_detail: "Leased from local council", leasehold_notes: "Leased from Colchester Borough Council." },
    training_ground: { ownership: "leased", notes: null },
  },
  crawley: {
    stadium: { stadium_name: "Broadfield Stadium", capacity: 5567, ownership: "leased", ownership_detail: "Leased from local council", leasehold_notes: "Leased from Crawley Borough Council." },
    training_ground: { ownership: "leased", notes: "Lease from University of Sussex" },
  },
  fleetwood: {
    stadium: { stadium_name: "Highbury Stadium", capacity: 5327, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  gillingham: {
    stadium: { stadium_name: "Priestfield Stadium", capacity: 11582, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  grimsby: {
    stadium: { stadium_name: "Blundell Park", capacity: 9546, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  "mk-dons": {
    stadium: { stadium_name: "Stadium MK", capacity: 30500, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "25 year lease from the council" },
  },
  newport: {
    stadium: { stadium_name: "Rodney Parade", capacity: 8700, ownership: "leased", ownership_detail: "10 year deal in early 2025", leasehold_notes: "New 10-year deal agreed in early 2025." },
    training_ground: { ownership: "leased", notes: "Leased from University of South Wales" },
  },
  "notts-county": {
    stadium: { stadium_name: "Meadow Lane", capacity: 19841, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "Joint venture with university" },
  },
  oldham: {
    stadium: { stadium_name: "Boundary Park", capacity: 13500, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  salford: {
    stadium: { stadium_name: "Peninsula Stadium", capacity: 5108, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: null },
  },
  shrewsbury: {
    stadium: { stadium_name: "Croud Meadow", capacity: 9875, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  swindon: {
    stadium: { stadium_name: "County Ground", capacity: 14753, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "leased", notes: "250 year lease with the council" },
  },
  tranmere: {
    stadium: { stadium_name: "Prenton Park", capacity: 16587, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
  walsall: {
    stadium: { stadium_name: "Bescot Stadium", capacity: 11300, ownership: "owned", ownership_detail: null, leasehold_notes: null },
    training_ground: { ownership: "owned", notes: null },
  },
};
