export type OwnershipStatus = "owned" | "leased";

export interface StadiumData {
  stadium_name: string;
  capacity: number | null;
  ownership: OwnershipStatus | null;
  notes: string | null;
}

export const fixedAssets: Record<string, StadiumData> = {
  // Premier League
  arsenal:        { stadium_name: "Emirates Stadium",             capacity: 60704, ownership: "owned",  notes: null },
  aston_villa:    { stadium_name: "Villa Park",                   capacity: 42918, ownership: "owned",  notes: null },
  bournemouth:    { stadium_name: "Vitality Stadium",             capacity: 11307, ownership: "owned",  notes: null },
  brentford:      { stadium_name: "Gtech Community Stadium",      capacity: 17250, ownership: "owned",  notes: null },
  brighton:       { stadium_name: "Amex Stadium",                 capacity: 31876, ownership: "owned",  notes: null },
  burnley:        { stadium_name: "Turf Moor",                    capacity: 21944, ownership: "owned",  notes: null },
  chelsea:        { stadium_name: "Stamford Bridge",              capacity: 40173, ownership: "leased", notes: "Chelsea Pitch Owners (non-profit supporter organisation)" },
  crystal_palace: { stadium_name: "Selhurst Park",                capacity: 26255, ownership: "owned",  notes: null },
  everton:        { stadium_name: "Hill Dickinson Stadium",       capacity: 52769, ownership: "owned",  notes: null },
  fulham:         { stadium_name: "Craven Cottage",               capacity: 25700, ownership: "owned",  notes: null },
  leeds:          { stadium_name: "Elland Road",                  capacity: 37890, ownership: "owned",  notes: null },
  liverpool:      { stadium_name: "Anfield",                      capacity: 61276, ownership: "owned",  notes: null },
  man_city:       { stadium_name: "Etihad Stadium",               capacity: 55097, ownership: "leased", notes: "Manchester City Council" },
  man_united:     { stadium_name: "Old Trafford",                 capacity: 74140, ownership: "owned",  notes: null },
  newcastle:      { stadium_name: "St James' Park",               capacity: 52409, ownership: "leased", notes: "PZ Holdings Ltd (PIF / Reuben Brothers)" },
  nottm_forest:   { stadium_name: "City Ground",                  capacity: 30404, ownership: "owned",  notes: null },
  sunderland:     { stadium_name: "Stadium of Light",             capacity: 49000, ownership: "owned",  notes: null },
  tottenham:      { stadium_name: "Tottenham Hotspur Stadium",    capacity: 62303, ownership: "owned",  notes: null },
  west_ham:       { stadium_name: "London Stadium",               capacity: 62500, ownership: "leased", notes: "London Stadium LLP (Greater London Authority)" },
  wolves:         { stadium_name: "Molineux Stadium",             capacity: 31700, ownership: "owned",  notes: null },

  // Championship
  birmingham:     { stadium_name: "St Andrew's",                  capacity: 29409, ownership: "owned",  notes: null },
  blackburn:      { stadium_name: "Ewood Park",                   capacity: 31367, ownership: "owned",  notes: null },
  bristol_city:   { stadium_name: "Ashton Gate",                  capacity: 27000, ownership: "owned",  notes: null },
  charlton:       { stadium_name: "The Valley",                   capacity: 27111, ownership: "leased", notes: "Roland Duchâtelet (former owner)" },
  coventry:       { stadium_name: "CBS Arena",                    capacity: 32609, ownership: "owned",  notes: null },
  derby:          { stadium_name: "Pride Park",                   capacity: 30000, ownership: "owned",  notes: null },
  hull:           { stadium_name: "MKM Stadium",                  capacity: 25586, ownership: "leased", notes: "Hull City Council" },
  ipswich:        { stadium_name: "Portman Road",                 capacity: 29813, ownership: "owned",  notes: null },
  leicester:      { stadium_name: "King Power Stadium",           capacity: 32259, ownership: "owned",  notes: null },
  middlesbrough:  { stadium_name: "Riverside Stadium",            capacity: 33746, ownership: "owned",  notes: null },
  millwall:       { stadium_name: "The Den",                      capacity: 20146, ownership: "leased", notes: "Owned by Lewisham Council; 999-year lease" },
  norwich:        { stadium_name: "Carrow Road",                  capacity: 27150, ownership: "owned",  notes: null },
  oxford_utd:     { stadium_name: "The Kassam Stadium",           capacity: 12500, ownership: "leased", notes: "Owned by Firoka Group — new stadium anticipated in 2026" },
  portsmouth:     { stadium_name: "Fratton Park",                 capacity: 20867, ownership: "owned",  notes: null },
  preston:        { stadium_name: "Deepdale",                     capacity: 23404, ownership: "owned",  notes: null },
  qpr:            { stadium_name: "Loftus Road",                  capacity: 18439, ownership: "owned",  notes: null },
  sheff_utd:      { stadium_name: "Bramall Lane",                 capacity: 32050, ownership: "owned",  notes: null },
  sheff_wed:      { stadium_name: "Hillsborough",                 capacity: 34835, ownership: "owned",  notes: null },
  southampton:    { stadium_name: "St Mary's Stadium",            capacity: 32384, ownership: "owned",  notes: null },
  stoke:          { stadium_name: "bet365 Stadium",               capacity: 30089, ownership: "owned",  notes: null },
  swansea:        { stadium_name: "Swansea.com Stadium",          capacity: 21088, ownership: "leased", notes: "37-year lease from council (signed 2018)" },
  watford:        { stadium_name: "Vicarage Road",                capacity: 22220, ownership: "owned",  notes: null },
  west_brom:      { stadium_name: "The Hawthorns",                capacity: 26850, ownership: "owned",  notes: null },
  wrexham:        { stadium_name: "Stok Cae Ras",                 capacity: 12600, ownership: "owned",  notes: null },

  // League One
  afc_wimbledon:  { stadium_name: "Plough Lane",                  capacity: 9215,  ownership: "owned",  notes: null },
  barnsley:       { stadium_name: "Oakwell Stadium",              capacity: 23287, ownership: "leased", notes: "30-year lease (signed 2023)" },
  blackpool:      { stadium_name: "Bloomfield Road",              capacity: 17338, ownership: "owned",  notes: null },
  bolton:         { stadium_name: "Toughsheet Community Stadium", capacity: 28723, ownership: "owned",  notes: null },
  bradford:       { stadium_name: "Valley Parade",                capacity: 24840, ownership: "leased", notes: "Lease until 2028 from former owner" },
  burton:         { stadium_name: "Pirelli Stadium",              capacity: 6912,  ownership: "owned",  notes: null },
  cardiff:        { stadium_name: "Cardiff City Stadium",         capacity: 33316, ownership: "owned",  notes: null },
  doncaster:      { stadium_name: "Eco-Power Stadium",            capacity: 15231, ownership: "leased", notes: "99-year lease from Council (2012)" },
  exeter:         { stadium_name: "St James Park",                capacity: 8720,  ownership: "leased", notes: "25-year lease from council (2020)" },
  huddersfield:   { stadium_name: "Accu Stadium",                 capacity: 24121, ownership: "owned",  notes: null },
  leyton_orient:  { stadium_name: "Brisbane Road",                capacity: 9271,  ownership: "leased", notes: "Owned by former owners (Matchroom); 20-year lease (2023)" },
  lincoln:        { stadium_name: "Sincil Bank",                  capacity: 10121, ownership: "owned",  notes: null },
  luton:          { stadium_name: "Kenilworth Road",              capacity: 11500, ownership: "owned",  notes: null },
  mansfield:      { stadium_name: "Field Mill",                   capacity: 10022, ownership: "owned",  notes: null },
  northampton:    { stadium_name: "Sixfields Stadium",            capacity: 8200,  ownership: "owned",  notes: null },
  peterborough:   { stadium_name: "London Road",                  capacity: 15314, ownership: "owned",  notes: null },
  plymouth:       { stadium_name: "Home Park",                    capacity: 17000, ownership: "owned",  notes: null },
  port_vale:      { stadium_name: "Vale Park",                    capacity: 16800, ownership: "owned",  notes: null },
  reading:        { stadium_name: "Select Car Leasing Stadium",   capacity: 24161, ownership: "owned",  notes: null },
  rotherham:      { stadium_name: "New York Stadium",             capacity: 12000, ownership: "owned",  notes: null },
  stevenage:      { stadium_name: "Lamex Stadium",                capacity: 7318,  ownership: "leased", notes: "Long-term lease from council" },
  stockport:      { stadium_name: "Edgeley Park",                 capacity: 10582, ownership: "leased", notes: "250-year lease with council (signed 2022)" },
  wigan:          { stadium_name: "Brick Community Stadium",      capacity: 25138, ownership: "leased", notes: "Owned by Mike Danson (current owner)" },
  wycombe:        { stadium_name: "Adams Park",                   capacity: 10446, ownership: "leased", notes: "Owned by fan trust; 50-year lease" },

  // League Two
  accrington:     { stadium_name: "Wham Stadium",                 capacity: 5450,  ownership: "owned",  notes: null },
  barnet:         { stadium_name: "The Hive",                     capacity: 6500,  ownership: "owned",  notes: null },
  barrow:         { stadium_name: "Holker Street",                capacity: 6500,  ownership: "owned",  notes: null },
  bristol_rovers: { stadium_name: "Memorial Stadium",             capacity: 12300, ownership: "owned",  notes: null },
  bromley:        { stadium_name: "Hayes Lane",                   capacity: 6100,  ownership: "owned",  notes: null },
  cambridge:      { stadium_name: "Cledara Abbey Stadium",        capacity: 7937,  ownership: "owned",  notes: null },
  cheltenham:     { stadium_name: "Jonny-Rocks Stadium",          capacity: 7066,  ownership: "leased", notes: "Leased from Cheltenham Borough Council" },
  chesterfield:   { stadium_name: "SMH Group Stadium",            capacity: 10292, ownership: "owned",  notes: null },
  colchester:     { stadium_name: "JobServe Community Stadium",   capacity: 10105, ownership: "leased", notes: "Leased from local council" },
  crawley:        { stadium_name: "Broadfield Stadium",           capacity: 5567,  ownership: "leased", notes: "Leased from local council" },
  crewe:          { stadium_name: "Gresty Road",                  capacity: 10153, ownership: "owned",  notes: null },
  fleetwood:      { stadium_name: "Highbury Stadium",             capacity: 5327,  ownership: "owned",  notes: null },
  gillingham:     { stadium_name: "Priestfield Stadium",          capacity: 11582, ownership: "owned",  notes: null },
  grimsby:        { stadium_name: "Blundell Park",                capacity: 9546,  ownership: "owned",  notes: null },
  harrogate:      { stadium_name: "Exercise Stadium",             capacity: 5000,  ownership: "owned",  notes: null },
  mk_dons:        { stadium_name: "Stadium MK",                   capacity: 30500, ownership: "owned",  notes: null },
  newport:        { stadium_name: "Rodney Parade",                capacity: 8700,  ownership: "leased", notes: "10-year deal (early 2025)" },
  notts_county:   { stadium_name: "Meadow Lane",                  capacity: 19841, ownership: "owned",  notes: null },
  oldham:         { stadium_name: "Boundary Park",                capacity: 13500, ownership: "owned",  notes: null },
  salford:        { stadium_name: "Peninsula Stadium",            capacity: 5108,  ownership: "owned",  notes: null },
  shrewsbury:     { stadium_name: "Croud Meadow",                 capacity: 9875,  ownership: "owned",  notes: null },
  swindon:        { stadium_name: "County Ground",                capacity: 14753, ownership: "owned",  notes: null },
  tranmere:       { stadium_name: "Prenton Park",                 capacity: 16587, ownership: "owned",  notes: null },
  walsall:        { stadium_name: "Bescot Stadium",               capacity: 11300, ownership: "owned",  notes: null },
};
