// Italian Serie A / Serie B clubs — values in EUR millions
// Source: Annual accounts (bilancio d'esercizio / bilancio consolidato) filed at CCIAA / club investor relations
// FY typically ends 30 June (football year) unless noted. December FY clubs marked "FY20XX (Dec)".
// Revenue = Valore della Produzione (includes gains on player sales)
// Wages  = Costo del personale
// Operating profit = Differenza tra Valore e Costi della Produzione (A−B / EBIT)
// Net debt = financial bank debt + bonds + SH loans − cash (trade payables, IFRS 16 lease liabilities excluded unless material)
// net_debt < 0 = net cash

import { EUClub } from "./euClubs";

export const itClubs: EUClub[] = [

  // ─── AC Milan ───────────────────────────────────────────────────────────────
  {
    slug: "ac-milan",
    name: "AC Milan",
    country: "Italy",
    league: "Serie A",
    city: "Milan",
    currency: "EUR",
    stadium: { name: "San Siro (Stadio Giuseppe Meazza)", capacity: 75923, ownership: "Shared with Inter Milan; municipality of Milan" },
    ownership: { summary: "RedBird Capital Partners (99%)", category: "AC Milan SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 494.5,
      wage_bill: 188.7,
      wage_to_revenue_pct: 38.2,
      net_profit: 3.0,
      total_liabilities: 515.9,
      equity: 199.4,
      operating_profit: 16.0,
      profit_from_player_sales: 55.9,
      pre_tax_profit: 9.8,
      net_debt: 92.6,
      data_notes: "Gruppo Milan consolidated (Italian GAAP / OIC). Revenue includes plusvalenze €55.9m (Reijnders → Man City €41.9m; Kalulu → Juventus €13.2m). All financial debt is factoring (€136.1m; no bonds or bank loans). Net financial position: factoring debt €136.1m less cash €28.0m and liquid financial assets €15.5m = €92.6m net debt. Player write-downs €19.7m in FY2025 (Bondo, Chukwueze, Musah et al). UEFA settlement for FY2022–24 met in full; accrued provisions released in FY2025. FY2022 wage bill not separately disclosed in comparative accounts.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 450.2,
      wage_bill: 182.7,
      wage_to_revenue_pct: 40.6,
      operating_profit: 13.2,
      profit_from_player_sales: 44.9,
      pre_tax_profit: 12.3,
      net_debt: 49.6,
      net_profit: 4.1,
      equity: 196.3,
    },
    historical: [
      {
        season: "FY2022/23",
        revenue: 404.5,
        wage_bill: 174.0,
        net_profit: 6.1,
        operating_profit: 14.9,
        pre_tax_profit: 13.5,
        net_debt: -10.8,
        equity: 177.2,
      },
      {
        season: "FY2023/24",
        revenue: 450.2,
        wage_bill: 182.7,
        net_profit: 4.1,
        operating_profit: 13.2,
        pre_tax_profit: 12.3,
        net_debt: 49.6,
        equity: 196.3,
      },
      {
        season: "FY2024/25",
        revenue: 494.5,
        wage_bill: 188.7,
        net_profit: 3.0,
        operating_profit: 16.0,
        pre_tax_profit: 9.8,
        net_debt: 92.6,
        equity: 199.4,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Inter Milan ────────────────────────────────────────────────────────────
  {
    slug: "inter-milan",
    name: "Inter Milan",
    country: "Italy",
    league: "Serie A",
    city: "Milan",
    currency: "EUR",
    stadium: { name: "San Siro (Stadio Giuseppe Meazza)", capacity: 75923, ownership: "Shared with AC Milan; municipality of Milan" },
    ownership: { summary: "Oaktree Capital Management (majority, acquired Jun 2024)", category: "F.C. Internazionale Milano SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 473.2,
      wage_bill: 227.4,
      wage_to_revenue_pct: 48.1,
      net_profit: -35.7,
      total_liabilities: null,
      equity: null,
      operating_profit: 8.9,
      profit_from_player_sales: null,
      pre_tax_profit: -26.6,
      net_debt: 326.4,
      data_notes: "Net debt includes €392.2m bonds and €34.3m shareholder loans, less cash €115.1m. FY2024/25 accounts not yet filed at time of publication.",
    },
    prior_year: {
      season: "FY2022/23",
      revenue: 425.5,
      wage_bill: 226.9,
      wage_to_revenue_pct: 53.3,
      operating_profit: -40.0,
      profit_from_player_sales: null,
      pre_tax_profit: -77.2,
      net_debt: 308.8,
      net_profit: -85.4,
    },
    historical: [
      { season: "FY2022/23", revenue: 425.5, wage_bill: null, net_profit: -85.4 },
      { season: "FY2023/24", revenue: 473.2, wage_bill: 227.4, net_profit: -35.7 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Juventus ───────────────────────────────────────────────────────────────
  {
    slug: "juventus",
    name: "Juventus",
    country: "Italy",
    league: "Serie A",
    city: "Turin",
    currency: "EUR",
    stadium: { name: "Allianz Stadium", capacity: 41507, ownership: "Club-owned (Juventus FC SpA)" },
    ownership: { summary: "Exor NV (John Elkann / Agnelli family, ~64%)", category: "Juventus FC SpA (listed: BIT: JUVE)", fifty_plus_one: null },
    financials: {
      most_recent_year: "H1 FY2025/26 (Dec 2025)",
      revenue: 261.8,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: -44.0,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: 302.0,
      data_notes: "Interim half-year report (6 months to 31 December 2025). Revenue and net loss reflect H1 only — not comparable to full-year figures. Net debt as at 31 December 2025.",
    },
    prior_year: {
      season: "H1 FY2024/25",
      revenue: 291.6,
      wage_bill: 120.8,
      wage_to_revenue_pct: 41.4,
      operating_profit: 31.4,
      profit_from_player_sales: null,
      pre_tax_profit: 21.1,
      net_debt: 271.2,
      net_profit: 16.9,
    },
    historical: [
      { season: "H1 FY2025/26", revenue: 261.8, wage_bill: null, net_profit: -44.0 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Napoli ─────────────────────────────────────────────────────────────────
  {
    slug: "napoli",
    name: "SSC Napoli",
    country: "Italy",
    league: "Serie A",
    city: "Naples",
    currency: "EUR",
    stadium: { name: "Diego Armando Maradona Stadium", capacity: 54726, ownership: "Municipality of Naples (leased to club)" },
    ownership: { summary: "Aurelio De Laurentiis family (majority via Filmauro Srl)", category: "SSC Napoli SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 290.9,
      wage_bill: 142.1,
      wage_to_revenue_pct: 48.9,
      net_profit: -21.4,
      total_liabilities: null,
      equity: null,
      operating_profit: -24.7,
      profit_from_player_sales: null,
      pre_tax_profit: -20.6,
      net_debt: -137.0,
      data_notes: "Individual entity (SSC Napoli SpA) accounts. Net cash of €137.0m (cash €174.4m less bank debt €37.4m). Revenue decline from FY2023/24 (€328.2m) partly reflects UEFA round-of-16 exit.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 328.2,
      wage_bill: 116.4,
      wage_to_revenue_pct: 35.5,
      operating_profit: 83.7,
      profit_from_player_sales: null,
      pre_tax_profit: 91.2,
      net_debt: -160.0,
      net_profit: 63.0,
    },
    historical: [
      { season: "FY2023/24", revenue: 328.2, wage_bill: null, net_profit: 63.0 },
      { season: "FY2024/25", revenue: 290.9, wage_bill: 142.1, net_profit: -21.4 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── AS Roma ────────────────────────────────────────────────────────────────
  {
    slug: "as-roma",
    name: "AS Roma",
    country: "Italy",
    league: "Serie A",
    city: "Rome",
    currency: "EUR",
    stadium: { name: "Stadio Olimpico", capacity: 70634, ownership: "Municipality of Rome / Italian Olympic Committee (leased)" },
    ownership: { summary: "Friedkin Group (100% via The Friedkin Group Inc)", category: "AS Roma SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 270.2,
      wage_bill: 152.7,
      wage_to_revenue_pct: 56.5,
      net_profit: -53.9,
      total_liabilities: null,
      equity: null,
      operating_profit: -35.0,
      profit_from_player_sales: null,
      pre_tax_profit: -48.9,
      net_debt: 382.8,
      data_notes: "Net debt €382.8m includes NEEP International SARL shareholder loans from Friedkin Group. Consolidated accounts.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 299.9,
      wage_bill: 202.1,
      wage_to_revenue_pct: 67.4,
      operating_profit: -64.5,
      profit_from_player_sales: 25.0,
      pre_tax_profit: -75.6,
      net_debt: 139.7,
      net_profit: -81.4,
    },
    historical: [
      { season: "FY2023/24", revenue: 299.9, wage_bill: null, net_profit: -81.4 },
      { season: "FY2024/25", revenue: 270.2, wage_bill: 152.7, net_profit: -53.9 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Atalanta ───────────────────────────────────────────────────────────────
  {
    slug: "atalanta",
    name: "Atalanta BC",
    country: "Italy",
    league: "Serie A",
    city: "Bergamo",
    currency: "EUR",
    stadium: { name: "Gewiss Stadium", capacity: 21747, ownership: "Club-owned (Atalanta BC SpA)" },
    ownership: { summary: "Percassi family (majority via Atalanta BC SpA)", category: "Atalanta BC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 243.7,
      wage_bill: 115.2,
      wage_to_revenue_pct: 47.3,
      net_profit: 11.9,
      total_liabilities: null,
      equity: null,
      operating_profit: 20.0,
      profit_from_player_sales: null,
      pre_tax_profit: 21.3,
      net_debt: 4.7,
      data_notes: "Revenue includes €71.0m gains on player sales. FY2024/25 accounts include UEFA Europa League winner prize pool. FY2024/25 not yet filed at publication.",
    },
    prior_year: {
      season: "FY2022/23",
      revenue: 195.4,
      wage_bill: 84.4,
      wage_to_revenue_pct: 43.2,
      operating_profit: 9.7,
      profit_from_player_sales: null,
      pre_tax_profit: 9.4,
      net_debt: 1.0,
      net_profit: 5.6,
    },
    historical: [
      { season: "FY2022/23", revenue: 195.4, wage_bill: null, net_profit: 5.6 },
      { season: "FY2023/24", revenue: 243.7, wage_bill: 115.2, net_profit: 11.9 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Lazio ──────────────────────────────────────────────────────────────────
  {
    slug: "lazio",
    name: "SS Lazio",
    country: "Italy",
    league: "Serie A",
    city: "Rome",
    currency: "EUR",
    stadium: { name: "Stadio Olimpico", capacity: 70634, ownership: "Municipality of Rome / Italian Olympic Committee (leased)" },
    ownership: { summary: "Claudio Lotito (majority)", category: "SS Lazio SpA (listed: BIT: SSL)", fifty_plus_one: null },
    financials: {
      most_recent_year: "H1 FY2025/26 (Dec 2025)",
      revenue: 52.0,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: 111.3,
      data_notes: "Interim half-year report (6 months to 31 December 2025). Revenue reflects H1 only — not comparable to full-year figures. Net debt as at 31 December 2025.",
    },
    prior_year: {
      season: "H1 FY2024/25",
      revenue: 77.1,
      wage_bill: 48.7,
      wage_to_revenue_pct: 63.2,
      operating_profit: 0.45,
      profit_from_player_sales: null,
      pre_tax_profit: -1.23,
      net_debt: 66.3,
      net_profit: 0.60,
    },
    historical: [
      { season: "H1 FY2025/26", revenue: 52.0, wage_bill: null, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Fiorentina ─────────────────────────────────────────────────────────────
  {
    slug: "fiorentina",
    name: "ACF Fiorentina",
    country: "Italy",
    league: "Serie A",
    city: "Florence",
    currency: "EUR",
    stadium: { name: "Stadio Artemio Franchi", capacity: 43147, ownership: "Municipality of Florence (leased)" },
    ownership: { summary: "Rocco Commisso (100% via Mediacom Communications)", category: "ACF Fiorentina SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 198.6,
      wage_bill: 94.7,
      wage_to_revenue_pct: 47.7,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: -17.6,
      profit_from_player_sales: null,
      pre_tax_profit: -17.7,
      net_debt: -7.3,
      data_notes: "Net cash position of €7.3m. Two consecutive UEFA Conference League final appearances (2023/24, 2024/25).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 199.9,
      wage_bill: 97.6,
      wage_to_revenue_pct: 48.8,
      operating_profit: -4.7,
      profit_from_player_sales: null,
      pre_tax_profit: -4.2,
      net_debt: -22.3,
      net_profit: -6.0,
    },
    historical: [
      { season: "FY2024/25", revenue: 198.6, wage_bill: 94.7, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Bologna ────────────────────────────────────────────────────────────────
  {
    slug: "bologna",
    name: "Bologna FC 1909",
    country: "Italy",
    league: "Serie A",
    city: "Bologna",
    currency: "EUR",
    stadium: { name: "Renato Dall'Ara", capacity: 38279, ownership: "Municipality of Bologna (leased)" },
    ownership: { summary: "Joey Saputo (majority via Saputo Football Group)", category: "Bologna FC 1909 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 138.2,
      wage_bill: 84.1,
      wage_to_revenue_pct: 60.9,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: 22.6,
      profit_from_player_sales: null,
      pre_tax_profit: 19.6,
      net_debt: 18.8,
      data_notes: "First season in UEFA Champions League (2024/25), contributing to revenue growth.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 127.8,
      wage_bill: 71.1,
      wage_to_revenue_pct: 55.6,
      operating_profit: -7.0,
      profit_from_player_sales: null,
      pre_tax_profit: -8.1,
      net_debt: 19.7,
      net_profit: -10.4,
    },
    historical: [
      { season: "FY2024/25", revenue: 138.2, wage_bill: 84.1, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Udinese ────────────────────────────────────────────────────────────────
  {
    slug: "udinese",
    name: "Udinese Calcio",
    country: "Italy",
    league: "Serie A",
    city: "Udine",
    currency: "EUR",
    stadium: { name: "Bluenergy Stadium", capacity: 25144, ownership: "Club-owned (Udinese Calcio SpA)" },
    ownership: { summary: "Pozzo family (Gino Pozzo, majority)", category: "Udinese Calcio SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 141.7,
      wage_bill: 42.1,
      wage_to_revenue_pct: 29.7,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: 11.0,
      profit_from_player_sales: null,
      pre_tax_profit: 4.0,
      net_debt: 49.0,
      data_notes: "One of the most cost-efficient wage structures in Serie A. Pozzo family also own Watford FC.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 120.9,
      wage_bill: 41.0,
      wage_to_revenue_pct: 33.9,
      operating_profit: -2.9,
      profit_from_player_sales: 37.6,
      pre_tax_profit: -9.1,
      net_debt: 59.0,
      net_profit: -11.5,
    },
    historical: [
      { season: "FY2024/25", revenue: 141.7, wage_bill: 42.1, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Hellas Verona ──────────────────────────────────────────────────────────
  {
    slug: "hellas-verona",
    name: "Hellas Verona FC",
    country: "Italy",
    league: "Serie A",
    city: "Verona",
    currency: "EUR",
    stadium: { name: "Stadio Marcantonio Bentegodi", capacity: 39211, ownership: "Municipality of Verona (leased)" },
    ownership: { summary: "Renzo Rosso (majority, acquired 2020)", category: "Hellas Verona FC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 101.6,
      wage_bill: 43.3,
      wage_to_revenue_pct: 42.7,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: -0.8,
      profit_from_player_sales: null,
      pre_tax_profit: -2.8,
      net_debt: 89.3,
      data_notes: "Negative equity reported at 30 June 2025.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 115.3,
      wage_bill: 43.7,
      wage_to_revenue_pct: 37.9,
      operating_profit: 12.3,
      profit_from_player_sales: null,
      pre_tax_profit: 8.1,
      net_debt: 89.0,
      net_profit: 3.9,
    },
    historical: [
      { season: "FY2024/25", revenue: 101.6, wage_bill: 43.3, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Torino ─────────────────────────────────────────────────────────────────
  {
    slug: "torino-fc",
    name: "Torino FC",
    country: "Italy",
    league: "Serie A",
    city: "Turin",
    currency: "EUR",
    stadium: { name: "Stadio Grande Torino", capacity: 28177, ownership: "Municipality of Turin (leased)" },
    ownership: { summary: "Urbano Cairo (majority via Cairo Communication)", category: "Torino FC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025 (Dec)",
      revenue: 122.5,
      wage_bill: 68.9,
      wage_to_revenue_pct: 56.2,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: -12.5,
      profit_from_player_sales: null,
      pre_tax_profit: -15.4,
      net_debt: 42.6,
      data_notes: "December fiscal year (calendar year 2025). Torino FC uses a 31 December FY, unlike the June FY used by most Italian clubs.",
    },
    prior_year: {
      season: "FY2024 (Dec)",
      revenue: 134.5,
      wage_bill: 58.9,
      wage_to_revenue_pct: 43.8,
      operating_profit: 19.7,
      profit_from_player_sales: null,
      pre_tax_profit: 16.9,
      net_debt: 43.5,
      net_profit: 10.4,
    },
    historical: [
      { season: "FY2025 (Dec)", revenue: 122.5, wage_bill: 68.9, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Genoa ──────────────────────────────────────────────────────────────────
  {
    slug: "genoa-cfc",
    name: "Genoa CFC",
    country: "Italy",
    league: "Serie A",
    city: "Genoa",
    currency: "EUR",
    stadium: { name: "Stadio Luigi Ferraris", capacity: 36599, ownership: "Jointly owned with Sampdoria; Genoa municipality" },
    ownership: { summary: "Dan Sucu (majority, acquired Dec 2023 from 777 Partners)", category: "Genoa CFC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "Jan–Jun 2024 (6-month transitional)",
      revenue: 89.4,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: 148.2,
      data_notes: "6-month transitional period (January–June 2024) following change of financial year. Revenue covers 6 months only and includes ~€62m one-off catch-up charges. Figures not directly comparable to other clubs.",
    },
    prior_year: {
      season: "FY2023 (Dec)",
      revenue: 120.7,
      wage_bill: 65.5,
      wage_to_revenue_pct: 54.3,
      operating_profit: -25.7,
      profit_from_player_sales: null,
      pre_tax_profit: -35.5,
      net_debt: 117.1,
      net_profit: -33.1,
    },
    historical: [
      { season: "Jan–Jun 2024", revenue: 89.4, wage_bill: null, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Monza ──────────────────────────────────────────────────────────────────
  {
    slug: "ac-monza",
    name: "AC Monza",
    country: "Italy",
    league: "Serie A",
    city: "Monza",
    currency: "EUR",
    stadium: { name: "U-Power Stadium", capacity: 18568, ownership: "AC Monza SpA" },
    ownership: { summary: "Fininvest SpA (Berlusconi family)", category: "AC Monza SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024 (Dec)",
      revenue: 85.7,
      wage_bill: 77.9,
      wage_to_revenue_pct: 91.0,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: -53.4,
      profit_from_player_sales: null,
      pre_tax_profit: -54.2,
      net_debt: 13.1,
      data_notes: "December fiscal year. Losses funded by Fininvest (Berlusconi family). Relegated to Serie B at end of 2024/25 season.",
    },
    prior_year: null,
    historical: [
      { season: "FY2024 (Dec)", revenue: 85.7, wage_bill: 77.9, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Sassuolo ───────────────────────────────────────────────────────────────
  {
    slug: "us-sassuolo",
    name: "US Sassuolo",
    country: "Italy",
    league: "Serie B",
    city: "Sassuolo",
    currency: "EUR",
    stadium: { name: "Mapei Stadium – Città del Tricolore", capacity: 21353, ownership: "Mapei SpA" },
    ownership: { summary: "Mapei SpA (Giorgio Squinzi heirs)", category: "US Sassuolo Calcio Srl", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025 (Dec)",
      revenue: 70.7,
      wage_bill: 59.1,
      wage_to_revenue_pct: 83.6,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: -47.9,
      profit_from_player_sales: null,
      pre_tax_profit: -50.6,
      net_debt: 38.7,
      data_notes: "December fiscal year. Going concern — continuation dependent on Mapei shareholder support. Relegated to Serie B at end of 2023/24 season.",
    },
    prior_year: {
      season: "FY2024 (Dec)",
      revenue: 102.1,
      wage_bill: 63.4,
      wage_to_revenue_pct: 62.1,
      operating_profit: -23.7,
      profit_from_player_sales: null,
      pre_tax_profit: -27.1,
      net_debt: 85.9,
      net_profit: -22.1,
    },
    historical: [
      { season: "FY2025 (Dec)", revenue: 70.7, wage_bill: 59.1, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Parma ──────────────────────────────────────────────────────────────────
  {
    slug: "parma-calcio",
    name: "Parma Calcio 1913",
    country: "Italy",
    league: "Serie A",
    city: "Parma",
    currency: "EUR",
    stadium: { name: "Stadio Ennio Tardini", capacity: 22352, ownership: "Parma Calcio 1913 SpA" },
    ownership: { summary: "Krause Group (Kyle Krause, majority)", category: "Parma Calcio 1913 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024 (Dec)",
      revenue: 41.5,
      wage_bill: 49.2,
      wage_to_revenue_pct: 118.5,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: -64.4,
      profit_from_player_sales: null,
      pre_tax_profit: -64.4,
      net_debt: 33.6,
      data_notes: "December fiscal year (covers Serie B promotion season). Going concern — continuation dependent on Krause Group shareholder support. Promoted to Serie A for 2024/25.",
    },
    prior_year: {
      season: "FY2023 (Dec)",
      revenue: 28.9,
      wage_bill: 43.8,
      wage_to_revenue_pct: 151.6,
      operating_profit: -80.4,
      profit_from_player_sales: null,
      pre_tax_profit: -80.5,
      net_debt: -12.9,
      net_profit: -80.5,
    },
    historical: [
      { season: "FY2024 (Dec)", revenue: 41.5, wage_bill: 49.2, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Cremonese ──────────────────────────────────────────────────────────────
  {
    slug: "us-cremonese",
    name: "US Cremonese",
    country: "Italy",
    league: "Serie B",
    city: "Cremona",
    currency: "EUR",
    stadium: { name: "Giovanni Zini", capacity: 16003, ownership: "Cremonese SpA" },
    ownership: { summary: "Giovanni Arvedi (majority via Acciaieria Arvedi SpA)", category: "Unione Sportiva Cremonese SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 57.7,
      wage_bill: 29.1,
      wage_to_revenue_pct: 50.4,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: 3.6,
      profit_from_player_sales: null,
      pre_tax_profit: 3.5,
      net_debt: 0.7,
      data_notes: "Essentially debt-free. Competing in Serie B.",
    },
    prior_year: {
      season: "FY2022/23",
      revenue: 89.1,
      wage_bill: 44.2,
      wage_to_revenue_pct: 49.6,
      operating_profit: 10.0,
      profit_from_player_sales: null,
      pre_tax_profit: 9.9,
      net_debt: 0.7,
      net_profit: 7.2,
    },
    historical: [
      { season: "FY2023/24", revenue: 57.7, wage_bill: 29.1, net_profit: null },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },


  // ─── Como 1907 ──────────────────────────────────────────────────────────────
  {
    slug: "como-1907",
    name: "Como 1907",
    country: "Italy",
    league: "Serie A",
    city: "Como",
    currency: "EUR",
    stadium: { name: "Stadio Giuseppe Sinigaglia", capacity: 10500, ownership: "Municipality of Como (leased)" },
    ownership: { summary: "Sent Entertainment Ltd (Robert Hartono family, ~80%)", category: "Como 1907 SRL", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 55.4,
      wage_bill: 85.7,
      wage_to_revenue_pct: 154.7,
      net_profit: -105.0,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: -7.7,
      data_notes: "First Serie A season (2024/25) following promotion. Significant investment by Indonesian Hartono family driving heavy losses. Net cash of €7.7m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 9.8,
      wage_bill: 33.6,
      wage_to_revenue_pct: 342.9,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: null,
      net_profit: -47.8,
    },
    historical: [
      { season: "FY2023/24", revenue: 9.8, wage_bill: 33.6, net_profit: -47.8 },
      { season: "FY2024/25", revenue: 55.4, wage_bill: 85.7, net_profit: -105.0 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Venezia FC ─────────────────────────────────────────────────────────────
  {
    slug: "venezia-fc",
    name: "Venezia FC",
    country: "Italy",
    league: "Serie A",
    city: "Venice",
    currency: "EUR",
    stadium: { name: "Stadio Pier Luigi Penzo", capacity: 7450, ownership: "Municipality of Venice (leased)" },
    ownership: { summary: "American-led investor consortium (majority)", category: "Venezia FC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 51.8,
      wage_bill: 48.6,
      wage_to_revenue_pct: 93.8,
      net_profit: -35.9,
      total_liabilities: null,
      equity: null,
      operating_profit: -35.0,
      profit_from_player_sales: null,
      pre_tax_profit: -35.8,
      net_debt: -5.0,
      data_notes: "Serie A return after promotion from Serie B in 2023/24. Smallest stadium capacity in Serie A (7,450 seats). Net cash of €5.0m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 20.0,
      wage_bill: 33.5,
      wage_to_revenue_pct: 167.5,
      operating_profit: -42.1,
      profit_from_player_sales: null,
      pre_tax_profit: -43.8,
      net_debt: 1.5,
      net_profit: -43.7,
    },
    historical: [
      { season: "FY2023/24", revenue: 20.0, wage_bill: 33.5, net_profit: -43.7 },
      { season: "FY2024/25", revenue: 51.8, wage_bill: 48.6, net_profit: -35.9 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── US Lecce ────────────────────────────────────────────────────────────────
  {
    slug: "us-lecce",
    name: "US Lecce",
    country: "Italy",
    league: "Serie A",
    city: "Lecce",
    currency: "EUR",
    stadium: { name: "Stadio Via del Mare", capacity: 31533, ownership: "Municipality of Lecce (leased)" },
    ownership: { summary: "Sticchi Damiani family (majority; Saverio Sticchi Damiani, president)", category: "Unione Sportiva Lecce SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 108.0,
      wage_bill: 14.7,
      wage_to_revenue_pct: 13.6,
      net_profit: 20.2,
      total_liabilities: null,
      equity: null,
      operating_profit: 24.5,
      profit_from_player_sales: 52.5,
      pre_tax_profit: 23.8,
      net_debt: 3.2,
      data_notes: "Revenue heavily inflated by player sale gains (€52.5m plusvalenze). Underlying revenue excluding transfers ≈ €55.4m. TV rights €33.1m (Serie A). Relegated from Serie A at end of 2024/25. Net debt €3.2m (bank €3.0m + other financial lenders €5.8m less cash €5.6m).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 85.3,
      wage_bill: 11.6,
      wage_to_revenue_pct: 13.6,
      operating_profit: 18.0,
      profit_from_player_sales: null,
      pre_tax_profit: 16.8,
      net_debt: null,
      net_profit: 14.0,
    },
    historical: [
      { season: "FY2023/24", revenue: 85.3, wage_bill: 11.6, net_profit: 14.0 },
      { season: "FY2024/25", revenue: 108.0, wage_bill: 14.7, net_profit: 20.2 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── AC Reggiana ─────────────────────────────────────────────────────────────
  {
    slug: "ac-reggiana",
    name: "AC Reggiana 1919",
    country: "Italy",
    league: "Serie B",
    city: "Reggio Emilia",
    currency: "EUR",
    stadium: { name: "Mapei Stadium – Città del Tricolore", capacity: 21584, ownership: "Mapei SpA" },
    ownership: { summary: "Locally owned (no external parent group)", category: "AC Reggiana 1919 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 17.5,
      wage_bill: 11.4,
      wage_to_revenue_pct: 65.1,
      net_profit: -1.8,
      total_liabilities: null,
      equity: null,
      operating_profit: -1.8,
      profit_from_player_sales: null,
      pre_tax_profit: -1.8,
      net_debt: -0.1,
      data_notes: "Net cash position. Shares Mapei Stadium with Sassuolo. No external parent company; independently owned.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 18.6,
      wage_bill: 11.0,
      wage_to_revenue_pct: 59.1,
      operating_profit: 0.1,
      profit_from_player_sales: null,
      pre_tax_profit: 0.1,
      net_debt: -1.4,
      net_profit: -0.4,
    },
    historical: [
      { season: "FY2023/24", revenue: 18.6, wage_bill: 11.0, net_profit: -0.4 },
      { season: "FY2024/25", revenue: 17.5, wage_bill: 11.4, net_profit: -1.8 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── US Catanzaro ────────────────────────────────────────────────────────────
  {
    slug: "us-catanzaro",
    name: "US Catanzaro 1929",
    country: "Italy",
    league: "Serie B",
    city: "Catanzaro",
    currency: "EUR",
    stadium: { name: "Stadio Nicola Ceravolo", capacity: 16000, ownership: "Municipality of Catanzaro (leased)" },
    ownership: { summary: "AZ S.p.A. / Noto S.p.A. (majority)", category: "Unione Sportiva Catanzaro 1929 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023 (Dec)",
      revenue: 9.3,
      wage_bill: 9.6,
      wage_to_revenue_pct: 103.2,
      net_profit: -4.3,
      total_liabilities: null,
      equity: null,
      operating_profit: -5.4,
      profit_from_player_sales: null,
      pre_tax_profit: -5.4,
      net_debt: -2.6,
      data_notes: "December fiscal year. Net cash of €2.6m. Wages exceed revenue, typical of smaller Serie B club.",
    },
    prior_year: {
      season: "FY2022 (Dec)",
      revenue: 4.3,
      wage_bill: 5.8,
      wage_to_revenue_pct: 134.9,
      operating_profit: -4.5,
      profit_from_player_sales: null,
      pre_tax_profit: -4.5,
      net_debt: -1.7,
      net_profit: -3.6,
    },
    historical: [
      { season: "FY2022 (Dec)", revenue: 4.3, wage_bill: 5.8, net_profit: -3.6 },
      { season: "FY2023 (Dec)", revenue: 9.3, wage_bill: 9.6, net_profit: -4.3 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Modena FC ───────────────────────────────────────────────────────────────
  {
    slug: "modena-fc",
    name: "Modena FC 2018",
    country: "Italy",
    league: "Serie B",
    city: "Modena",
    currency: "EUR",
    stadium: { name: "Stadio Alberto Braglia", capacity: 21151, ownership: "Municipality of Modena (leased)" },
    ownership: { summary: "Rivetex Srl (Italian holding company, majority)", category: "Modena F.C. 2018 Srl", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 14.0,
      wage_bill: 16.4,
      wage_to_revenue_pct: 117.1,
      net_profit: -11.6,
      total_liabilities: null,
      equity: null,
      operating_profit: -15.0,
      profit_from_player_sales: null,
      pre_tax_profit: -15.0,
      net_debt: -4.9,
      data_notes: "Net cash of €4.9m. Net loss reduced by €3.4m tax benefit from fiscal consolidation with parent Rivetex Srl. Losses funded by shareholder capital injections (€19.4m in FY2025). Bank debt negligible (€0.9k).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 16.8,
      wage_bill: 13.6,
      wage_to_revenue_pct: 81.0,
      operating_profit: -8.1,
      profit_from_player_sales: null,
      pre_tax_profit: -8.1,
      net_debt: null,
      net_profit: -6.5,
    },
    historical: [
      { season: "FY2023/24", revenue: 16.8, wage_bill: 13.6, net_profit: -6.5 },
      { season: "FY2024/25", revenue: 14.0, wage_bill: 16.4, net_profit: -11.6 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── SS Juve Stabia ──────────────────────────────────────────────────────────
  {
    slug: "juve-stabia",
    name: "SS Juve Stabia",
    country: "Italy",
    league: "Serie B",
    city: "Castellammare di Stabia",
    currency: "EUR",
    stadium: { name: "Stadio Romeo Menti", capacity: 9040, ownership: "Municipality of Castellammare di Stabia (leased)" },
    ownership: { summary: "Brera Holdings PLC (Nasdaq: BREA, majority) alongside XX Settembre Holding SRL", category: "SS Juve Stabia SRL", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 12.6,
      wage_bill: 11.4,
      wage_to_revenue_pct: 90.5,
      net_profit: -7.6,
      total_liabilities: null,
      equity: null,
      operating_profit: -7.2,
      profit_from_player_sales: null,
      pre_tax_profit: -7.3,
      net_debt: 0.2,
      data_notes: "Owned by Nasdaq-listed Brera Holdings PLC. Net debt: bank €0.2m + shareholder loans to controllanti €0.4m, less cash €0.4m. Negative equity (€-3.9m). Going concern dependency on shareholder support.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 5.0,
      wage_bill: 3.5,
      wage_to_revenue_pct: 70.0,
      operating_profit: -0.6,
      profit_from_player_sales: null,
      pre_tax_profit: -0.7,
      net_debt: 0.1,
      net_profit: -0.8,
    },
    historical: [
      { season: "FY2023/24", revenue: 5.0, wage_bill: 3.5, net_profit: -0.8 },
      { season: "FY2024/25", revenue: 12.6, wage_bill: 11.4, net_profit: -7.6 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Delfino Pescara ─────────────────────────────────────────────────────────
  {
    slug: "delfino-pescara",
    name: "Delfino Pescara 1936",
    country: "Italy",
    league: "Serie B",
    city: "Pescara",
    currency: "EUR",
    stadium: { name: "Stadio Adriatico-Giovanni Cornacchia", capacity: 20476, ownership: "Municipality of Pescara (leased)" },
    ownership: { summary: "Delfino Capital Srl (majority)", category: "Delfino Pescara 1936 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 8.1,
      wage_bill: 4.9,
      wage_to_revenue_pct: 60.5,
      net_profit: -3.9,
      total_liabilities: null,
      equity: null,
      operating_profit: -3.4,
      profit_from_player_sales: null,
      pre_tax_profit: -3.9,
      net_debt: 2.4,
      data_notes: "Competed in Serie C during 2024/25; promoted to Serie B for 2025/26. Net debt €2.4m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 8.9,
      wage_bill: 4.7,
      wage_to_revenue_pct: 52.8,
      operating_profit: -2.2,
      profit_from_player_sales: null,
      pre_tax_profit: -2.9,
      net_debt: 5.1,
      net_profit: -2.9,
    },
    historical: [
      { season: "FY2023/24", revenue: 8.9, wage_bill: 4.7, net_profit: -2.9 },
      { season: "FY2024/25", revenue: 8.1, wage_bill: 4.9, net_profit: -3.9 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Calcio Padova ───────────────────────────────────────────────────────────
  {
    slug: "calcio-padova",
    name: "Calcio Padova",
    country: "Italy",
    league: "Serie B",
    city: "Padua",
    currency: "EUR",
    stadium: { name: "Stadio Euganeo", capacity: 32420, ownership: "Municipality of Padua (leased)" },
    ownership: { summary: "J4A Holding II SARL (Luxembourg, majority)", category: "Calcio Padova SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 5.0,
      wage_bill: 6.3,
      wage_to_revenue_pct: 126.0,
      net_profit: -6.5,
      total_liabilities: null,
      equity: null,
      operating_profit: -6.4,
      profit_from_player_sales: null,
      pre_tax_profit: -6.5,
      net_debt: 0.2,
      data_notes: "Competed in Serie C during 2024/25; promoted to Serie B for 2025/26. Wages exceed revenue; losses funded by Luxembourg holding company. Net debt €0.2m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 8.0,
      wage_bill: 5.7,
      wage_to_revenue_pct: 71.3,
      operating_profit: -2.4,
      profit_from_player_sales: null,
      pre_tax_profit: -2.4,
      net_debt: 0.0,
      net_profit: -2.4,
    },
    historical: [
      { season: "FY2023/24", revenue: 8.0, wage_bill: 5.7, net_profit: -2.4 },
      { season: "FY2024/25", revenue: 5.0, wage_bill: 6.3, net_profit: -6.5 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Virtus Entella ──────────────────────────────────────────────────────────
  {
    slug: "virtus-entella",
    name: "Virtus Entella",
    country: "Italy",
    league: "Serie B",
    city: "Chiavari",
    currency: "EUR",
    stadium: { name: "Stadio Comunale di Chiavari", capacity: 7000, ownership: "Municipality of Chiavari" },
    ownership: { summary: "Duferco Travi e Profilati SpA (70%, acquired June 2025)", category: "Virtus Entella SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 6.5,
      wage_bill: 8.5,
      wage_to_revenue_pct: 130.8,
      net_profit: -7.3,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: -7.3,
      net_debt: -1.0,
      data_notes: "Net cash of €1.0m. Competed in Serie C during 2024/25; promoted to Serie B for 2025/26. Duferco (Italian steel group) acquired 70% stake in June 2025.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 3.9,
      wage_bill: 7.2,
      wage_to_revenue_pct: 184.6,
      operating_profit: -8.2,
      profit_from_player_sales: null,
      pre_tax_profit: -8.2,
      net_debt: 2.9,
      net_profit: null,
    },
    historical: [
      { season: "FY2023/24", revenue: 3.9, wage_bill: 7.2, net_profit: null },
      { season: "FY2024/25", revenue: 6.5, wage_bill: 8.5, net_profit: -7.3 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── US Avellino ─────────────────────────────────────────────────────────────
  {
    slug: "us-avellino",
    name: "US Avellino 1912",
    country: "Italy",
    league: "Serie B",
    city: "Avellino",
    currency: "EUR",
    stadium: { name: "Stadio Partenio-Adriano Lombardi", capacity: 25676, ownership: "Municipality of Avellino (leased)" },
    ownership: { summary: "SG Flat Finance Holding SpA (majority)", category: "Unione Sportiva Avellino 1912 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024 (Dec)",
      revenue: 8.5,
      wage_bill: 10.7,
      wage_to_revenue_pct: 125.9,
      net_profit: -5.3,
      total_liabilities: null,
      equity: null,
      operating_profit: -6.5,
      profit_from_player_sales: null,
      pre_tax_profit: -6.6,
      net_debt: -0.4,
      data_notes: "December fiscal year. Net cash of €0.4m. Wages significantly exceed revenue.",
    },
    prior_year: {
      season: "FY2023 (Dec)",
      revenue: 6.3,
      wage_bill: 8.4,
      wage_to_revenue_pct: 133.3,
      operating_profit: -5.4,
      profit_from_player_sales: null,
      pre_tax_profit: -5.5,
      net_debt: -0.2,
      net_profit: -4.4,
    },
    historical: [
      { season: "FY2023 (Dec)", revenue: 6.3, wage_bill: 8.4, net_profit: -4.4 },
      { season: "FY2024 (Dec)", revenue: 8.5, wage_bill: 10.7, net_profit: -5.3 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

];
