// Italian Serie A / Serie B clubs — values in EUR millions
// Source: Annual accounts (bilancio d'esercizio / bilancio consolidato) filed at CCIAA / club investor relations
// FY typically ends 30 June (football year) unless noted. December FY clubs marked "FY20XX (Dec)".
// Revenue = Valore della Produzione (includes gains on player sales)
// Wages  = Costo del personale
// Operating profit = Differenza tra Valore e Costi della Produzione (A−B / EBIT)
// Net debt = financial bank debt + bonds + SH loans − cash (trade payables, IFRS 16 lease liabilities excluded unless material)
// net_debt < 0 = net cash

import { EUClub } from "./euClubs";

export const itClubs: EUClub[] = [

  // ─── AC Milan ───────────────────────────────────────────────────────────────
  {
    slug: "ac-milan",
    name: "AC Milan",
    country: "Italy",
    league: "Serie A",
    city: "Milan",
    currency: "EUR",
    stadium: { name: "San Siro (Stadio Giuseppe Meazza)", capacity: 75923, ownership: "Shared with Inter Milan; municipality of Milan" },
    ownership: { summary: "RedBird Capital Partners (99%)", category: "AC Milan SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 494.5,
      wage_bill: 188.7,
      wage_to_revenue_pct: 38.2,
      net_profit: 3.0,
      total_liabilities: 515.9,
      equity: 199.4,
      operating_profit: 16.0,
      profit_from_player_sales: 55.9,
      pre_tax_profit: 9.8,
      net_debt: 92.6,
      data_notes: "Gruppo Milan consolidated (Italian GAAP / OIC). Revenue includes plusvalenze €55.9m (Reijnders → Man City €41.9m; Kalulu → Juventus €13.2m). All financial debt is factoring (€136.1m; no bonds or bank loans). Net financial position: factoring debt €136.1m less cash €28.0m and liquid financial assets €15.5m = €92.6m net debt. Player write-downs €19.7m in FY2025 (Bondo, Chukwueze, Musah et al). UEFA settlement for FY2022–24 met in full; accrued provisions released in FY2025. FY2022 wage bill not separately disclosed in comparative accounts.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 450.2,
      wage_bill: 182.7,
      wage_to_revenue_pct: 40.6,
      operating_profit: 13.2,
      profit_from_player_sales: 44.9,
      pre_tax_profit: 12.3,
      net_debt: 49.6,
      net_profit: 4.1,
      equity: 196.3,
    },
    historical: [
      {
        season: "FY2022/23",
        revenue: 404.5,
        wage_bill: 174.0,
        net_profit: 6.1,
        operating_profit: 14.9,
        pre_tax_profit: 13.5,
        net_debt: -10.8,
        equity: 177.2,
      },
      {
        season: "FY2023/24",
        revenue: 450.2,
        wage_bill: 182.7,
        net_profit: 4.1,
        operating_profit: 13.2,
        pre_tax_profit: 12.3,
        net_debt: 49.6,
        equity: 196.3,
      },
      {
        season: "FY2024/25",
        revenue: 494.5,
        wage_bill: 188.7,
        net_profit: 3.0,
        operating_profit: 16.0,
        pre_tax_profit: 9.8,
        net_debt: 92.6,
        equity: 199.4,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Inter Milan ────────────────────────────────────────────────────────────
  {
    slug: "inter-milan",
    name: "Inter Milan",
    country: "Italy",
    league: "Serie A",
    city: "Milan",
    currency: "EUR",
    stadium: { name: "San Siro (Stadio Giuseppe Meazza)", capacity: 75923, ownership: "Shared with AC Milan; municipality of Milan" },
    ownership: { summary: "Oaktree Capital Management (majority, acquired Jun 2024)", category: "F.C. Internazionale Milano SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023/24 (Jun)",
      revenue: 473.2,
      wage_bill: 231.4,
      wage_to_revenue_pct: 48.9,
      net_profit: -35.7,
      total_liabilities: null,
      equity: -99.7,
      operating_profit: 8.9,
      profit_from_player_sales: 65.8,
      pre_tax_profit: -26.6,
      net_debt: 330,
      data_notes: "Consolidated group (F.C. Internazionale Milano S.p.A. + subsidiaries), Italian OIC GAAP. Net debt includes bonds, shareholder loans less cash. FY2021/22 was peak loss period (COVID + heavy player amortisation on major acquisitions). First EBIT-positive year in FY2023/24. FY2024/25 accounts not yet filed at time of publication.",
    },
    prior_year: {
      season: "FY2022/23",
      revenue: 425.5,
      wage_bill: 228.9,
      wage_to_revenue_pct: 53.8,
      operating_profit: -40.0,
      profit_from_player_sales: 28.9,
      pre_tax_profit: -77.2,
      net_debt: 437,
      net_profit: -85.4,
      equity: -162.0,
    },
    historical: [
      {
        season: "FY2021/22",
        revenue: 439.6,
        wage_bill: 248.4,
        net_profit: -140.1,
        operating_profit: -88.3,
        pre_tax_profit: -136.7,
        net_debt: 361,
        equity: -86.6,
        profit_from_player_sales: 105.2,
      },
      {
        season: "FY2022/23",
        revenue: 425.5,
        wage_bill: 228.9,
        net_profit: -85.4,
        operating_profit: -40.0,
        pre_tax_profit: -77.2,
        net_debt: 437,
        equity: -162.0,
        profit_from_player_sales: 28.9,
      },
      {
        season: "FY2023/24",
        revenue: 473.2,
        wage_bill: 231.4,
        net_profit: -35.7,
        operating_profit: 8.9,
        pre_tax_profit: -26.6,
        net_debt: 330,
        equity: -99.7,
        profit_from_player_sales: 65.8,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Juventus ───────────────────────────────────────────────────────────────
  {
    slug: "juventus",
    name: "Juventus",
    country: "Italy",
    league: "Serie A",
    city: "Turin",
    currency: "EUR",
    stadium: { name: "Allianz Stadium", capacity: 41507, ownership: "Club-owned (Juventus FC SpA)" },
    ownership: { summary: "Exor NV (John Elkann / Agnelli family, ~64%)", category: "Juventus FC SpA (listed: BIT: JUVE)", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 529.6,
      wage_bill: 244.7,
      wage_to_revenue_pct: 46.2,
      net_profit: -58.1,
      total_liabilities: null,
      equity: 13.2,
      operating_profit: -29.9,
      profit_from_player_sales: 89.7,
      pre_tax_profit: -50.0,
      net_debt: 394.8,
      data_notes: "Consolidated IFRS accounts (Juventus FC S.p.A. + subsidiaries, listed BIT: JUVE). Revenue = Ricavi totali; plusvalenze appear within operating section. NFP per ESMA definition (includes IFRS 16 lease liabilities and trade payables > 12m). FY21/22 losses driven by COVID shortfalls + player write-downs. FY22/23 included €9.6m penalty from FIGC salary deferral agreement. FY23/24 worst year — FIGC barred from UEFA competitions (no UCL/UEL). FY24/25 recovery on UCL return + €89.7m player sale gains (Bremer partial, Chiesa, Miretti, others).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 394.6,
      wage_bill: 264.1,
      wage_to_revenue_pct: 66.9,
      operating_profit: -175.4,
      profit_from_player_sales: 22.9,
      pre_tax_profit: -196.1,
      net_debt: 305.7,
      net_profit: -199.2,
      equity: 40.2,
    },
    historical: [
      {
        season: "FY2021/22",
        revenue: 443.4,
        wage_bill: 337.0,
        net_profit: -239.3,
        operating_profit: -221.7,
        pre_tax_profit: -237.4,
        net_debt: 318.2,
        equity: 164.7,
        profit_from_player_sales: 28.9,
      },
      {
        season: "FY2022/23",
        revenue: 507.7,
        wage_bill: 282.4,
        net_profit: -123.7,
        operating_profit: -99.3,
        pre_tax_profit: -117.3,
        net_debt: 424.5,
        equity: 42.1,
        profit_from_player_sales: 46.7,
      },
      {
        season: "FY2023/24",
        revenue: 394.6,
        wage_bill: 264.1,
        net_profit: -199.2,
        operating_profit: -175.4,
        pre_tax_profit: -196.1,
        net_debt: 305.7,
        equity: 40.2,
        profit_from_player_sales: 22.9,
      },
      {
        season: "FY2024/25",
        revenue: 529.6,
        wage_bill: 244.7,
        net_profit: -58.1,
        operating_profit: -29.9,
        pre_tax_profit: -50.0,
        net_debt: 394.8,
        equity: 13.2,
        profit_from_player_sales: 89.7,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Napoli ─────────────────────────────────────────────────────────────────
  {
    slug: "napoli",
    name: "SSC Napoli",
    country: "Italy",
    league: "Serie A",
    city: "Naples",
    currency: "EUR",
    stadium: { name: "Diego Armando Maradona Stadium", capacity: 54726, ownership: "Municipality of Naples (leased to club)" },
    ownership: { summary: "Aurelio De Laurentiis family (majority via Filmauro Srl)", category: "SSC Napoli SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 290.9,
      wage_bill: 142.1,
      wage_to_revenue_pct: 48.9,
      net_profit: -21.4,
      total_liabilities: null,
      equity: null,
      operating_profit: -24.7,
      profit_from_player_sales: null,
      pre_tax_profit: -20.6,
      net_debt: -137.0,
      data_notes: "Individual entity (SSC Napoli SpA) accounts. Net cash of €137.0m (cash €174.4m less bank debt €37.4m). Revenue decline from FY2023/24 (€328.2m) partly reflects UEFA round-of-16 exit.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 328.2,
      wage_bill: 116.4,
      wage_to_revenue_pct: 35.5,
      operating_profit: 83.7,
      profit_from_player_sales: null,
      pre_tax_profit: 91.2,
      net_debt: -160.0,
      net_profit: 63.0,
    },
    historical: [
      {
        season: "FY2021/22",
        revenue: 176.0,
        wage_bill: 130.4,
        net_profit: -52.0,
        operating_profit: -65.2,
        pre_tax_profit: -65.6,
        net_debt: -55.9,
        equity: 68.8,
      },
      {
        season: "FY2022/23",
        revenue: 359.3,
        wage_bill: 111.3,
        net_profit: 79.7,
        operating_profit: 116.7,
        pre_tax_profit: 117.8,
        net_debt: -117.3,
        equity: 148.5,
      },
      {
        season: "FY2023/24",
        revenue: 328.2,
        wage_bill: 116.4,
        net_profit: 63.0,
        operating_profit: 83.7,
        pre_tax_profit: 91.2,
        net_debt: -160.0,
        equity: 211.6,
      },
      {
        season: "FY2024/25",
        revenue: 290.9,
        wage_bill: 142.1,
        net_profit: -21.4,
        operating_profit: -24.7,
        pre_tax_profit: -20.6,
        net_debt: -137.0,
        equity: 190.2,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── AS Roma ────────────────────────────────────────────────────────────────
  {
    slug: "as-roma",
    name: "AS Roma",
    country: "Italy",
    league: "Serie A",
    city: "Rome",
    currency: "EUR",
    stadium: { name: "Stadio Olimpico", capacity: 70634, ownership: "Municipality of Rome / Italian Olympic Committee (leased)" },
    ownership: { summary: "Friedkin Group (100% via The Friedkin Group Inc)", category: "AS Roma SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 270.2,
      wage_bill: 152.7,
      wage_to_revenue_pct: 56.5,
      net_profit: -53.9,
      total_liabilities: null,
      equity: null,
      operating_profit: -35.0,
      profit_from_player_sales: null,
      pre_tax_profit: -48.9,
      net_debt: 382.8,
      data_notes: "Net debt €382.8m includes NEEP International SARL shareholder loans from Friedkin Group. Consolidated accounts.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 299.9,
      wage_bill: 202.1,
      wage_to_revenue_pct: 67.4,
      operating_profit: -64.5,
      profit_from_player_sales: 25.0,
      pre_tax_profit: -75.6,
      net_debt: 431.8,
      net_profit: -81.4,
      equity: -407.7,
    },
    historical: [
      {
        season: "FY2021/22",
        revenue: 206.4,
        wage_bill: 183.2,
        net_profit: -219.3,
        operating_profit: -196.0,
        pre_tax_profit: -218.8,
        net_debt: 323.0,
        equity: -336.0,
        profit_from_player_sales: 6.2,
      },
      {
        season: "FY2022/23",
        revenue: 277.1,
        wage_bill: 173.1,
        net_profit: -102.7,
        operating_profit: -71.7,
        pre_tax_profit: -99.3,
        net_debt: 448.0,
        equity: -436.4,
        profit_from_player_sales: 47.1,
      },
      {
        season: "FY2023/24",
        revenue: 299.9,
        wage_bill: 202.1,
        net_profit: -81.4,
        operating_profit: -64.5,
        pre_tax_profit: -75.6,
        net_debt: 431.8,
        equity: -407.7,
        profit_from_player_sales: 25.0,
      },
      {
        season: "FY2024/25",
        revenue: 270.2,
        wage_bill: 152.7,
        net_profit: -53.9,
        operating_profit: -35.0,
        pre_tax_profit: -48.9,
        net_debt: 382.8,
        equity: -316.6,
        profit_from_player_sales: 29.9,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Atalanta ───────────────────────────────────────────────────────────────
  {
    slug: "atalanta",
    name: "Atalanta BC",
    country: "Italy",
    league: "Serie A",
    city: "Bergamo",
    currency: "EUR",
    stadium: { name: "Gewiss Stadium", capacity: 21747, ownership: "Club-owned (Atalanta BC SpA)" },
    ownership: { summary: "Percassi family (majority via Atalanta BC SpA)", category: "Atalanta BC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 320.8,
      wage_bill: 123.2,
      wage_to_revenue_pct: 38.4,
      net_profit: 37.9,
      total_liabilities: null,
      equity: 248.2,
      operating_profit: 59.1,
      profit_from_player_sales: 100.9,
      pre_tax_profit: 58.6,
      net_debt: 11.1,
      data_notes: "Consolidated group (Atalanta BC Srl + Stadio Atalanta Srl). Revenue includes €100.9m player sale gains (Koopmeiners to Juventus, Ederson, De Ketelaere, Lookman, Scalvini etc.) and ca. €67m UCL participation/prize money. Stadium mortgage (Gewiss Stadium; Intesa Sanpaolo/Credito Sportivo pool, nominal €55.3m) is the only financial debt — no bonds or shareholder loans. Essentially debt-free despite UCL investment.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 243.7,
      wage_bill: 115.2,
      wage_to_revenue_pct: 47.3,
      operating_profit: 20.0,
      profit_from_player_sales: 71.0,
      pre_tax_profit: 21.3,
      net_debt: 4.7,
      net_profit: 11.9,
      equity: 196.3,
    },
    historical: [
      {
        season: "FY2022/23",
        revenue: 195.4,
        wage_bill: 84.4,
        net_profit: 5.6,
        operating_profit: 9.7,
        pre_tax_profit: 9.4,
        net_debt: 1.0,
        equity: 185.1,
        profit_from_player_sales: 63.2,
      },
      {
        season: "FY2023/24",
        revenue: 243.7,
        wage_bill: 115.2,
        net_profit: 11.9,
        operating_profit: 20.0,
        pre_tax_profit: 21.3,
        net_debt: 4.7,
        equity: 196.3,
        profit_from_player_sales: 71.0,
      },
      {
        season: "FY2024/25",
        revenue: 320.8,
        wage_bill: 123.2,
        net_profit: 37.9,
        operating_profit: 59.1,
        pre_tax_profit: 58.6,
        net_debt: 11.1,
        equity: 248.2,
        profit_from_player_sales: 100.9,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Lazio ──────────────────────────────────────────────────────────────────
  {
    slug: "lazio",
    name: "SS Lazio",
    country: "Italy",
    league: "Serie A",
    city: "Rome",
    currency: "EUR",
    stadium: { name: "Stadio Olimpico", capacity: 70634, ownership: "Municipality of Rome / Italian Olympic Committee (leased)" },
    ownership: { summary: "Claudio Lotito (majority)", category: "SS Lazio SpA (listed: BIT: SSL)", fifty_plus_one: null },
    financials: {
      most_recent_year: "H1 FY2025/26 (Dec 2025)",
      revenue: 52.0,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: 111.3,
      data_notes: "Interim half-year report (6 months to 31 December 2025). Revenue reflects H1 only — not comparable to full-year figures. Net debt as at 31 December 2025. Full-year data: IFRS consolidated group (S.S. Lazio SpA + subsidiaries); primary full-year figures are FY2024/25. FY24/25 revenue fell sharply due to exit from Champions League (dropped to Europa League): TV/media revenue fell ca. €44m vs FY23/24. Net debt is primarily reverse-factoring and bank credit lines; no bonds.",
    },
    prior_year: {
      season: "FY2024/25",
      revenue: 146.0,
      wage_bill: 98.2,
      wage_to_revenue_pct: 67.2,
      operating_profit: -16.8,
      profit_from_player_sales: 11.1,
      pre_tax_profit: -21.0,
      net_debt: 66.3,
      net_profit: -17.2,
      equity: -16.8,
    },
    historical: [
      {
        season: "FY2023/24",
        revenue: 195.5,
        wage_bill: 116.6,
        net_profit: 38.5,
        operating_profit: 44.2,
        pre_tax_profit: 40.7,
        net_debt: 38.1,
        equity: 0.4,
        profit_from_player_sales: 40.9,
      },
      {
        season: "FY2024/25",
        revenue: 146.0,
        wage_bill: 98.2,
        net_profit: -17.2,
        operating_profit: -16.8,
        pre_tax_profit: -21.0,
        net_debt: 66.3,
        equity: -16.8,
        profit_from_player_sales: 11.1,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Fiorentina ─────────────────────────────────────────────────────────────
  {
    slug: "fiorentina",
    name: "ACF Fiorentina",
    country: "Italy",
    league: "Serie A",
    city: "Florence",
    currency: "EUR",
    stadium: { name: "Stadio Artemio Franchi", capacity: 43147, ownership: "Municipality of Florence (leased)" },
    ownership: { summary: "Rocco Commisso (100% via Mediacom Communications)", category: "ACF Fiorentina SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 198.6,
      wage_bill: 94.7,
      wage_to_revenue_pct: 47.7,
      net_profit: -23.2,
      total_liabilities: null,
      equity: 268.8,
      operating_profit: -17.6,
      profit_from_player_sales: 56.2,
      pre_tax_profit: -17.7,
      net_debt: -7.3,
      data_notes: "Individual entity (ACF Fiorentina Srl). No financial debt; net cash €7.3m. Revenue includes €56.2m player sale gains (Gonzalez to Juventus, Kayode to Brentford, Amrabat to Fenerbahce, Milenkovic to Nottingham Forest). FY24/25 EBIT worsened despite record player sales due to ~50% stadium capacity reduction (Fiesole terrace demolished June 2024 for Stadio Franchi renovation). Football sector payables (deferred player purchase instalments) surged to €91.4m — key liquidity pressure. Shareholder injected €5m capital in June 2025. No formal going concern warning but significant stadium uncertainty disclosed.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 199.9,
      wage_bill: 97.6,
      wage_to_revenue_pct: 48.8,
      operating_profit: -4.7,
      profit_from_player_sales: 26.1,
      pre_tax_profit: -4.2,
      net_debt: -22.3,
      net_profit: -6.0,
      equity: 287.1,
    },
    historical: [
      {
        season: "FY2022/23",
        revenue: 159.6,
        wage_bill: 86.7,
        net_profit: -19.5,
        operating_profit: -24.0,
        pre_tax_profit: -23.3,
        net_debt: -24.0,
        equity: 293.1,
        profit_from_player_sales: 7.7,
      },
      {
        season: "FY2023/24",
        revenue: 199.9,
        wage_bill: 97.6,
        net_profit: -6.0,
        operating_profit: -4.7,
        pre_tax_profit: -4.2,
        net_debt: -22.3,
        equity: 287.1,
        profit_from_player_sales: 26.1,
      },
      {
        season: "FY2024/25",
        revenue: 198.6,
        wage_bill: 94.7,
        net_profit: -23.2,
        operating_profit: -17.6,
        pre_tax_profit: -17.7,
        net_debt: -7.3,
        equity: 268.8,
        profit_from_player_sales: 56.2,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Bologna ────────────────────────────────────────────────────────────────
  {
    slug: "bologna",
    name: "Bologna FC 1909",
    country: "Italy",
    league: "Serie A",
    city: "Bologna",
    currency: "EUR",
    stadium: { name: "Renato Dall'Ara", capacity: 38279, ownership: "Municipality of Bologna (leased)" },
    ownership: { summary: "Joey Saputo (majority via Saputo Football Group)", category: "Bologna FC 1909 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 138.2,
      wage_bill: 84.1,
      wage_to_revenue_pct: 60.9,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: 22.6,
      profit_from_player_sales: null,
      pre_tax_profit: 19.6,
      net_debt: 18.8,
      data_notes: "First season in UEFA Champions League (2024/25), contributing to revenue growth.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 127.8,
      wage_bill: 71.1,
      wage_to_revenue_pct: 55.6,
      operating_profit: -7.0,
      profit_from_player_sales: null,
      pre_tax_profit: -8.1,
      net_debt: 19.7,
      net_profit: -10.4,
    },
    historical: [
      {
        season: "FY2021/22",
        revenue: 80.4,
        wage_bill: 67.6,
        net_profit: -46.7,
        operating_profit: -44.7,
        pre_tax_profit: -46.0,
        net_debt: 19.1,
        equity: 9.3,
        profit_from_player_sales: 15.2,
      },
      {
        season: "FY2022/23",
        revenue: 117.3,
        wage_bill: 69.1,
        net_profit: -16.3,
        operating_profit: -13.3,
        pre_tax_profit: -14.0,
        net_debt: 25.0,
        equity: 11.7,
        profit_from_player_sales: 34.5,
      },
      {
        season: "FY2023/24",
        revenue: 127.8,
        wage_bill: 71.1,
        net_profit: -10.4,
        operating_profit: -7.0,
        pre_tax_profit: -8.1,
        net_debt: 19.7,
      },
      {
        season: "FY2024/25",
        revenue: 138.2,
        wage_bill: 84.1,
        net_profit: null,
        operating_profit: 22.6,
        pre_tax_profit: 19.6,
        net_debt: 18.8,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Udinese ────────────────────────────────────────────────────────────────
  {
    slug: "udinese",
    name: "Udinese Calcio",
    country: "Italy",
    league: "Serie A",
    city: "Udine",
    currency: "EUR",
    stadium: { name: "Bluenergy Stadium", capacity: 25144, ownership: "Club-owned (Udinese Calcio SpA)" },
    ownership: { summary: "Pozzo family (Gino Pozzo, majority)", category: "Udinese Calcio SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 141.7,
      wage_bill: 42.1,
      wage_to_revenue_pct: 29.7,
      net_profit: 2.9,
      total_liabilities: null,
      equity: 115.1,
      operating_profit: 11.0,
      profit_from_player_sales: 72.3,
      pre_tax_profit: 4.0,
      net_debt: 56.5,
      data_notes: "Individual entity (Udinese Calcio SpA). Revenue includes €72.3m player sale gains (FY25). One of the lowest wage ratios in Serie A. Udinese uses declining-balance amortisation on player registrations (policy since 2014-15) — front-loads amortisation and generates larger plusvalenze; EBIT not directly comparable to peers using straight-line. Large patrimonio netto (€115.1m) underpinned by €97m stadium revaluation reserve. FIGC liquidity indicator breach at 30/06/2025 (0.69 vs 0.80 minimum). Post-balance-sheet: Guardia di Finanza tax assessment (PVC) disclosed; covering FY2019-22 — no material impact assessed. Pozzo family also own Watford FC.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 120.9,
      wage_bill: 41.0,
      wage_to_revenue_pct: 33.9,
      operating_profit: -2.9,
      profit_from_player_sales: 37.6,
      pre_tax_profit: -9.1,
      net_debt: 65.3,
      net_profit: -11.5,
      equity: 112.1,
    },
    historical: [
      {
        season: "FY2023/24",
        revenue: 120.9,
        wage_bill: 41.0,
        net_profit: -11.5,
        operating_profit: -2.9,
        pre_tax_profit: -9.1,
        net_debt: 65.3,
        equity: 112.1,
        profit_from_player_sales: 37.6,
      },
      {
        season: "FY2024/25",
        revenue: 141.7,
        wage_bill: 42.1,
        net_profit: 2.9,
        operating_profit: 11.0,
        pre_tax_profit: 4.0,
        net_debt: 56.5,
        equity: 115.1,
        profit_from_player_sales: 72.3,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Hellas Verona ──────────────────────────────────────────────────────────
  {
    slug: "hellas-verona",
    name: "Hellas Verona FC",
    country: "Italy",
    league: "Serie A",
    city: "Verona",
    currency: "EUR",
    stadium: { name: "Stadio Marcantonio Bentegodi", capacity: 39211, ownership: "Municipality of Verona (leased)" },
    ownership: { summary: "Renzo Rosso (majority, acquired 2020)", category: "Hellas Verona FC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 101.6,
      wage_bill: 43.3,
      wage_to_revenue_pct: 42.7,
      net_profit: -4.7,
      total_liabilities: null,
      equity: -7.0,
      operating_profit: -0.8,
      profit_from_player_sales: 31.6,
      pre_tax_profit: -2.8,
      net_debt: 89.3,
      data_notes: "Individual entity (Hellas Verona FC SpA). Negative equity in both FY2024 (−€2.2m) and FY2025 (−€7.0m); accumulated losses −€21.5m. Revenue heavily dependent on player sales (plusvalenze €31.6m = 31% of FY25 total revenue). 'Altri finanziatori' debt of €77.8m is predominantly deferred player purchase instalments owed to other clubs — only €13.5m is traditional bank debt. No formal going concern warning issued.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 115.3,
      wage_bill: 43.7,
      wage_to_revenue_pct: 37.9,
      operating_profit: 12.3,
      profit_from_player_sales: 45.4,
      pre_tax_profit: 8.1,
      net_debt: 89.0,
      net_profit: 3.9,
      equity: -2.2,
    },
    historical: [
      {
        season: "FY2023/24",
        revenue: 115.3,
        wage_bill: 43.7,
        net_profit: 3.9,
        operating_profit: 12.3,
        pre_tax_profit: 8.1,
        net_debt: 89.0,
        equity: -2.2,
        profit_from_player_sales: 45.4,
      },
      {
        season: "FY2024/25",
        revenue: 101.6,
        wage_bill: 43.3,
        net_profit: -4.7,
        operating_profit: -0.8,
        pre_tax_profit: -2.8,
        net_debt: 89.3,
        equity: -7.0,
        profit_from_player_sales: 31.6,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Torino ─────────────────────────────────────────────────────────────────
  {
    slug: "torino-fc",
    name: "Torino FC",
    country: "Italy",
    league: "Serie A",
    city: "Turin",
    currency: "EUR",
    stadium: { name: "Stadio Grande Torino", capacity: 28177, ownership: "Municipality of Turin (leased)" },
    ownership: { summary: "Urbano Cairo (majority via Cairo Communication)", category: "Torino FC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025 (Dec)",
      revenue: 122.5,
      wage_bill: 68.9,
      wage_to_revenue_pct: 56.2,
      net_profit: -13.1,
      total_liabilities: null,
      equity: 9.3,
      operating_profit: -12.5,
      profit_from_player_sales: 43.0,
      pre_tax_profit: -15.4,
      net_debt: 42.6,
      data_notes: "December fiscal year (calendar year end). Individual entity (Torino FC SpA). FY25 loss reflects lower player sale gains vs FY24 (€43.0m vs €58.5m) and ca. €13m negative impact from injured players (Zapata, others sidelined most of season). Shareholder loans from U.T. Communications (Cairo family): €4.7m current at 31/12/2025. No going concern warning.",
    },
    prior_year: {
      season: "FY2024 (Dec)",
      revenue: 134.5,
      wage_bill: 58.9,
      wage_to_revenue_pct: 43.8,
      operating_profit: 26.3,
      profit_from_player_sales: 58.5,
      pre_tax_profit: 26.3,
      net_debt: 43.5,
      net_profit: 10.4,
      equity: 17.7,
    },
    historical: [
      {
        season: "FY2022 (Dec)",
        revenue: 112.7,
        wage_bill: 65.7,
        net_profit: -6.8,
        operating_profit: -5.2,
        pre_tax_profit: -6.5,
        net_debt: 21.2,
        equity: 14.3,
        profit_from_player_sales: 38.3,
      },
      {
        season: "FY2023 (Dec)",
        revenue: 101.1,
        wage_bill: 55.7,
        net_profit: -9.6,
        operating_profit: -8.3,
        pre_tax_profit: -10.7,
        net_debt: 45.7,
        equity: 4.3,
        profit_from_player_sales: 23.2,
      },
      {
        season: "FY2024 (Dec)",
        revenue: 134.5,
        wage_bill: 58.9,
        net_profit: 10.4,
        operating_profit: 26.3,
        pre_tax_profit: 26.3,
        net_debt: 43.5,
        equity: 17.7,
        profit_from_player_sales: 58.5,
      },
      {
        season: "FY2025 (Dec)",
        revenue: 122.5,
        wage_bill: 68.9,
        net_profit: -13.1,
        operating_profit: -12.5,
        pre_tax_profit: -15.4,
        net_debt: 42.6,
        equity: 9.3,
        profit_from_player_sales: 43.0,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Genoa ──────────────────────────────────────────────────────────────────
  {
    slug: "genoa-cfc",
    name: "Genoa CFC",
    country: "Italy",
    league: "Serie A",
    city: "Genoa",
    currency: "EUR",
    stadium: { name: "Stadio Luigi Ferraris", capacity: 36599, ownership: "Jointly owned with Sampdoria; Genoa municipality" },
    ownership: { summary: "Passion For Green Capital Srl (majority, acquired late 2024; Romanian-backed; Dan Sucu predecessor sold to Passion For Green)", category: "Genoa CFC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 120.5,
      wage_bill: 62.4,
      wage_to_revenue_pct: 51.8,
      net_profit: -33.3,
      total_liabilities: null,
      equity: 18.0,
      operating_profit: -27.4,
      profit_from_player_sales: 0,
      pre_tax_profit: -33.0,
      net_debt: 140.5,
      data_notes: "Individual entity (Genoa CFC SpA) under new June fiscal year-end (changed from December under previous ownership). FY24/25 and FY23/24 are the first two years under new ownership (Passion For Green Capital). Historical data prior to FY23/24 is not comparable: (i) different fiscal year (Dec), (ii) consolidated group accounts, (iii) different owner (777 Partners). Cash flow statement shows nil player sale gains in both presented years. Capital increase of €40.3m completed in FY24/25; equity turned positive at €18.0m at 30/06/2025 following two large net losses. Net debt predominantly 'altri finanziatori' (€102.7m) plus bank debt (€40.1m) — high leverage relative to revenue scale.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 85.1,
      wage_bill: 33.8,
      wage_to_revenue_pct: 39.7,
      operating_profit: -31.8,
      profit_from_player_sales: 0,
      pre_tax_profit: -36.6,
      net_debt: 146.3,
      net_profit: -38.8,
      equity: 1.1,
    },
    historical: [
      {
        season: "FY2023/24",
        revenue: 85.1,
        wage_bill: 33.8,
        net_profit: -38.8,
        operating_profit: -31.8,
        pre_tax_profit: -36.6,
        net_debt: 146.3,
        equity: 1.1,
        profit_from_player_sales: 0,
      },
      {
        season: "FY2024/25",
        revenue: 120.5,
        wage_bill: 62.4,
        net_profit: -33.3,
        operating_profit: -27.4,
        pre_tax_profit: -33.0,
        net_debt: 140.5,
        equity: 18.0,
        profit_from_player_sales: 0,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Monza ──────────────────────────────────────────────────────────────────
  {
    slug: "ac-monza",
    name: "AC Monza",
    country: "Italy",
    league: "Serie A",
    city: "Monza",
    currency: "EUR",
    stadium: { name: "U-Power Stadium", capacity: 18568, ownership: "AC Monza SpA" },
    ownership: { summary: "Fininvest SpA (Berlusconi family)", category: "AC Monza SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024 (Dec)",
      revenue: 85.7,
      wage_bill: 78.0,
      wage_to_revenue_pct: 91.0,
      net_profit: -48.0,
      total_liabilities: null,
      equity: 23.1,
      operating_profit: -53.4,
      profit_from_player_sales: 22.6,
      pre_tax_profit: -54.2,
      net_debt: 10.3,
      data_notes: "December fiscal year. Individual entity (AC Monza S.p.A.), Italian OIC GAAP. Losses funded annually by Fininvest S.p.A. (Berlusconi family) via capital injections (cumulative ~€177m over FY22–24). Net loss each year is ~€6-7m better than pre-tax due to IRES tax consolidation compensation from Fininvest. No bank debt in any year; FY2024 net debt of €10.3m is entirely Factorit factoring facility secured against transfer receivables. FY2022 wage ratio of 182% is an accounting artefact (full-year top-flight wages against only H2 Serie A revenues). Relegated to Serie B at end of 2024/25 season.",
    },
    prior_year: {
      season: "FY2023 (Dec)",
      revenue: 68.3,
      wage_bill: 78.0,
      wage_to_revenue_pct: 114.2,
      operating_profit: -66.0,
      profit_from_player_sales: 0.0,
      pre_tax_profit: -66.9,
      net_debt: -1.7,
      net_profit: -60.3,
      equity: 20.0,
    },
    historical: [
      {
        season: "FY2022 (Dec)",
        revenue: 32.7,
        wage_bill: 59.6,
        net_profit: -65.4,
        operating_profit: -72.8,
        pre_tax_profit: -72.9,
        net_debt: -6.2,
        equity: 18.3,
        profit_from_player_sales: 0.0,
      },
      {
        season: "FY2023 (Dec)",
        revenue: 68.3,
        wage_bill: 78.0,
        net_profit: -60.3,
        operating_profit: -66.0,
        pre_tax_profit: -66.9,
        net_debt: -1.7,
        equity: 20.0,
        profit_from_player_sales: 0.0,
      },
      {
        season: "FY2024 (Dec)",
        revenue: 85.7,
        wage_bill: 78.0,
        net_profit: -48.0,
        operating_profit: -53.4,
        pre_tax_profit: -54.2,
        net_debt: 10.3,
        equity: 23.1,
        profit_from_player_sales: 22.6,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Cagliari ───────────────────────────────────────────────────────────────
  {
    slug: "cagliari-calcio",
    name: "Cagliari Calcio",
    country: "Italy",
    league: "Serie A",
    city: "Cagliari",
    currency: "EUR",
    stadium: { name: "Unipol Domus", capacity: 16416, ownership: "Municipality of Cagliari (leased)" },
    ownership: { summary: "Tommaso Giulini (majority)", category: "Cagliari Calcio SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 70.8,
      wage_bill: 39.0,
      wage_to_revenue_pct: 55.1,
      net_profit: -7.7,
      total_liabilities: null,
      equity: 3.1,
      operating_profit: -6.3,
      profit_from_player_sales: 7.0,
      pre_tax_profit: -8.0,
      net_debt: 56.7,
      data_notes: "Year ending 30 June 2025. Individual entity (Cagliari Calcio SpA), Italian OIC GAAP. Revenue (Valore della Produzione) includes TV rights €32.5m, ticketing/matchday €2.1m, season tickets €4.0m, sponsorship €7.4m, advertising €6.1m, player loan fees €0.5m, player sale gains (plusvalenze) €7.0m, and other revenues €5.6m. Net profit is €0.4m better than pre-tax due to tax credit €0.4m. Net debt: bank debt €39.7m (short-term €23.7m + long-term €16.0m) plus other financial liabilities less cash €0.1m = €56.7m. Balance sheet total assets €146.8m; intangible assets (player rights) €49.3m. Club remained in Serie A for 2025/26.",
    },
    prior_year: null,
    historical: [
      {
        season: "FY2024/25 (Jun)",
        revenue: 70.8,
        wage_bill: 39.0,
        net_profit: -7.7,
        operating_profit: -6.3,
        pre_tax_profit: -8.0,
        net_debt: 56.7,
        equity: 3.1,
        profit_from_player_sales: 7.0,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Sassuolo ───────────────────────────────────────────────────────────────
  {
    slug: "us-sassuolo",
    name: "US Sassuolo",
    country: "Italy",
    league: "Serie B",
    city: "Sassuolo",
    currency: "EUR",
    stadium: { name: "Mapei Stadium – Città del Tricolore", capacity: 21353, ownership: "Mapei SpA" },
    ownership: { summary: "Mapei SpA (Giorgio Squinzi heirs)", category: "US Sassuolo Calcio Srl", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025 (Dec)",
      revenue: 70.7,
      wage_bill: 59.1,
      wage_to_revenue_pct: 83.6,
      net_profit: -38.8,
      total_liabilities: null,
      equity: 25.8,
      operating_profit: -47.9,
      profit_from_player_sales: 2.4,
      pre_tax_profit: -50.6,
      net_debt: 56.7,
      data_notes: "December fiscal year (calendar year end). Individual entity (US Sassuolo Calcio Srl). Going concern — continuation explicitly dependent on Mapei SpA 'formal and irrevocable' loss-coverage commitment. Relegated to Serie B end of 2023/24. Revenue collapse driven by relegation and near-zero player sale gains (€2.4m in FY25 vs €51m in FY22/23). NFP improved from €119.9m to €56.7m primarily through Mapei converting €45m cash-pooling debt to equity (December 2025). Mapei cash-pool is the dominant NFP component. Guardia di Finanza investigation (false corporate communications 2019-21) ongoing — management assesses no material impact.",
    },
    prior_year: {
      season: "FY2024 (Dec)",
      revenue: 102.1,
      wage_bill: 63.4,
      wage_to_revenue_pct: 62.1,
      operating_profit: -23.7,
      profit_from_player_sales: 32.7,
      pre_tax_profit: -27.1,
      net_debt: 85.9,
      net_profit: -22.1,
      equity: 19.5,
    },
    historical: [
      {
        season: "FY2022 (Dec)",
        revenue: 139.0,
        wage_bill: 63.7,
        net_profit: 1.4,
        operating_profit: 6.6,
        pre_tax_profit: 4.6,
        net_debt: 108.4,
        equity: 27.7,
        profit_from_player_sales: 51.3,
      },
      {
        season: "FY2023 (Dec)",
        revenue: 140.2,
        wage_bill: 65.9,
        net_profit: -7.1,
        operating_profit: -2.7,
        pre_tax_profit: -6.6,
        net_debt: 119.9,
        equity: 20.7,
        profit_from_player_sales: 51.2,
      },
      {
        season: "FY2024 (Dec)",
        revenue: 102.1,
        wage_bill: 63.4,
        net_profit: -22.1,
        operating_profit: -23.7,
        pre_tax_profit: -27.1,
        net_debt: 85.9,
        equity: 19.5,
        profit_from_player_sales: 32.7,
      },
      {
        season: "FY2025 (Dec)",
        revenue: 70.7,
        wage_bill: 59.1,
        net_profit: -38.8,
        operating_profit: -47.9,
        pre_tax_profit: -50.6,
        net_debt: 56.7,
        equity: 25.8,
        profit_from_player_sales: 2.4,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Parma ──────────────────────────────────────────────────────────────────
  {
    slug: "parma-calcio",
    name: "Parma Calcio 1913",
    country: "Italy",
    league: "Serie A",
    city: "Parma",
    currency: "EUR",
    stadium: { name: "Stadio Ennio Tardini", capacity: 22352, ownership: "Parma Calcio 1913 SpA" },
    ownership: { summary: "Krause Group (Kyle Krause, majority)", category: "Parma Calcio 1913 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025 (Dec)",
      revenue: 125.4,
      wage_bill: 60.9,
      wage_to_revenue_pct: 48.6,
      net_profit: -1.8,
      total_liabilities: null,
      equity: 32.4,
      operating_profit: -0.3,
      profit_from_player_sales: 69.5,
      pre_tax_profit: -0.3,
      net_debt: 57.1,
      data_notes: "December fiscal year (calendar year end). Individual entity. Going concern — continuation dependent on Krause Group Italia annual support letters (FY25 letter dated 19 February 2026). FY25 = first full Serie A season after promotion; near-breakeven EBIT driven by €69.5m player sale gains (Bonny Ange-Yoan to Inter, Leoni to Liverpool et al.) — exceptional and not representative of normalised trading. Net debt of €57.1m includes €60.6m Krause subordinated interest-free loans (economically quasi-equity; if excluded, NFP ≈ net cash). Cumulative Krause injections to 31/12/2025: €437.8m (€377.3m converted to equity; €60.6m still as debt). FY22–24 reflect Serie B revenue base with Krause-funded wage structure producing wage/revenue ratios well above 100%.",
    },
    prior_year: {
      season: "FY2024 (Dec)",
      revenue: 41.5,
      wage_bill: 49.2,
      wage_to_revenue_pct: 118.7,
      operating_profit: -64.4,
      profit_from_player_sales: null,
      pre_tax_profit: -64.4,
      net_debt: 33.6,
      net_profit: -63.4,
      equity: 20.1,
    },
    historical: [
      {
        season: "FY2022 (Dec)",
        revenue: 32.5,
        wage_bill: 53.9,
        net_profit: -96.5,
        operating_profit: -96.4,
        pre_tax_profit: -96.5,
        net_debt: 49.2,
        equity: 15.0,
      },
      {
        season: "FY2023 (Dec)",
        revenue: 28.9,
        wage_bill: 43.8,
        net_profit: -80.5,
        operating_profit: -80.4,
        pre_tax_profit: -80.5,
        net_debt: 44.1,
        equity: 19.7,
        profit_from_player_sales: 3.7,
      },
      {
        season: "FY2024 (Dec)",
        revenue: 41.5,
        wage_bill: 49.2,
        net_profit: -63.4,
        operating_profit: -64.4,
        pre_tax_profit: -64.4,
        net_debt: 33.6,
        equity: 20.1,
      },
      {
        season: "FY2025 (Dec)",
        revenue: 125.4,
        wage_bill: 60.9,
        net_profit: -1.8,
        operating_profit: -0.3,
        pre_tax_profit: -0.3,
        net_debt: 57.1,
        equity: 32.4,
        profit_from_player_sales: 69.5,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Cremonese ──────────────────────────────────────────────────────────────
  {
    slug: "us-cremonese",
    name: "US Cremonese",
    country: "Italy",
    league: "Serie B",
    city: "Cremona",
    currency: "EUR",
    stadium: { name: "Giovanni Zini", capacity: 16003, ownership: "Cremonese SpA" },
    ownership: { summary: "Giovanni Arvedi (majority via Acciaieria Arvedi SpA)", category: "Unione Sportiva Cremonese SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 57.4,
      wage_bill: 38.6,
      wage_to_revenue_pct: 67.2,
      net_profit: -7.0,
      total_liabilities: null,
      equity: 3.7,
      operating_profit: -8.1,
      profit_from_player_sales: 3.0,
      pre_tax_profit: -8.1,
      net_debt: -1.7,
      data_notes: "Individual entity (US Cremonese SpA). Essentially debt-free (net cash of €1.7m). FY25 loss partly driven by promotion bonuses (premi NOIF) accrued on second Serie A promotion in June 2025 — FY25 season was in Serie B. FIGC indicator breaches at 30/06/2025 (liquidity AC/PC 0.457 vs 0.70 minimum; CLA/R 0.992 vs 0.80 minimum); management characterises as seasonal. FY22/23 was first Serie A season; revenue surge to €89.1m driven by TV rights. Relegated end of FY23.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 57.7,
      wage_bill: 29.1,
      wage_to_revenue_pct: 50.5,
      operating_profit: 3.6,
      profit_from_player_sales: 1.4,
      pre_tax_profit: 3.5,
      net_debt: 0.7,
      net_profit: 2.0,
      equity: 10.7,
    },
    historical: [
      {
        season: "FY2021/22",
        revenue: 28.1,
        wage_bill: 20.8,
        net_profit: -2.9,
        operating_profit: -1.9,
        pre_tax_profit: -2.0,
        net_debt: 3.1,
        equity: 1.5,
        profit_from_player_sales: 0.0,
      },
      {
        season: "FY2022/23",
        revenue: 89.1,
        wage_bill: 44.2,
        net_profit: 7.2,
        operating_profit: 10.0,
        pre_tax_profit: 9.9,
        net_debt: 0.7,
        equity: 8.7,
        profit_from_player_sales: 0.2,
      },
      {
        season: "FY2023/24",
        revenue: 57.7,
        wage_bill: 29.1,
        net_profit: 2.0,
        operating_profit: 3.6,
        pre_tax_profit: 3.5,
        net_debt: 0.7,
        equity: 10.7,
        profit_from_player_sales: 1.4,
      },
      {
        season: "FY2024/25",
        revenue: 57.4,
        wage_bill: 38.6,
        net_profit: -7.0,
        operating_profit: -8.1,
        pre_tax_profit: -8.1,
        net_debt: -1.7,
        equity: 3.7,
        profit_from_player_sales: 3.0,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },


  // ─── Como 1907 ──────────────────────────────────────────────────────────────
  {
    slug: "como-1907",
    name: "Como 1907",
    country: "Italy",
    league: "Serie A",
    city: "Como",
    currency: "EUR",
    stadium: { name: "Stadio Giuseppe Sinigaglia", capacity: 10500, ownership: "Municipality of Como (leased)" },
    ownership: { summary: "Sent Entertainment Ltd (Robert Hartono family, ~80%)", category: "Como 1907 SRL", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 55.4,
      wage_bill: 85.7,
      wage_to_revenue_pct: 154.7,
      net_profit: -105.0,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: -105.1,
      net_debt: -7.7,
      data_notes: "First Serie A season (2024/25) following promotion. Significant investment by Indonesian Hartono family driving heavy losses. Pre-tax loss €105.1m; net loss €105.0m. Net cash of €7.7m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 9.8,
      wage_bill: 33.6,
      wage_to_revenue_pct: 342.9,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_debt: -3.3,
      net_profit: -47.8,
    },
    historical: [
      { season: "FY2023/24", revenue: 9.8, wage_bill: 33.6, net_profit: -47.8, net_debt: -3.3 },
      { season: "FY2024/25", revenue: 55.4, wage_bill: 85.7, net_profit: -105.0, pre_tax_profit: -105.1, net_debt: -7.7 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Venezia FC ─────────────────────────────────────────────────────────────
  {
    slug: "venezia-fc",
    name: "Venezia FC",
    country: "Italy",
    league: "Serie A",
    city: "Venice",
    currency: "EUR",
    stadium: { name: "Stadio Pier Luigi Penzo", capacity: 7450, ownership: "Municipality of Venice (leased)" },
    ownership: { summary: "American-led investor consortium (majority)", category: "Venezia FC SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 51.8,
      wage_bill: 48.6,
      wage_to_revenue_pct: 93.8,
      net_profit: -35.9,
      total_liabilities: null,
      equity: null,
      operating_profit: -35.0,
      profit_from_player_sales: null,
      pre_tax_profit: -35.8,
      net_debt: -5.0,
      data_notes: "Serie A return after promotion from Serie B in 2023/24. Smallest stadium capacity in Serie A (7,450 seats). Net cash of €5.0m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 20.0,
      wage_bill: 33.5,
      wage_to_revenue_pct: 167.5,
      operating_profit: -42.1,
      profit_from_player_sales: null,
      pre_tax_profit: -43.8,
      net_debt: 1.5,
      net_profit: -43.7,
    },
    historical: [
      { season: "FY2023/24", revenue: 20.0, wage_bill: 33.5, net_profit: -43.7 },
      { season: "FY2024/25", revenue: 51.8, wage_bill: 48.6, net_profit: -35.9 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── US Lecce ────────────────────────────────────────────────────────────────
  {
    slug: "us-lecce",
    name: "US Lecce",
    country: "Italy",
    league: "Serie A",
    city: "Lecce",
    currency: "EUR",
    stadium: { name: "Stadio Via del Mare", capacity: 31533, ownership: "Municipality of Lecce (leased)" },
    ownership: { summary: "Sticchi Damiani family (majority; Saverio Sticchi Damiani, president)", category: "Unione Sportiva Lecce SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 108.0,
      wage_bill: 14.7,
      wage_to_revenue_pct: 13.6,
      net_profit: 20.2,
      total_liabilities: null,
      equity: null,
      operating_profit: 24.5,
      profit_from_player_sales: 52.5,
      pre_tax_profit: 23.8,
      net_debt: 3.2,
      data_notes: "Revenue heavily inflated by player sale gains (€52.5m plusvalenze). Underlying revenue excluding transfers ≈ €55.4m. TV rights €33.1m (Serie A). Relegated from Serie A at end of 2024/25. Net debt €3.2m (bank €3.0m + other financial lenders €5.8m less cash €5.6m).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 85.3,
      wage_bill: 11.6,
      wage_to_revenue_pct: 13.6,
      operating_profit: 18.0,
      profit_from_player_sales: null,
      pre_tax_profit: 16.8,
      net_debt: -2.16,
      net_profit: 14.0,
    },
    historical: [
      { season: "FY2023/24", revenue: 85.3, wage_bill: 11.6, net_profit: 14.0, net_debt: -2.16 },
      { season: "FY2024/25", revenue: 108.0, wage_bill: 14.7, net_profit: 20.2 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── AC Reggiana ─────────────────────────────────────────────────────────────
  {
    slug: "ac-reggiana",
    name: "AC Reggiana 1919",
    country: "Italy",
    league: "Serie B",
    city: "Reggio Emilia",
    currency: "EUR",
    stadium: { name: "Mapei Stadium – Città del Tricolore", capacity: 21584, ownership: "Mapei SpA" },
    ownership: { summary: "Locally owned (no external parent group)", category: "AC Reggiana 1919 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 17.5,
      wage_bill: 11.4,
      wage_to_revenue_pct: 65.1,
      net_profit: -1.8,
      total_liabilities: null,
      equity: null,
      operating_profit: -1.8,
      profit_from_player_sales: null,
      pre_tax_profit: -1.8,
      net_debt: -0.1,
      data_notes: "Net cash position. Shares Mapei Stadium with Sassuolo. No external parent company; independently owned.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 18.6,
      wage_bill: 11.0,
      wage_to_revenue_pct: 59.1,
      operating_profit: 0.1,
      profit_from_player_sales: null,
      pre_tax_profit: 0.1,
      net_debt: -1.4,
      net_profit: -0.4,
    },
    historical: [
      { season: "FY2023/24", revenue: 18.6, wage_bill: 11.0, net_profit: -0.4 },
      { season: "FY2024/25", revenue: 17.5, wage_bill: 11.4, net_profit: -1.8 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── US Catanzaro ────────────────────────────────────────────────────────────
  {
    slug: "us-catanzaro",
    name: "US Catanzaro 1929",
    country: "Italy",
    league: "Serie B",
    city: "Catanzaro",
    currency: "EUR",
    stadium: { name: "Stadio Nicola Ceravolo", capacity: 16000, ownership: "Municipality of Catanzaro (leased)" },
    ownership: { summary: "AZ S.p.A. / Noto S.p.A. (majority)", category: "Unione Sportiva Catanzaro 1929 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2023 (Dec)",
      revenue: 9.3,
      wage_bill: 9.6,
      wage_to_revenue_pct: 103.2,
      net_profit: -4.3,
      total_liabilities: null,
      equity: null,
      operating_profit: -5.4,
      profit_from_player_sales: null,
      pre_tax_profit: -5.4,
      net_debt: -2.6,
      data_notes: "December fiscal year. Net cash of €2.6m. Wages exceed revenue, typical of smaller Serie B club.",
    },
    prior_year: {
      season: "FY2022 (Dec)",
      revenue: 4.3,
      wage_bill: 5.8,
      wage_to_revenue_pct: 134.9,
      operating_profit: -4.5,
      profit_from_player_sales: null,
      pre_tax_profit: -4.5,
      net_debt: -1.7,
      net_profit: -3.6,
    },
    historical: [
      { season: "FY2022 (Dec)", revenue: 4.3, wage_bill: 5.8, net_profit: -3.6 },
      { season: "FY2023 (Dec)", revenue: 9.3, wage_bill: 9.6, net_profit: -4.3 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Modena FC ───────────────────────────────────────────────────────────────
  {
    slug: "modena-fc",
    name: "Modena FC 2018",
    country: "Italy",
    league: "Serie B",
    city: "Modena",
    currency: "EUR",
    stadium: { name: "Stadio Alberto Braglia", capacity: 21151, ownership: "Municipality of Modena (leased)" },
    ownership: { summary: "Rivetex Srl (Italian holding company, majority)", category: "Modena F.C. 2018 Srl", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 14.0,
      wage_bill: 16.4,
      wage_to_revenue_pct: 117.1,
      net_profit: -11.6,
      total_liabilities: null,
      equity: null,
      operating_profit: -15.0,
      profit_from_player_sales: null,
      pre_tax_profit: -15.0,
      net_debt: -4.9,
      data_notes: "Net cash of €4.9m. Net loss reduced by €3.4m tax benefit from fiscal consolidation with parent Rivetex Srl. Losses funded by shareholder capital injections (€19.4m in FY2025). Bank debt negligible (€0.9k).",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 16.8,
      wage_bill: 13.6,
      wage_to_revenue_pct: 81.0,
      operating_profit: -8.1,
      profit_from_player_sales: null,
      pre_tax_profit: -8.1,
      net_debt: 2.88,
      net_profit: -6.5,
    },
    historical: [
      { season: "FY2023/24", revenue: 16.8, wage_bill: 13.6, net_profit: -6.5, net_debt: 2.88 },
      { season: "FY2024/25", revenue: 14.0, wage_bill: 16.4, net_profit: -11.6 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── SS Juve Stabia ──────────────────────────────────────────────────────────
  {
    slug: "juve-stabia",
    name: "SS Juve Stabia",
    country: "Italy",
    league: "Serie B",
    city: "Castellammare di Stabia",
    currency: "EUR",
    stadium: { name: "Stadio Romeo Menti", capacity: 9040, ownership: "Municipality of Castellammare di Stabia (leased)" },
    ownership: { summary: "Brera Holdings PLC (Nasdaq: BREA, majority) alongside XX Settembre Holding SRL", category: "SS Juve Stabia SRL", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 12.6,
      wage_bill: 11.4,
      wage_to_revenue_pct: 90.5,
      net_profit: -7.6,
      total_liabilities: null,
      equity: null,
      operating_profit: -7.2,
      profit_from_player_sales: null,
      pre_tax_profit: -7.3,
      net_debt: 0.2,
      data_notes: "Owned by Nasdaq-listed Brera Holdings PLC. Net debt: bank €0.2m + shareholder loans to controllanti €0.4m, less cash €0.4m. Negative equity (€-3.9m). Going concern dependency on shareholder support.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 5.0,
      wage_bill: 3.5,
      wage_to_revenue_pct: 70.0,
      operating_profit: -0.6,
      profit_from_player_sales: null,
      pre_tax_profit: -0.7,
      net_debt: 0.1,
      net_profit: -0.8,
    },
    historical: [
      { season: "FY2023/24", revenue: 5.0, wage_bill: 3.5, net_profit: -0.8 },
      { season: "FY2024/25", revenue: 12.6, wage_bill: 11.4, net_profit: -7.6 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Delfino Pescara ─────────────────────────────────────────────────────────
  {
    slug: "delfino-pescara",
    name: "Delfino Pescara 1936",
    country: "Italy",
    league: "Serie B",
    city: "Pescara",
    currency: "EUR",
    stadium: { name: "Stadio Adriatico-Giovanni Cornacchia", capacity: 20476, ownership: "Municipality of Pescara (leased)" },
    ownership: { summary: "Delfino Capital Srl (majority)", category: "Delfino Pescara 1936 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 8.1,
      wage_bill: 4.9,
      wage_to_revenue_pct: 60.5,
      net_profit: -3.9,
      total_liabilities: null,
      equity: null,
      operating_profit: -3.4,
      profit_from_player_sales: null,
      pre_tax_profit: -3.9,
      net_debt: 2.4,
      data_notes: "Competed in Serie C during 2024/25; promoted to Serie B for 2025/26. Net debt €2.4m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 8.9,
      wage_bill: 4.7,
      wage_to_revenue_pct: 52.8,
      operating_profit: -2.2,
      profit_from_player_sales: null,
      pre_tax_profit: -2.9,
      net_debt: 5.1,
      net_profit: -2.9,
    },
    historical: [
      { season: "FY2023/24", revenue: 8.9, wage_bill: 4.7, net_profit: -2.9 },
      { season: "FY2024/25", revenue: 8.1, wage_bill: 4.9, net_profit: -3.9 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Calcio Padova ───────────────────────────────────────────────────────────
  {
    slug: "calcio-padova",
    name: "Calcio Padova",
    country: "Italy",
    league: "Serie B",
    city: "Padua",
    currency: "EUR",
    stadium: { name: "Stadio Euganeo", capacity: 32420, ownership: "Municipality of Padua (leased)" },
    ownership: { summary: "J4A Holding II SARL (Luxembourg, majority)", category: "Calcio Padova SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 5.0,
      wage_bill: 6.3,
      wage_to_revenue_pct: 126.0,
      net_profit: -6.5,
      total_liabilities: null,
      equity: null,
      operating_profit: -6.4,
      profit_from_player_sales: null,
      pre_tax_profit: -6.5,
      net_debt: 0.2,
      data_notes: "Competed in Serie C during 2024/25; promoted to Serie B for 2025/26. Wages exceed revenue; losses funded by Luxembourg holding company. Net debt €0.2m.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 8.0,
      wage_bill: 5.7,
      wage_to_revenue_pct: 71.3,
      operating_profit: -2.4,
      profit_from_player_sales: null,
      pre_tax_profit: -2.4,
      net_debt: 0.0,
      net_profit: -2.4,
    },
    historical: [
      { season: "FY2023/24", revenue: 8.0, wage_bill: 5.7, net_profit: -2.4 },
      { season: "FY2024/25", revenue: 5.0, wage_bill: 6.3, net_profit: -6.5 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── Virtus Entella ──────────────────────────────────────────────────────────
  {
    slug: "virtus-entella",
    name: "Virtus Entella",
    country: "Italy",
    league: "Serie B",
    city: "Chiavari",
    currency: "EUR",
    stadium: { name: "Stadio Comunale di Chiavari", capacity: 7000, ownership: "Municipality of Chiavari" },
    ownership: { summary: "Duferco Travi e Profilati SpA (70%, acquired June 2025)", category: "Virtus Entella SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 6.5,
      wage_bill: 8.5,
      wage_to_revenue_pct: 130.8,
      net_profit: -7.3,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: -7.3,
      net_debt: -1.0,
      data_notes: "Net cash of €1.0m. Competed in Serie C during 2024/25; promoted to Serie B for 2025/26. Duferco (Italian steel group) acquired 70% stake in June 2025.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 3.9,
      wage_bill: 7.2,
      wage_to_revenue_pct: 184.6,
      operating_profit: -8.2,
      profit_from_player_sales: null,
      pre_tax_profit: -8.2,
      net_debt: 2.9,
      net_profit: null,
    },
    historical: [
      { season: "FY2023/24", revenue: 3.9, wage_bill: 7.2, net_profit: null },
      { season: "FY2024/25", revenue: 6.5, wage_bill: 8.5, net_profit: -7.3 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── US Avellino ─────────────────────────────────────────────────────────────
  {
    slug: "us-avellino",
    name: "US Avellino 1912",
    country: "Italy",
    league: "Serie B",
    city: "Avellino",
    currency: "EUR",
    stadium: { name: "Stadio Partenio-Adriano Lombardi", capacity: 25676, ownership: "Municipality of Avellino (leased)" },
    ownership: { summary: "SG Flat Finance Holding SpA (majority)", category: "Unione Sportiva Avellino 1912 SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024 (Dec)",
      revenue: 8.5,
      wage_bill: 10.7,
      wage_to_revenue_pct: 125.9,
      net_profit: -5.3,
      total_liabilities: null,
      equity: null,
      operating_profit: -6.5,
      profit_from_player_sales: null,
      pre_tax_profit: -6.6,
      net_debt: -0.4,
      data_notes: "December fiscal year. Net cash of €0.4m. Wages significantly exceed revenue.",
    },
    prior_year: {
      season: "FY2023 (Dec)",
      revenue: 6.3,
      wage_bill: 8.4,
      wage_to_revenue_pct: 133.3,
      operating_profit: -5.4,
      profit_from_player_sales: null,
      pre_tax_profit: -5.5,
      net_debt: -0.2,
      net_profit: -4.4,
    },
    historical: [
      { season: "FY2023 (Dec)", revenue: 6.3, wage_bill: 8.4, net_profit: -4.4 },
      { season: "FY2024 (Dec)", revenue: 8.5, wage_bill: 10.7, net_profit: -5.3 },
    ],
    tm_squad_value_eur_m: null,
    data_status: "EXTRACTED",
    volatility_tier: null,
  },

  // ─── SSC Bari ────────────────────────────────────────────────────────────────
  {
    slug: "ssc-bari",
    name: "SSC Bari",
    country: "Italy",
    league: "Serie B",
    city: "Bari",
    currency: "EUR",
    stadium: { name: "Stadio San Nicola", capacity: 58270, ownership: "Municipality of Bari (leased)" },
    ownership: { summary: "Filmauro Srl (De Laurentiis family, sole shareholder)", category: "Società Sportiva Calcio Bari SpA", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024/25 (Jun)",
      revenue: 18.1,
      wage_bill: 14.9,
      wage_to_revenue_pct: 82.5,
      net_profit: -5.9,
      total_liabilities: 21.5,
      equity: -6.7,
      operating_profit: -7.4,
      profit_from_player_sales: null,
      pre_tax_profit: -7.4,
      net_debt: 8.5,
      data_notes: "Individual entity (SSC Bari SpA), Italian OIC GAAP. June fiscal year. Sole shareholder Filmauro Srl (De Laurentiis family — also majority owner of SSC Napoli; UEFA multi-club ownership rules require structural separation). Financial debt is entirely shareholder loans from Filmauro (€9.7m) plus intercompany payables to parent (€0.3m); no bank debt. Net loss reduced from pre-tax €7.4m to €5.9m by a €1.5m tax benefit via fiscal consolidation with Filmauro. Negative equity (−€6.7m) reflects accumulated losses of −€7.5m partially offset by shareholder coverage injections of €6.6m. Player disposal proceeds negligible (€0.3m cash inflow from intangible disinvestments). Revenue decline from FY2023/24 (€23.5m) driven by lower 'altri ricavi e proventi'. Club incorporated July 2018; FY2024/25 is the 7th set of accounts.",
    },
    prior_year: {
      season: "FY2023/24",
      revenue: 23.5,
      wage_bill: 16.3,
      wage_to_revenue_pct: 69.4,
      operating_profit: -4.2,
      profit_from_player_sales: null,
      pre_tax_profit: -4.1,
      net_debt: 9.7,
      net_profit: -3.5,
      equity: -6.5,
    },
    historical: [
      {
        season: "FY2023/24",
        revenue: 23.5,
        wage_bill: 16.3,
        net_profit: -3.5,
        operating_profit: -4.2,
        pre_tax_profit: -4.1,
        net_debt: 9.7,
        equity: -6.5,
      },
      {
        season: "FY2024/25",
        revenue: 18.1,
        wage_bill: 14.9,
        net_profit: -5.9,
        operating_profit: -7.4,
        pre_tax_profit: -7.4,
        net_debt: 8.5,
        equity: -6.7,
      },
    ],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: null,
  },

];
