export type Takeaway = {
  text: string;
  sentiment: "positive" | "negative" | "neutral";
};

export const KEY_TAKEAWAYS: Record<string, Takeaway[]> = {
  arsenal: [
    { text: "Revenue more than doubled from £342m (FY22) to £690m (FY25), driven by Champions League returns and commercial growth.", sentiment: "positive" },
    { text: "Operating profit was positive in FY22 (£61m) and FY23 (£96m), but swung to a loss from FY24 onwards as player amortisation increased.", sentiment: "neutral" },
    { text: "Net position reversed sharply: the club held net cash in FY22 and FY23 but carried £302m of net debt by FY25.", sentiment: "negative" },
    { text: "Pre-tax losses in all four years despite strong revenue growth, reflecting the cost of sustained squad investment.", sentiment: "negative" },
  ],
  "aston-villa": [
    { text: "Revenue nearly tripled from £108m (FY22) to £310m (FY25) as the club returned to European football.", sentiment: "positive" },
    { text: "Wage ratio of 115% in FY22 — wages almost double revenue — reflects the financial hangover from relegation.", sentiment: "negative" },
    { text: "Net debt fell from £190m (FY24) to £149m (FY25), the only meaningful positive trend on the balance sheet.", sentiment: "positive" },
    { text: "Operating losses in all four years; the club has not generated a profit from operations in any year reviewed.", sentiment: "negative" },
  ],
  brentford: [
    { text: "Pre-tax profits of £29.9m (FY22) and £9.2m (FY23) made Brentford one of the few profitable PL clubs in those years.", sentiment: "positive" },
    { text: "Wage ratio rose from 48% (FY22) to ~76% (FY25) — the steepest sustained increase in the dataset.", sentiment: "negative" },
    { text: "Net cash of ~£15m in FY22/FY23 swung to £130m of net debt by FY25 as the club invested in the squad.", sentiment: "negative" },
    { text: "Revenue grew modestly from £141m (FY22) to £173m (FY25), limiting the club's ability to absorb rising costs.", sentiment: "neutral" },
  ],
  brighton: [
    { text: "FY23 produced an operating profit of £139.5m and a pre-tax profit of £142m — the highest in the club's history — driven by £121m of player sales.", sentiment: "positive" },
    { text: "Net debt swung from net cash of £15m (FY23) to £296m (FY25), a significant deterioration despite the profitable trading period.", sentiment: "negative" },
    { text: "Revenue was broadly flat at £203-222m across FY23-FY25, suggesting commercial growth has not kept pace with costs.", sentiment: "neutral" },
    { text: "Operating losses returned in FY24 and FY25 as amortisation on new signings accelerated.", sentiment: "negative" },
  ],
  burnley: [
    { text: "FY22 was the only profitable year in the dataset: pre-tax profit of £36.3m, boosted by £54m of player sales while still in the Premier League.", sentiment: "positive" },
    { text: "Revenue halved from £123m (FY22, PL) to £65m (FY23, Championship) following relegation.", sentiment: "negative" },
    { text: "Net debt grew from £32m (FY22) to £104m (FY25) — more than trebling over the four-year period.", sentiment: "negative" },
  ],
  chelsea: [
    { text: "FY25 operating loss of £308m is the largest recorded by any English football club.", sentiment: "negative" },
    { text: "FY24 pre-tax profit of £128.4m was almost entirely generated by £152.5m of player sales, not operational performance.", sentiment: "neutral" },
    { text: "Revenue peaked at £512.5m in FY23 and has not recovered to that level since.", sentiment: "negative" },
    { text: "Net debt position was not externally disclosed in FY22 or FY23; by FY25 the club reported net cash of £49m following owner equity injections.", sentiment: "neutral" },
  ],
  "crystal-palace": [
    { text: "Operating losses were broadly consistent at ~£20m per year in FY22–FY24, representing a structural annual deficit before player trading.", sentiment: "negative" },
    { text: "Net debt jumped from net cash of £8m (FY23) to £149m (FY24) — a swing of £157m in a single year.", sentiment: "negative" },
    { text: "FY25 pre-tax profit of £8m was driven by £66m of player sales; absent that trading income, losses would have been significant.", sentiment: "neutral" },
    { text: "Revenue grew steadily from £160m (FY22) to £195m (FY25) — consistent but not transformative growth.", sentiment: "neutral" },
  ],
  everton: [
    { text: "Net debt reached £1,018m in FY24 — the highest recorded by any English club — reflecting new stadium construction costs.", sentiment: "negative" },
    { text: "Net debt fell sharply to £389m in FY25 as the stadium opened and financing was restructured.", sentiment: "positive" },
    { text: "Wage ratio improved from 92% (FY23) to ~77% (FY25) as the club gradually reduced its cost base.", sentiment: "positive" },
    { text: "Pre-tax losses in all four years; the FY23 loss of £89m was the worst during the PSR scrutiny period.", sentiment: "negative" },
  ],
  fulham: [
    { text: "FY22 wage ratio of 126% — Championship revenues supporting near-Premier League wages — was an unsustainable position pre-promotion.", sentiment: "negative" },
    { text: "Revenue grew from £72m (FY22) to £182m (FY23) on promotion to the Premier League — a 154% increase in one year.", sentiment: "positive" },
    { text: "Net cash of £31-52m in FY22/FY23 swung to £85-92m of net debt by FY24/FY25.", sentiment: "negative" },
    { text: "Wage ratio has remained elevated at ~85% in FY24 and FY25 — the club's cost base has not been restructured to match its income.", sentiment: "negative" },
  ],
  leeds: [
    { text: "Operating loss of £106m in FY23 was one of the largest in the Premier League that year, despite £190m of revenue.", sentiment: "negative" },
    { text: "Revenue fell from £190m (FY23, PL) to £128m (FY24, Championship) on relegation — a £62m drop.", sentiment: "negative" },
    { text: "Net debt reduced from £55m (FY24) to £25m (FY25) — the only consistent positive trend in the financial data.", sentiment: "positive" },
    { text: "Operating losses in all four years reviewed; the club has not operated profitably in any year of this period.", sentiment: "negative" },
  ],
  liverpool: [
    { text: "Revenue was flat at ~£594m in FY22 and FY23 before growing to £703m by FY25.", sentiment: "neutral" },
    { text: "Wage ratio held at 62-63% across FY22–FY24 — one of the most consistent cost ratios at this scale — and improved slightly to ~61% in FY25.", sentiment: "positive" },
    { text: "Net debt grew from £145m (FY22) to £307m (FY24), then reduced to £283m in FY25.", sentiment: "neutral" },
    { text: "Pre-tax result: profit in FY22 (£7.5m) and FY25 (£15m), losses in FY23 and FY24.", sentiment: "neutral" },
  ],
  "man-city": [
    { text: "Wage ratio was 58-59% across all four years — exceptionally stable cost control at revenues exceeding £600m per year.", sentiment: "positive" },
    { text: "Net position swung from net cash of £78-79m (FY22/FY23) to £328m of net debt by FY25.", sentiment: "negative" },
    { text: "Operating losses in all four years; pre-tax profitability in FY22–FY24 was driven entirely by player sales of £68-139m per year.", sentiment: "neutral" },
    { text: "Revenue peaked at £715m in FY24 and declined slightly to £694m in FY25.", sentiment: "neutral" },
  ],
  "man-united": [
    { text: "Wage bill fell from £373m (FY22) to £313m (FY25) — one of the few major clubs to meaningfully reduce its wage cost.", sentiment: "positive" },
    { text: "Wage ratio improved from 69% (FY22) to ~47% (FY25) — the largest proportional improvement in this dataset.", sentiment: "positive" },
    { text: "Net debt has been broadly flat at £534-551m across all four years despite cumulative losses exceeding £300m.", sentiment: "negative" },
    { text: "Operating losses in all four years; FY22 (£92m) and FY24 (£107m) were the worst.", sentiment: "negative" },
  ],
  newcastle: [
    { text: "Revenue grew from £180m (FY22) to £335m (FY25) — nearly doubling in four years following the Saudi-led takeover.", sentiment: "positive" },
    { text: "Wage ratio improved from 95% (FY22) to ~73% (FY25) as revenue grew faster than the wage bill.", sentiment: "positive" },
    { text: "FY25 pre-tax profit of £35m was driven by player sales; operating losses were £109m that year.", sentiment: "neutral" },
    { text: "Net debt moved from net cash of £5m (FY22) to £52m of debt (FY25) — modest relative to the scale of squad investment.", sentiment: "neutral" },
  ],
  "nottm-forest": [
    { text: "Revenue grew from £30m (FY22, Championship) to £222m (FY25) — a 643% increase in four years.", sentiment: "positive" },
    { text: "Wage ratio fell from 197% (FY22) to ~75% (FY25) as Premier League revenues transformed the club's finances.", sentiment: "positive" },
    { text: "FY24 pre-tax profit of £12.1m was generated entirely by £100.5m of player sales; operating losses were £73m.", sentiment: "neutral" },
    { text: "Operating losses in all three Premier League seasons; the club has not operated profitably without player trading income.", sentiment: "negative" },
  ],
  sunderland: [
    { text: "Revenue grew from £26m (League One, FY22) to £39m (Championship, FY25) — steady but modest progress across divisions.", sentiment: "neutral" },
    { text: "Net cash held in FY22/FY23; net debt of £24-28m appeared in FY24/FY25.", sentiment: "neutral" },
    { text: "Pre-tax losses in all four years, ranging from £3m to £10m — material relative to the club's revenue base.", sentiment: "negative" },
  ],
  tottenham: [
    { text: "Net debt grew from £626m (FY22) to £831m (FY25) — the highest of any English club — reflecting the ongoing cost of the stadium development.", sentiment: "negative" },
    { text: "Wage ratio held at 42-47% across all four years — among the lowest in the Premier League — reflecting strong commercial income relative to wages.", sentiment: "positive" },
    { text: "Operating losses in all four years; pre-tax losses are driven primarily by stadium debt interest rather than operational underperformance.", sentiment: "neutral" },
    { text: "Revenue grew from £444m (FY22) to £565m (FY25) — a 27% increase — as the commercial benefits of the new stadium materialised.", sentiment: "positive" },
  ],
  "west-ham": [
    { text: "FY22 was the only year with a pre-tax profit (£13.3m) and positive operating profit (£20.1m) in this four-year period.", sentiment: "positive" },
    { text: "FY25 pre-tax loss of £109m is the worst in the club's four-year record; operating loss alone was £109m.", sentiment: "negative" },
    { text: "Revenue declined from £270m (FY24) to £226m (FY25) — a £44m fall in a single year.", sentiment: "negative" },
    { text: "Net debt swung from net cash of £42m (FY22) to £216m of debt (FY25) — a £258m deterioration over four years.", sentiment: "negative" },
  ],
  wolves: [
    { text: "Revenue was essentially flat at £166-178m across all four years — no meaningful growth over the period.", sentiment: "neutral" },
    { text: "FY25 player sales of £117m offset an operating loss of £117m — the club traded to near break-even on a pre-tax basis.", sentiment: "neutral" },
    { text: "Operating losses in all four years, ranging from £52m (FY22) to £117m (FY25) — a consistent and worsening trend.", sentiment: "negative" },
    { text: "Net debt reduced slightly from £81m (FY23) to £68m (FY25) despite persistent losses, suggesting ongoing owner funding.", sentiment: "neutral" },
  ],
};
