// Norwegian Eliteserien clubs — extracted from annual reports (årsregnskap/årsberetning)
// Monetary values in USD millions (converted from NOK at published FX rates)
// FY2025 conversion: NOK × 0.092 | FY2024 conversion: NOK × 0.093
// Original NOK figures stored in financials.data_notes for reference
// Disclaimer: Figures converted from NOK to USD. Original filings in Norwegian Krone.
// Norwegian clubs are non-profit idrettslag (sports associations) — no corporate tax.
// Some clubs use separate AS entities for commercial/player rights operations.
import type { EUClub } from "./euClubs";

export const noClubs: EUClub[] = [
  // ─── FK Bodø/Glimt ──────────────────────────────────────────────────────────
  // Morselskap (parent entity). FY2025. Figures in USD millions.
  {
    slug: "fk-bodo-glimt",
    name: "FK Bodø/Glimt",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Bodø",
    currency: "USD",
    stadium: { name: "Aspmyra Stadion", capacity: 7269, ownership: "FK Bodø/Glimt (idrettslag)" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 74.4,
      wage_bill: 35.2,
      wage_to_revenue_pct: 47.3,
      net_profit: 18.7,
      total_liabilities: 27.2,
      equity: 43.4,
      operating_profit: 18.9,
      pre_tax_profit: 18.7,
      profit_from_player_sales: 4.6,
      net_debt: -26.5,
      data_notes: "Morselskap (parent entity). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 808,854,870 | wages 382,304,304 | operating profit 205,865,535 | pre-tax profit 203,504,677 | player sales (net) 50,350,885 | equity 471,622,515 | total liabilities 295,395,976 | cash 287,816,841. No bank debt. Nordlandsglimt AS collaboration terminated 2025; player rights now held directly. Champions League + Europa League semi-final 2025.",
    },
    prior_year: {
      season: "FY2024",
      revenue: 56.1,
      wage_bill: 24.3,
      wage_to_revenue_pct: 43.3,
      operating_profit: 5.8,
      profit_from_player_sales: 24.7,
      pre_tax_profit: 6.1,
      net_profit: 6.1,
      net_debt: -12.1,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "LOW",
  },

  // ─── SK Brann ────────────────────────────────────────────────────────────────
  // Consolidated (Sportsklubben Brann + Brann Stadion AS). FY2025.
  {
    slug: "sk-brann",
    name: "SK Brann",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Bergen",
    currency: "USD",
    stadium: { name: "Brann Stadion", capacity: 17686, ownership: "Brann Stadion AS" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 38.4,
      wage_bill: 15.4,
      wage_to_revenue_pct: 40.0,
      net_profit: 9.5,
      total_liabilities: 8.4,
      equity: 34.2,
      operating_profit: 9.4,
      pre_tax_profit: 9.5,
      profit_from_player_sales: 8.7,
      net_debt: -6.2,
      data_notes: "Consolidated (Sportsklubben Brann + Brann Stadion AS). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 417,429,083 | wages 167,041,876 | operating profit 102,636,403 | pre-tax profit 102,732,611 | player sale cash inflows 94,752,862 | equity 372,265,805 | total liabilities 91,080,518 | cash 67,704,578. No bank debt.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "LOW",
  },

  // ─── Rosenborg BK ───────────────────────────────────────────────────────────
  // Konsernregnskap (group). FY2025.
  {
    slug: "rosenborg-bk",
    name: "Rosenborg BK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Trondheim",
    currency: "USD",
    stadium: { name: "Lerkendal Stadion", capacity: 21166, ownership: "Trondheim kommune" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 22.9,
      wage_bill: 12.0,
      wage_to_revenue_pct: 52.6,
      net_profit: 12.9,
      total_liabilities: 31.9,
      equity: 22.9,
      operating_profit: -4.2,
      pre_tax_profit: 12.9,
      profit_from_player_sales: 18.3,
      net_debt: 4.0,
      data_notes: "Konsernregnskap (group). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 248,440,298 | wages 130,741,606 | operating result -45,664,946 | pre-tax profit 140,287,203 | player sales 199,056,884 | equity 248,591,814 | total liabilities 346,666,924 | cash 118,390,242 | LT bank debt 162,263,907. Profit driven by large player sales; underlying operating loss -4.2m USD before player transactions.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── Lillestrøm SK ──────────────────────────────────────────────────────────
  // Parent entity. FY2025.
  {
    slug: "lillestrom-sk",
    name: "Lillestrøm SK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Lillestrøm",
    currency: "USD",
    stadium: { name: "Åråsen Stadion", capacity: 12250, ownership: "Lillestrøm kommune" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 12.7,
      wage_bill: 6.7,
      wage_to_revenue_pct: 52.4,
      net_profit: -0.1,
      total_liabilities: 7.6,
      equity: 4.3,
      operating_profit: -0.1,
      pre_tax_profit: -0.1,
      profit_from_player_sales: 3.4,
      net_debt: -0.7,
      data_notes: "Parent entity (morselskap). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 138,074,970 | wages 72,400,031 | operating result -1,507,831 | annual result -1,306,702 | player sales 37,374,268 | equity 46,508,015 | total liabilities 82,507,234 | cash 11,521,525 | external LT bank debt 3,622,700. Net cash position.",
    },
    prior_year: {
      season: "FY2024",
      revenue: 11.7,
      wage_bill: 7.7,
      wage_to_revenue_pct: 66.2,
      operating_profit: -1.9,
      profit_from_player_sales: 2.3,
      pre_tax_profit: -1.8,
      net_profit: -1.8,
      net_debt: -0.1,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── Tromsø IL ──────────────────────────────────────────────────────────────
  // Parent entity. FY2025.
  {
    slug: "tromso-il",
    name: "Tromsø IL",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Tromsø",
    currency: "USD",
    stadium: { name: "Alfheim Stadion", capacity: 7200, ownership: "Alfheim Arena AS (related entity)" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 14.1,
      wage_bill: 6.4,
      wage_to_revenue_pct: 45.2,
      net_profit: 0.0,
      total_liabilities: 21.2,
      equity: 0.2,
      operating_profit: 0.1,
      pre_tax_profit: 0.0,
      profit_from_player_sales: null,
      net_debt: -0.6,
      data_notes: "Parent entity (morselskap). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 153,220,894 | wages 69,317,488 | operating result 1,529,960 | pre-tax result 130,510 | equity 2,651,578 | total liabilities 229,995,763 | cash 6,665,968. LT intercompany debt 51,238,990 NOK owed to Alfheim Arena AS (stadium entity) — not external bank debt. No external bank debt.",
    },
    prior_year: {
      season: "FY2024",
      revenue: 10.6,
      wage_bill: 4.4,
      wage_to_revenue_pct: 41.9,
      operating_profit: 0.1,
      profit_from_player_sales: null,
      pre_tax_profit: 0.06,
      net_profit: 0.06,
      net_debt: -1.1,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── Kristiansund BK ────────────────────────────────────────────────────────
  // Parent entity. FY2025.
  {
    slug: "kristiansund-bk",
    name: "Kristiansund BK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Kristiansund",
    currency: "USD",
    stadium: { name: "Kristiansund Stadion", capacity: 5765, ownership: "Municipality" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 8.1,
      wage_bill: 3.9,
      wage_to_revenue_pct: 48.3,
      net_profit: 0.1,
      total_liabilities: 3.3,
      equity: 0.6,
      operating_profit: 0.2,
      pre_tax_profit: 0.1,
      profit_from_player_sales: 1.9,
      net_debt: 1.4,
      data_notes: "Parent entity. Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 87,923,668 | wages 42,434,175 | operating result 1,632,829 | pre-tax result 819,270 | player sales 21,056,090 | equity 6,031,850 | total liabilities 35,948,201 | cash 1,663,001 | bank debt (LT 16,228,408 + ST 732,115) 16,960,523.",
    },
    prior_year: {
      season: "FY2024",
      revenue: 7.4,
      wage_bill: 3.4,
      wage_to_revenue_pct: 46.3,
      operating_profit: 0.45,
      profit_from_player_sales: 2.3,
      pre_tax_profit: 0.38,
      net_profit: 0.38,
      net_debt: 1.24,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── Molde FK ────────────────────────────────────────────────────────────────
  // Parent entity (Molde Fotballklubb idrettslag). FY2025.
  // Player rights held separately via Molde Fotball AS / NoRo Fotball AS.
  {
    slug: "molde-fk",
    name: "Molde FK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Molde",
    currency: "USD",
    stadium: { name: "Aker Stadion", capacity: 11800, ownership: "Romsdal Stadion AS" },
    ownership: { summary: "Member-owned idrettslag. Player rights held via Molde Fotball AS / NoRo Fotball AS", category: "Idrettslag with commercial AS structure", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 11.9,
      wage_bill: 14.2,
      wage_to_revenue_pct: 119.9,
      net_profit: -7.3,
      total_liabilities: 21.3,
      equity: 12.9,
      operating_profit: -14.8,
      pre_tax_profit: -7.3,
      profit_from_player_sales: null,
      net_debt: -4.3,
      data_notes: "Parent entity (Molde Fotballklubb idrettslag). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK (rounded): revenue 129,100,000 | wages 154,800,000 | operating result -160,500,000 | annual result -79,200,000 | equity 139,800,000 | total assets 370,800,000 | cash 46,900,000. No bank debt. Wage ratio >100% because player costs borne by the idrettslag but commercial revenues flow through Molde Fotball AS (not consolidated here). Full picture requires Molde Fotball AS accounts.",
    },
    prior_year: {
      season: "FY2024",
      revenue: 21.1,
      wage_bill: 14.1,
      wage_to_revenue_pct: 66.6,
      operating_profit: -4.9,
      profit_from_player_sales: 0.27,
      pre_tax_profit: 0.88,
      net_profit: 0.88,
      net_debt: -9.3,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "PARTIAL",
    volatility_tier: "HIGH",
  },

  // ─── Fredrikstad FK ─────────────────────────────────────────────────────────
  // Parent entity. FY2024 (most recent available).
  {
    slug: "fredrikstad-fk",
    name: "Fredrikstad FK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Fredrikstad",
    currency: "USD",
    stadium: { name: "Fredrikstad Stadion", capacity: 11200, ownership: "Fredrikstad kommune" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 8.6,
      wage_bill: 5.0,
      wage_to_revenue_pct: 57.8,
      net_profit: 0.3,
      total_liabilities: 3.5,
      equity: 0.6,
      operating_profit: 0.3,
      pre_tax_profit: 0.3,
      profit_from_player_sales: null,
      net_debt: -0.4,
      data_notes: "Parent entity. FY2024 — most recent filing available. Figures converted from NOK to USD at FY2024 rate ×0.093. Original NOK: revenue 92,725,486 | wages 53,626,147 | operating result 2,853,829 | pre-tax result 2,766,504 | equity 6,209,392 | total liabilities 37,691,800 | cash 4,216,938. No external bank debt.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── IK Start ────────────────────────────────────────────────────────────────
  // Parent entity (Idrettsklubben Start). FY2025.
  // Revenue primarily via transfer from partner company Stein på Stein 1905 AS.
  {
    slug: "ik-start",
    name: "IK Start",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Kristiansand",
    currency: "USD",
    stadium: { name: "Sparebanken Sør Arena", capacity: 14563, ownership: "Kristiansand kommune" },
    ownership: { summary: "Member-owned idrettslag. Commercial operations via Stein på Stein 1905 AS (partner company)", category: "Idrettslag with commercial AS structure", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 4.6,
      wage_bill: 3.0,
      wage_to_revenue_pct: 65.0,
      net_profit: 0.0,
      total_liabilities: 4.4,
      equity: -1.5,
      operating_profit: 0.0,
      pre_tax_profit: 0.0,
      profit_from_player_sales: null,
      net_debt: 2.7,
      data_notes: "Parent entity (Idrettsklubben Start). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 49,916,439 (of which 35,940,429 is transfer from partner company Stein på Stein 1905 AS) | wages 32,455,830 | annual result 231,649 | equity -16,103,320 (negative equity, accumulated losses) | total assets 31,805,979 | cash 3,757,312 | ansvarlig lån (subordinated loan) 33,150,000.",
    },
    prior_year: {
      season: "FY2024",
      revenue: 2.4,
      wage_bill: 2.1,
      wage_to_revenue_pct: 88.2,
      operating_profit: -0.88,
      profit_from_player_sales: null,
      pre_tax_profit: -0.87,
      net_profit: -0.87,
      net_debt: -0.28,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "HIGH",
  },

  // ─── HamKam ──────────────────────────────────────────────────────────────────
  // Hamarkameratene Fotball Elite. FY2024 (most recent available).
  {
    slug: "hamkam",
    name: "HamKam",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Hamar",
    currency: "USD",
    stadium: { name: "Briskeby Gressbane", capacity: 7668, ownership: "Municipality" },
    ownership: { summary: "Hamarkameratene Fotball Elite — shareholder structure", category: "Limited company (AS)", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: "FY2024",
      revenue: 7.0,
      wage_bill: 4.2,
      wage_to_revenue_pct: 59.4,
      net_profit: 0.1,
      total_liabilities: 2.0,
      equity: 0.5,
      operating_profit: 0.1,
      pre_tax_profit: 0.1,
      profit_from_player_sales: null,
      net_debt: -0.3,
      data_notes: "Hamarkameratene Fotball Elite. FY2024 — most recent filing available. Figures converted from NOK to USD at FY2024 rate ×0.093. Original NOK: revenue 75,102,872 | wages 44,647,934 | operating result 981,867 | pre-tax result 900,078 | equity 5,446,823 | total liabilities 21,625,455 | cash 2,880,584. No bank debt.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "VERIFIED",
    volatility_tier: "MEDIUM",
  },

  // ─── KFUM Oslo ───────────────────────────────────────────────────────────────
  // FY2025. Wage and balance sheet data not available in published report.
  {
    slug: "kfum-oslo",
    name: "KFUM Oslo",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Oslo",
    currency: "USD",
    stadium: { name: "Ekeberg Stadion", capacity: 7000, ownership: "Club/municipality" },
    ownership: { summary: "Member-owned idrettslag (non-profit sports association)", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 9.6,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: 1.4,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      pre_tax_profit: 1.4,
      profit_from_player_sales: null,
      net_debt: null,
      data_notes: "FY2025 partial data — revenue and profit from narrative disclosure only. Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 104,422,828 | annual result 14,932,207. Wage and balance sheet figures not available in published 16-page annual report.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "PARTIAL",
    volatility_tier: null,
  },

  // ─── Sandefjord Fotball ──────────────────────────────────────────────────────
  // Idrettslag (passthrough entity). FY2025.
  // Professional revenues and player sales are at Sandefjord Fotball AS level (not filed).
  {
    slug: "sandefjord-fotball",
    name: "Sandefjord Fotball",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Sandefjord",
    currency: "USD",
    stadium: { name: "Komplett Arena", capacity: 7000, ownership: "Municipality" },
    ownership: { summary: "Sandefjord Fotball idrettslag. Professional operations via Sandefjord Fotball AS", category: "Idrettslag with commercial AS structure", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: "FY2025",
      revenue: 4.1,
      wage_bill: 4.0,
      wage_to_revenue_pct: 96.0,
      net_profit: 0.0,
      total_liabilities: 1.2,
      equity: 0.0,
      operating_profit: 0.0,
      pre_tax_profit: 0.0,
      profit_from_player_sales: null,
      net_debt: -0.2,
      data_notes: "Idrettslag (passthrough entity). Figures converted from NOK to USD at FY2025 rate ×0.092. Original NOK: revenue 44,959,584 (of which 42,253,841 is internal transfer from Sandefjord Fotball AS) | wages 43,180,925 | annual result 0 | equity 0 | total assets 13,405,147 | cash 2,673,666. Professional revenues, commercial activities and player sales are recorded at Sandefjord Fotball AS level — accounts not publicly available. Club finished 5th in Eliteserien 2025.",
    },
    prior_year: {
      season: "FY2024",
      revenue: 3.5,
      wage_bill: 3.4,
      wage_to_revenue_pct: 97.7,
      operating_profit: null,
      profit_from_player_sales: null,
      pre_tax_profit: null,
      net_profit: 0.0,
      net_debt: null,
    },
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "PARTIAL",
    volatility_tier: null,
  },

  // ─── Vålerenga FK ────────────────────────────────────────────────────────────
  // NO_DATA — professional entity is Vålerenga Fotball Elite AS, accounts not available.
  {
    slug: "valerenga-fk",
    name: "Vålerenga FK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Oslo",
    currency: "USD",
    stadium: { name: "Intility Arena", capacity: 17600, ownership: "Oslo kommune" },
    ownership: { summary: "Vålerenga idrettslag (parent). Professional football via Vålerenga Fotball Elite AS", category: "Commercial AS", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      pre_tax_profit: null,
      profit_from_player_sales: null,
      net_debt: null,
      data_notes: "No data available. Professional operations conducted by Vålerenga Fotball Elite AS — accounts not publicly filed. Available document covers only the women's section (Toppserien).",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ─── Viking FK ───────────────────────────────────────────────────────────────
  // NO_DATA — professional entity is Viking Fotball AS, accounts not available.
  {
    slug: "viking-fk",
    name: "Viking FK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Stavanger",
    currency: "USD",
    stadium: { name: "SR-Bank Arena", capacity: 16600, ownership: "SR-Bank Arena AS" },
    ownership: { summary: "Viking Fotballklubb (parent idrettslag). Professional football via Viking Fotball AS", category: "Commercial AS", fifty_plus_one: "N/A" },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      pre_tax_profit: null,
      profit_from_player_sales: null,
      net_debt: null,
      data_notes: "No data available. Professional operations conducted by Viking Fotball AS — accounts not publicly filed. Available document (Årsrapport 24.pdf) covers Viking Fotballklubb, the grassroots parent association (~20m NOK member revenue), not the Eliteserien professional entity.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ─── Aalesund FK ─────────────────────────────────────────────────────────────
  // NO_DATA — only women's section (AaFK Fortuna) filing available, not the men's club.
  {
    slug: "aalesund-fk",
    name: "Aalesund FK",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Ålesund",
    currency: "USD",
    stadium: { name: "Color Line Stadion", capacity: 11800, ownership: "Municipality" },
    ownership: { summary: "Aalesunds FK — member-owned association", category: "Idrettslag", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      pre_tax_profit: null,
      profit_from_player_sales: null,
      net_debt: null,
      data_notes: "No data available. Only available document (Årsmelding 2025 AaFK Fortuna.pdf) covers the women's football section, not the men's Eliteserien club.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "NO_DATA",
    volatility_tier: null,
  },

  // ─── Sarpsborg 08 FF ─────────────────────────────────────────────────────────
  // NO_DATA — no annual report available for the Eliteserien club.
  {
    slug: "sarpsborg-08",
    name: "Sarpsborg 08 FF",
    country: "Norway",
    league: "norwegian-eliteserien",
    city: "Sarpsborg",
    currency: "USD",
    stadium: { name: "Sarpsborg Stadion", capacity: 7000, ownership: "Sarpsborg kommune" },
    ownership: { summary: "Sarpsborg 08 Fotballforening — member-owned", category: "Fotballforening", fifty_plus_one: "Yes — member-owned" },
    financials: {
      most_recent_year: null,
      revenue: null,
      wage_bill: null,
      wage_to_revenue_pct: null,
      net_profit: null,
      total_liabilities: null,
      equity: null,
      operating_profit: null,
      pre_tax_profit: null,
      profit_from_player_sales: null,
      net_debt: null,
      data_notes: "No annual report available for Sarpsborg 08 FF. Document available was for Sarpsborg Fotballklubb (a 4th division grassroots club), not the Eliteserien entity.",
    },
    prior_year: null,
    historical: [],
    tm_squad_value_eur_m: null,
    data_status: "NO_DATA",
    volatility_tier: null,
  },
];
