export type SquadProfile = {
  squad_value_eur_m: number | null;
};

export const squadProfiles: Record<string, SquadProfile> = {
  // Netherlands — Eredivisie / Eerste Divisie
  "ajax":              { squad_value_eur_m: 175.0 },
  "psv":               { squad_value_eur_m: 240.0 },
  "feyenoord":         { squad_value_eur_m: 165.0 },
  "az":                { squad_value_eur_m:  75.0 },
  "fc-twente":         { squad_value_eur_m:  42.0 },
  "fc-utrecht":        { squad_value_eur_m:  35.0 },
  "sparta-rotterdam":  { squad_value_eur_m:  18.0 },
  "nec":               { squad_value_eur_m:  28.0 },
  "go-ahead-eagles":   { squad_value_eur_m:  15.0 },
  "sc-heerenveen":     { squad_value_eur_m:  22.0 },
  "pec-zwolle":        { squad_value_eur_m:  14.0 },
  "heracles-almelo":   { squad_value_eur_m:  11.0 },
  "fortuna-sittard":   { squad_value_eur_m:  13.0 },
  "rkc-waalwijk":      { squad_value_eur_m:  10.0 },
  "willem-ii":         { squad_value_eur_m:  12.0 },
  "nac-breda":         { squad_value_eur_m:  10.0 },
  "almere-city":       { squad_value_eur_m:   8.0 },
  "fc-groningen":      { squad_value_eur_m:  15.0 },
  "vitesse":           { squad_value_eur_m:   5.0 },
  "roda-jc":           { squad_value_eur_m:   8.0 },
  "mvv-maastricht":    { squad_value_eur_m:   4.0 },
  "de-graafschap":     { squad_value_eur_m:   6.0 },
  "fc-dordrecht":      { squad_value_eur_m:   4.0 },
  "sc-cambuur":        { squad_value_eur_m:   7.0 },
  "fc-den-bosch":      { squad_value_eur_m:   3.0 },
  "helmond-sport":     { squad_value_eur_m:   3.0 },
  "top-oss":           { squad_value_eur_m:   3.0 },
  "fc-eindhoven":      { squad_value_eur_m:   4.0 },
  "vvv-venlo":         { squad_value_eur_m:   5.0 },
  "fc-emmen":          { squad_value_eur_m:   4.0 },
  "ado-den-haag":      { squad_value_eur_m:   7.0 },
  "jong-ajax":         { squad_value_eur_m:  20.0 },
  "jong-az":           { squad_value_eur_m:  12.0 },
  "jong-utrecht":      { squad_value_eur_m:   8.0 },
  "jong-psv":          { squad_value_eur_m:  15.0 },
  "telstar":           { squad_value_eur_m:   3.0 },
  "fc-volendam":       { squad_value_eur_m:   6.0 },
  "excelsior":         { squad_value_eur_m:   6.0 },
};
