// Swedish Allsvenskan (and Damallsvenskan) clubs — values in USD millions
// Source: Statutory annual accounts (årsredovisning) filed at Bolagsverket / club websites
// Calendar year Jan–Dec. Koncern (group) accounts used where available.
// Converted from SEK using annual average FX rates: 2025 = 10.47, 2024 = 10.53, 2023 = 10.50, 2022 = 10.12 SEK/USD
// net_profit = resultat efter finansiella poster (pre-tax; Swedish clubs are non-profit ideella föreningar)
// net_debt   = financial bank debt minus cash (negative = net cash); pension provisions excluded

import { EUClub } from "./euClubs";

export const swClubs: EUClub[] = [
  // ─── Malmö FF ───────────────────────────────────────────────────────────────
  {
    slug: "malmo-ff",
    name: "Malmö FF",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Malmö",
    currency: "USD",
    stadium: { name: "Eleda Stadion", capacity: 22500, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 51.9,
      wage_bill: 30.8,
      wage_to_revenue_pct: 59.3,
      net_profit: -8.5,
      operating_profit: -8.0,
      pre_tax_profit: -8.5,
      net_debt: -13.1,
      total_liabilities: null,
      equity: null,
      data_notes: "Own-reported net cash of SEK 136.8m (USD 13.1m). Player amortisation SEK 45.9m.",
    },
    historical: [
      { season: "2022", revenue: 58.2, wage_bill: 24.8, net_profit: 8.1, operating_profit: 8.1, net_debt: -21.8 },
      { season: "2023", revenue: 41.2, wage_bill: 20.9, net_profit: 0.1, operating_profit: 0.1, net_debt: -12.0 },
      { season: "2024", revenue: 62.7, wage_bill: 27.6, net_profit: 5.9, operating_profit: 5.9, net_debt: -17.7 },
      { season: "2025", revenue: 51.9, wage_bill: 30.8, net_profit: -8.5, operating_profit: -8.0, net_debt: -13.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Hammarby IF ────────────────────────────────────────────────────────────
  {
    slug: "hammarby-if",
    name: "Hammarby IF",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Stockholm",
    currency: "USD",
    stadium: { name: "Tele2 Arena", capacity: 30000, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 43.5,
      wage_bill: 16.5,
      wage_to_revenue_pct: 37.9,
      net_profit: 10.5,
      operating_profit: 10.9,
      pre_tax_profit: 10.5,
      net_debt: -6.6,
      total_liabilities: null,
      equity: null,
      data_notes: "Post-balance sheet: Adrian Lahdo sold to Como 1907.",
    },
    historical: [
      { season: "2022", revenue: 33.5, wage_bill: 14.5, net_profit: 4.2, operating_profit: 4.2, net_debt: 0.5 },
      { season: "2023", revenue: 25.5, wage_bill: 15.1, net_profit: -1.6, operating_profit: -1.6, net_debt: -2.7 },
      { season: "2024", revenue: 36.5, wage_bill: 16.0, net_profit: 5.0, operating_profit: 5.0, net_debt: -3.1 },
      { season: "2025", revenue: 43.5, wage_bill: 16.5, net_profit: 10.5, operating_profit: 10.9, net_debt: -6.6 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Djurgårdens IF ─────────────────────────────────────────────────────────
  {
    slug: "djurgarden",
    name: "Djurgårdens IF",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Stockholm",
    currency: "USD",
    stadium: { name: "Stockholm Stadion", capacity: 14417, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 37.0,
      wage_bill: 18.3,
      wage_to_revenue_pct: 49.5,
      net_profit: 3.8,
      operating_profit: 3.8,
      pre_tax_profit: 3.8,
      net_debt: -9.6,
      total_liabilities: null,
      equity: null,
      data_notes: "Koncern accounts. No financial bank debt; net cash position all years. Revenue includes substantial player sales.",
    },
    historical: [
      { season: "2022", revenue: 34.0, wage_bill: 12.9, net_profit: 10.7, operating_profit: 10.7, net_debt: -14.4 },
      { season: "2023", revenue: 25.6, wage_bill: 12.9, net_profit: 3.6, operating_profit: 3.6, net_debt: -15.5 },
      { season: "2024", revenue: 41.4, wage_bill: 17.8, net_profit: 11.0, operating_profit: 11.0, net_debt: -9.7 },
      { season: "2025", revenue: 37.0, wage_bill: 18.3, net_profit: 3.8, operating_profit: 3.8, net_debt: -9.6 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── AIK ────────────────────────────────────────────────────────────────────
  {
    slug: "aik",
    name: "AIK",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Stockholm",
    currency: "USD",
    stadium: { name: "Friends Arena", capacity: 50000, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 33.9,
      wage_bill: 18.0,
      wage_to_revenue_pct: 53.0,
      net_profit: -1.7,
      operating_profit: -1.5,
      pre_tax_profit: -1.7,
      net_debt: -0.7,
      total_liabilities: null,
      equity: null,
      data_notes: "Koncern (group) accounts. Net debt = bank debt (SEK 153.7m) less cash (SEK 228.1m). Player sales proceeds SEK 58.1m in FY2025; solidarity fee receivable from Alexander Isak (Newcastle→Liverpool) transfer.",
    },
    historical: [
      { season: "2022", revenue: 26.7, wage_bill: 13.9, net_profit: 1.9, operating_profit: 1.9, net_debt: -4.9 },
      { season: "2023", revenue: 24.8, wage_bill: 15.0, net_profit: -2.9, operating_profit: -2.9, net_debt: -1.3 },
      { season: "2024", revenue: 30.0, wage_bill: 14.8, net_profit: 0.9, operating_profit: 1.0, net_debt: -2.4 },
      { season: "2025", revenue: 33.9, wage_bill: 18.0, net_profit: -1.7, operating_profit: -1.5, net_debt: -0.7 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── IF Elfsborg ────────────────────────────────────────────────────────────
  {
    slug: "if-elfsborg",
    name: "IF Elfsborg",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Borås",
    currency: "USD",
    stadium: { name: "Borås Arena", capacity: 16200, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 23.4,
      wage_bill: 12.2,
      wage_to_revenue_pct: 52.1,
      net_profit: 1.6,
      operating_profit: 2.0,
      pre_tax_profit: 1.6,
      net_debt: 11.2,
      total_liabilities: null,
      equity: null,
      data_notes: "Bank debt SEK 184.8m (USD 17.6m) largely funding capitalised player acquisitions.",
    },
    historical: [
      { season: "2022", revenue: 14.4, wage_bill: 6.9, net_profit: 1.6, operating_profit: 1.6, net_debt: 16.0 },
      { season: "2023", revenue: 18.9, wage_bill: 8.3, net_profit: 3.5, operating_profit: 3.5, net_debt: 12.7 },
      { season: "2024", revenue: 24.9, wage_bill: 10.5, net_profit: 4.8, operating_profit: 4.8, net_debt: 9.4 },
      { season: "2025", revenue: 23.4, wage_bill: 12.2, net_profit: 1.6, operating_profit: 2.0, net_debt: 11.2 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── IFK Göteborg ───────────────────────────────────────────────────────────
  {
    slug: "ifk-goteborg",
    name: "IFK Göteborg",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Göteborg",
    currency: "USD",
    stadium: { name: "Gamla Ullevi", capacity: 18416, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 20.4,
      wage_bill: 8.8,
      wage_to_revenue_pct: 43.1,
      net_profit: -0.5,
      operating_profit: -0.3,
      pre_tax_profit: -0.5,
      net_debt: 3.2,
      total_liabilities: null,
      equity: null,
      data_notes: "Koncern accounts. Net debt: SEK 36.9m bank debt less SEK 3.8m cash. Pension insurance provisions SEK 178.1m excluded from net debt.",
    },
    historical: [
      { season: "2022", revenue: 15.0, wage_bill: 7.1, net_profit: 0.7, operating_profit: 0.7, net_debt: 1.7 },
      { season: "2023", revenue: 16.0, wage_bill: 7.8, net_profit: -0.8, operating_profit: -0.8, net_debt: 1.7 },
      { season: "2024", revenue: 22.8, wage_bill: 8.7, net_profit: 3.0, operating_profit: 3.0, net_debt: 1.2 },
      { season: "2025", revenue: 20.4, wage_bill: 8.8, net_profit: -0.5, operating_profit: -0.3, net_debt: 3.2 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── IK Sirius ──────────────────────────────────────────────────────────────
  {
    slug: "ik-sirius",
    name: "IK Sirius",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Uppsala",
    currency: "USD",
    stadium: { name: "Studenternas IP", capacity: 8500, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 15.6,
      wage_bill: 6.8,
      wage_to_revenue_pct: 43.6,
      net_profit: 2.7,
      operating_profit: 2.7,
      pre_tax_profit: 2.7,
      net_debt: -2.0,
      total_liabilities: null,
      equity: null,
      data_notes: "Revenue includes youth tournaments (Gothia Cup). No financial bank debt on balance sheet.",
    },
    historical: [
      { season: "2022", revenue: 8.3, wage_bill: 4.3, net_profit: 1.2, operating_profit: 1.2, net_debt: -2.7 },
      { season: "2023", revenue: 8.2, wage_bill: 4.2, net_profit: 0.8, operating_profit: 0.8, net_debt: -2.6 },
      { season: "2024", revenue: 11.1, wage_bill: 5.2, net_profit: 1.9, operating_profit: 1.9, net_debt: -3.2 },
      { season: "2025", revenue: 15.6, wage_bill: 6.8, net_profit: 2.7, operating_profit: 2.7, net_debt: -2.0 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── IF Brommapojkarna ──────────────────────────────────────────────────────
  {
    slug: "if-brommapojkarna",
    name: "IF Brommapojkarna",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Stockholm",
    currency: "USD",
    stadium: null,
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 15.9,
      wage_bill: 7.0,
      wage_to_revenue_pct: 44.0,
      net_profit: 1.4,
      operating_profit: 1.4,
      pre_tax_profit: 1.4,
      net_debt: -1.3,
      total_liabilities: null,
      equity: null,
      data_notes: "Revenue includes public grants (SEK 5.2m) and membership fees. Post-balance sheet: Ezekiel Alladoh and Love Arrhov sold.",
    },
    historical: [
      { season: "2022", revenue: 6.9, wage_bill: null, net_profit: 0.2, operating_profit: 0.2, net_debt: -2.3 },
      { season: "2023", revenue: 9.1, wage_bill: 5.4, net_profit: 0.2, operating_profit: 0.2, net_debt: -2.7 },
      { season: "2024", revenue: 13.3, wage_bill: 6.3, net_profit: 1.0, operating_profit: 1.0, net_debt: -1.4 },
      { season: "2025", revenue: 15.9, wage_bill: 7.0, net_profit: 1.4, operating_profit: 1.4, net_debt: -1.3 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── GAIS ───────────────────────────────────────────────────────────────────
  {
    slug: "gais",
    name: "GAIS",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Göteborg",
    currency: "USD",
    stadium: { name: "Gamla Ullevi", capacity: 18416, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 9.8,
      wage_bill: 3.9,
      wage_to_revenue_pct: 39.8,
      net_profit: 1.5,
      operating_profit: 1.4,
      pre_tax_profit: 1.5,
      net_debt: -2.1,
      total_liabilities: null,
      equity: null,
      data_notes: "Moderförening accounts (no group subsidiary). Expenses all player acquisitions directly (no capitalisation). Net transfer income SEK 10.4m.",
    },
    historical: [
      { season: "2022", revenue: 2.0, wage_bill: 0.8, net_profit: 0.0, operating_profit: 0.0, net_debt: 0.1 },
      { season: "2023", revenue: 3.8, wage_bill: 1.5, net_profit: 0.5, operating_profit: 0.5, net_debt: -0.6 },
      { season: "2024", revenue: 7.1, wage_bill: 2.7, net_profit: 1.2, operating_profit: 1.2, net_debt: -2.0 },
      { season: "2025", revenue: 9.8, wage_bill: 3.9, net_profit: 1.5, operating_profit: 1.4, net_debt: -2.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── VSK Fotboll (Västerås SK) ──────────────────────────────────────────────
  {
    slug: "vsk-fotboll",
    name: "VSK Fotboll",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Västerås",
    currency: "USD",
    stadium: { name: "ABB Arena Syd", capacity: 7700, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 9.5,
      wage_bill: 2.7,
      wage_to_revenue_pct: 28.4,
      net_profit: 2.9,
      operating_profit: 2.9,
      pre_tax_profit: 2.9,
      net_debt: -1.9,
      total_liabilities: null,
      equity: null,
      data_notes: "Played in Superettan 2025; promoted to Allsvenskan 2026. Transfer net income SEK 40.7m drives headline result. Operative (ex-transfers) result: SEK -10.1m.",
    },
    historical: [
      { season: "2022", revenue: 1.8, wage_bill: 1.4, net_profit: -0.5, operating_profit: -0.5, net_debt: -0.2 },
      { season: "2023", revenue: 2.9, wage_bill: 1.4, net_profit: 0.2, operating_profit: 0.2, net_debt: -0.8 },
      { season: "2024", revenue: 7.1, wage_bill: null, net_profit: 1.1, operating_profit: 1.1 },
      { season: "2025", revenue: 9.5, wage_bill: 2.7, net_profit: 2.9, operating_profit: 2.9, net_debt: -1.9 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Kalmar FF ──────────────────────────────────────────────────────────────
  {
    slug: "kalmar-ff",
    name: "Kalmar FF",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Kalmar",
    currency: "USD",
    stadium: { name: "Guldfågeln Arena", capacity: 12000, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 7.9,
      wage_bill: 4.1,
      wage_to_revenue_pct: 51.9,
      net_profit: 0.7,
      operating_profit: 0.7,
      pre_tax_profit: 0.7,
      net_debt: -1.2,
      total_liabilities: null,
      equity: null,
      data_notes: "Played in Superettan 2025; promoted to Allsvenskan 2026. No bank debt; net cash position all years. Player rights net cash +SEK 6.5m.",
    },
    historical: [
      { season: "2022", revenue: 7.6, wage_bill: 4.5, net_profit: 0.2, operating_profit: 0.2, net_debt: -1.3 },
      { season: "2023", revenue: 9.3, wage_bill: 4.8, net_profit: 0.7, operating_profit: 0.7, net_debt: -1.7 },
      { season: "2024", revenue: 9.0, wage_bill: 4.6, net_profit: 0.8, operating_profit: 0.8, net_debt: -1.1 },
      { season: "2025", revenue: 7.9, wage_bill: 4.1, net_profit: 0.7, operating_profit: 0.7, net_debt: -1.2 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Mjällby AIF ────────────────────────────────────────────────────────────
  {
    slug: "mjallby-aif",
    name: "Mjällby AIF",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Sölvesborg",
    currency: "USD",
    stadium: { name: "Strandvallen", capacity: 7500, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024",
      revenue: 8.0,
      wage_bill: 4.5,
      wage_to_revenue_pct: 56.3,
      net_profit: 1.3,
      operating_profit: 1.3,
      pre_tax_profit: 1.3,
      net_debt: -2.9,
      total_liabilities: null,
      equity: null,
      data_notes: "FY2024 (most recent available). Historic 5th-place Allsvenskan finish in 2024.",
    },
    historical: [
      { season: "2022", revenue: 5.3, wage_bill: 3.6, net_profit: 0.1, operating_profit: 0.1, net_debt: -0.9 },
      { season: "2023", revenue: 8.0, wage_bill: 4.2, net_profit: 1.5, operating_profit: 1.5, net_debt: -2.4 },
      { season: "2024", revenue: 8.0, wage_bill: 4.5, net_profit: 1.3, operating_profit: 1.3, net_debt: -2.9 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Degerfors IF ───────────────────────────────────────────────────────────
  {
    slug: "degerfors-if",
    name: "Degerfors IF",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Degerfors",
    currency: "USD",
    stadium: { name: "Stora Valla", capacity: 7500, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 7.1,
      wage_bill: 4.1,
      wage_to_revenue_pct: 57.2,
      net_profit: -0.1,
      operating_profit: -0.1,
      pre_tax_profit: -0.1,
      net_debt: -0.1,
      total_liabilities: null,
      equity: null,
      data_notes: "Won Superettan 2025; promoted to Allsvenskan 2026. Revenue includes player sale income (SEK 8.2m gross).",
    },
    historical: [
      { season: "2024", revenue: 4.7, wage_bill: 2.3, net_profit: 0.5, operating_profit: 0.4, net_debt: -0.7 },
      { season: "2025", revenue: 7.1, wage_bill: 4.1, net_profit: -0.1, operating_profit: -0.1, net_debt: -0.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Halmstads BK ───────────────────────────────────────────────────────────
  {
    slug: "halmstads-bk",
    name: "Halmstads BK",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Halmstad",
    currency: "USD",
    stadium: { name: "Örjans Valls IP", capacity: 15500, ownership: null },
    ownership: { summary: "Halmstads Bollklubb (ideell förening) + HBK Elitfotboll AB", category: "Hybrid non-profit/limited company", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2024",
      revenue: 8.0,
      wage_bill: 4.7,
      wage_to_revenue_pct: 58.8,
      net_profit: -0.3,
      operating_profit: -0.3,
      pre_tax_profit: -0.3,
      net_debt: -0.1,
      total_liabilities: null,
      equity: null,
      data_notes: "FY2024 (most recent available). Revenue includes player sales net SEK 12.5m.",
    },
    historical: [
      { season: "2022", revenue: 4.7, wage_bill: 2.8, net_profit: 0.0, operating_profit: 0.0, net_debt: -0.6 },
      { season: "2023", revenue: 6.5, wage_bill: 3.6, net_profit: 0.1, operating_profit: 0.1, net_debt: -1.4 },
      { season: "2024", revenue: 8.0, wage_bill: 4.7, net_profit: -0.3, operating_profit: -0.3, net_debt: -0.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── Örgryte IS ─────────────────────────────────────────────────────────────
  {
    slug: "orgryte-is",
    name: "Örgryte IS",
    country: "Sweden",
    league: "Allsvenskan",
    city: "Göteborg",
    currency: "USD",
    stadium: { name: "Gamla Ullevi", capacity: 18416, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 4.1,
      wage_bill: 2.1,
      wage_to_revenue_pct: 51.2,
      net_profit: 0.1,
      operating_profit: 0.1,
      pre_tax_profit: 0.1,
      net_debt: 0.3,
      total_liabilities: null,
      equity: null,
      data_notes: "First season back in Allsvenskan since 2009. SEK 6.6m bank loan taken in FY2025 for new artificial pitch.",
    },
    historical: [
      { season: "2024", revenue: 3.2, wage_bill: 1.8, net_profit: -0.1, operating_profit: -0.1, net_debt: -0.1 },
      { season: "2025", revenue: 4.1, wage_bill: 2.1, net_profit: 0.1, operating_profit: 0.1, net_debt: 0.3 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },

  // ─── BK Häcken FF (women's section) ─────────────────────────────────────────
  {
    slug: "bk-hacken-ff",
    name: "BK Häcken FF",
    country: "Sweden",
    league: "Damallsvenskan",
    city: "Göteborg",
    currency: "USD",
    stadium: { name: "Gothia Park Academy", capacity: null, ownership: null },
    ownership: { summary: "Ideell förening (non-profit association)", category: "Member-owned", fifty_plus_one: null },
    financials: {
      most_recent_year: "FY2025",
      revenue: 4.2,
      wage_bill: 2.8,
      wage_to_revenue_pct: 66.7,
      net_profit: -0.1,
      operating_profit: -0.1,
      pre_tax_profit: -0.1,
      net_debt: -0.1,
      total_liabilities: null,
      equity: null,
      data_notes: "Women's football section of BK Häcken. Won OBOS Damallsvenskan 2025. No financial bank debt.",
    },
    historical: [
      { season: "2022", revenue: 3.0, wage_bill: 1.8, net_profit: 0.0, operating_profit: 0.0, net_debt: 0.0 },
      { season: "2023", revenue: 3.3, wage_bill: 1.9, net_profit: 0.0, operating_profit: 0.0, net_debt: -0.1 },
      { season: "2024", revenue: 4.1, wage_bill: 2.4, net_profit: 0.1, operating_profit: 0.1, net_debt: -0.2 },
      { season: "2025", revenue: 4.2, wage_bill: 2.8, net_profit: -0.1, operating_profit: -0.1, net_debt: -0.1 },
    ],
    data_status: "VERIFIED",
    volatility_tier: null,
  },
];
