#!/usr/bin/env python3
"""
enrich_stadium_data.py

Fetches stadium data for every club in transfermarkt_mapping.json
and writes lib/stadiumData.ts.

Data fetched per club (1 API call each):
  /clubs/{id}/profile → stadiumName, stadiumSeats

NOT available via this API:
  avg_attendance — no attendance endpoint in transfermarkt-api
  attendance_pct — derived; will be null since avg_attendance unavailable

Usage:
    # Dry-run: validate mappings, preview data, write nothing
    python scripts/enrich_stadium_data.py --dry-run

    # Full run: fetch and write lib/stadiumData.ts
    python scripts/enrich_stadium_data.py

    # Single region
    python scripts/enrich_stadium_data.py --region english

    # Retry only clubs that errored
    python scripts/enrich_stadium_data.py --retry-errors

Output: lib/stadiumData.ts
"""

import argparse
import json
import sys
import time
from datetime import date
from pathlib import Path
from typing import Optional

try:
    import requests
except ImportError:
    print("ERROR: 'requests' not installed.  Run:  pip install requests")
    sys.exit(1)

# ─── Config ───────────────────────────────────────────────────────────────────

BASE_URL      = "http://localhost:8000"
DELAY_SECONDS = 1.2
MAPPING_PATH  = Path(__file__).parent / "transfermarkt_mapping.json"
OUTPUT_PATH   = Path(__file__).parent.parent / "lib" / "stadiumData.ts"
TODAY         = date.today()

# ─── Error category constants ─────────────────────────────────────────────────

ERR_NOT_FOUND    = "club_not_found"     # HTTP 404
ERR_UNAVAILABLE  = "data_unavailable"   # 200 but all stadium fields null/missing
ERR_API_ERROR    = "api_error"          # timeout, 5xx, parse failure

# ─── API helper ───────────────────────────────────────────────────────────────

def get(session: requests.Session, path: str) -> tuple[Optional[dict], Optional[str]]:
    """
    Returns (data, error_category).
    On success: (dict, None)
    On failure: (None, ERR_*)
    """
    url = f"{BASE_URL}{path}"
    try:
        r = session.get(url, timeout=12)
        if r.status_code == 404:
            return None, ERR_NOT_FOUND
        r.raise_for_status()
        return r.json(), None
    except requests.exceptions.Timeout:
        return None, ERR_API_ERROR
    except requests.exceptions.HTTPError:
        return None, ERR_API_ERROR
    except Exception:
        return None, ERR_API_ERROR

# ─── Fetch stadium data for one club ─────────────────────────────────────────

def fetch_stadium(session: requests.Session, tm_id: str) -> tuple[dict, Optional[str]]:
    """
    Returns (result_dict, error_category).
    result_dict always has: stadium_name, capacity, avg_attendance, attendance_pct
    error_category is set when all data is unavailable.
    Partial success (capacity present, attendance null) returns no error.
    """
    data, err = get(session, f"/clubs/{tm_id}/profile")

    if err == ERR_NOT_FOUND:
        return {
            "stadium_name": None, "capacity": None,
            "avg_attendance": None, "attendance_pct": None,
        }, ERR_NOT_FOUND

    if err == ERR_API_ERROR or data is None:
        return {
            "stadium_name": None, "capacity": None,
            "avg_attendance": None, "attendance_pct": None,
        }, ERR_API_ERROR

    stadium_name = data.get("stadiumName") or None
    raw_seats    = data.get("stadiumSeats")
    capacity: Optional[int] = int(raw_seats) if raw_seats and int(raw_seats) > 0 else None

    # avg_attendance: not available from this API
    avg_attendance: Optional[float] = None
    attendance_pct: Optional[float] = None

    if capacity is None and stadium_name is None:
        return {
            "stadium_name": None, "capacity": None,
            "avg_attendance": None, "attendance_pct": None,
        }, ERR_UNAVAILABLE

    return {
        "stadium_name": stadium_name,
        "capacity":     capacity,
        "avg_attendance": avg_attendance,
        "attendance_pct": attendance_pct,
    }, None

# ─── TypeScript output ────────────────────────────────────────────────────────

def ts_val(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, str):
        escaped = v.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    if isinstance(v, float):
        return f"{v:.1f}"
    return str(v)

def write_ts(results: dict[str, dict]) -> None:
    lines = [
        "// AUTO-GENERATED by scripts/enrich_stadium_data.py — do not edit manually.",
        f"// Generated: {TODAY}",
        "// Source: Transfermarkt (via transfermarkt-api, https://github.com/felipeall/transfermarkt-api)",
        "//",
        "// avg_attendance and attendance_pct are null for all clubs — no attendance",
        "// endpoint exists in this version of the transfermarkt-api.",
        "",
        "export type StadiumData = {",
        "  stadium_name:    string | null;",
        "  capacity:        number | null;",
        "  avg_attendance:  number | null;",
        "  attendance_pct:  number | null;  // avg_attendance / capacity × 100",
        "};",
        "",
        "export const stadiumData: Record<string, StadiumData> = {",
    ]

    for slug in sorted(results.keys()):
        r = results[slug]
        lines.append(f'  "{slug}": {{')
        lines.append(f'    stadium_name:    {ts_val(r["stadium_name"])},')
        lines.append(f'    capacity:        {ts_val(r["capacity"])},')
        lines.append(f'    avg_attendance:  {ts_val(r["avg_attendance"])},')
        lines.append(f'    attendance_pct:  {ts_val(r["attendance_pct"])},')
        lines.append( '  },')

    lines.append("};")
    lines.append("")

    OUTPUT_PATH.write_text("\n".join(lines), encoding="utf-8")
    print(f"\n✓ Written to {OUTPUT_PATH}")

# ─── Main ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Enrich stadium data from Transfermarkt API")
    parser.add_argument("--dry-run",      action="store_true", help="Preview only — write nothing")
    parser.add_argument("--region",       choices=["english", "eu", "japan"], help="Only process one region")
    parser.add_argument("--retry-errors", action="store_true", help="Skip clubs that already have data; only retry errors")
    args = parser.parse_args()

    mapping: dict = json.loads(MAPPING_PATH.read_text())

    # Filter by region if requested
    clubs = {
        slug: info for slug, info in mapping.items()
        if args.region is None or info.get("region") == args.region
    }

    # If retry-errors mode and output already exists, skip clubs with data
    existing: dict[str, dict] = {}
    if args.retry_errors and OUTPUT_PATH.exists():
        # We can't easily parse TS — just run all in this mode as a safe fallback
        print("⚠  --retry-errors: re-fetching all clubs (TS parse not supported; idempotent anyway)")

    total = len(clubs)
    print(f"{'DRY RUN — ' if args.dry_run else ''}Processing {total} clubs"
          + (f" ({args.region} only)" if args.region else ""))
    print(f"API base: {BASE_URL}\n")

    results: dict[str, dict] = {}
    errors: dict[str, list[str]] = {
        ERR_NOT_FOUND:   [],
        ERR_UNAVAILABLE: [],
        ERR_API_ERROR:   [],
    }

    with requests.Session() as session:
        session.headers.update({"User-Agent": "insighteleven-enrichment/1.0"})

        for i, (slug, info) in enumerate(clubs.items(), 1):
            tm_id    = info["tm_id"]
            tm_name  = info.get("tm_name", slug)
            region   = info.get("region", "?")
            confidence = info.get("confidence", "?")

            prefix = f"[{i:>3}/{total}] {slug:<35} (TM:{tm_id:<6})"

            if args.dry_run:
                print(f"{prefix} → would fetch /clubs/{tm_id}/profile")
                # In dry-run, do the actual fetch so we can report real data

            result, err = fetch_stadium(session, tm_id)

            if err == ERR_NOT_FOUND:
                errors[ERR_NOT_FOUND].append(slug)
                print(f"{prefix} ✗ NOT FOUND (confidence={confidence})")
            elif err == ERR_API_ERROR:
                errors[ERR_API_ERROR].append(slug)
                print(f"{prefix} ✗ API ERROR")
            elif err == ERR_UNAVAILABLE:
                errors[ERR_UNAVAILABLE].append(slug)
                print(f"{prefix} ⚠  DATA UNAVAILABLE (no stadium fields in profile)")
            else:
                name_str = result["stadium_name"] or "—"
                cap_str  = f"{result['capacity']:,}" if result["capacity"] else "—"
                print(f"{prefix} ✓  {name_str:<35} cap={cap_str}")

            results[slug] = result

            if i < total:
                time.sleep(DELAY_SECONDS)

    # ── Summary ──────────────────────────────────────────────────────────────
    ok_count   = sum(1 for r in results.values() if r["stadium_name"] is not None or r["capacity"] is not None)
    null_count = total - ok_count

    print(f"\n{'─' * 60}")
    print(f"SUMMARY")
    print(f"  Total clubs:          {total}")
    print(f"  With stadium data:    {ok_count}")
    print(f"  No data:              {null_count}")
    print(f"  avg_attendance:       null for ALL clubs (API limitation)")
    print(f"  attendance_pct:       null for ALL clubs (derived; requires attendance)")
    print(f"\nErrors by category:")
    print(f"  Club not found (404): {len(errors[ERR_NOT_FOUND])}")
    print(f"  Data unavailable:     {len(errors[ERR_UNAVAILABLE])}")
    print(f"  API errors:           {len(errors[ERR_API_ERROR])}")

    if errors[ERR_NOT_FOUND]:
        print(f"\n  Not found slugs:  {', '.join(errors[ERR_NOT_FOUND][:10])}"
              + (" ..." if len(errors[ERR_NOT_FOUND]) > 10 else ""))
    if errors[ERR_UNAVAILABLE]:
        print(f"\n  No-data slugs:    {', '.join(errors[ERR_UNAVAILABLE][:10])}"
              + (" ..." if len(errors[ERR_UNAVAILABLE]) > 10 else ""))
    if errors[ERR_API_ERROR]:
        print(f"\n  API error slugs:  {', '.join(errors[ERR_API_ERROR][:10])}"
              + (" ..." if len(errors[ERR_API_ERROR]) > 10 else ""))

    if args.dry_run:
        print(f"\n{'─' * 60}")
        print("DRY RUN complete — nothing written.")
        print(f"To write lib/stadiumData.ts, re-run without --dry-run")
    else:
        write_ts(results)


if __name__ == "__main__":
    main()
